[workspace]
members = ["viper", "viper-sys", "prusti_contracts", "prusti-interface", "prusti", "prusti-viper", "jni-gen", "jni-gen/testcrate"]

[replace]
"https://github.com/viperproject/viper.git#viper:0.1.0" = { "path" = "viper"}
"https://github.com/viperproject/viper-sys.git#viper-sys:0.1.0" = { "path" = "viper-sys"}
"https://github.com/viperproject/prusti_contracts.git#prusti_contracts:0.1.0" = { "path" = "prusti_contracts"}
"https://github.com/viperproject/prusti-interface.git#prusti-interface:0.1.0" = { "path" = "prusti-interface"}
"https://github.com/viperproject/prusti-viper.git#prusti-viper:0.1.0" = { "path" = "prusti-viper"}
"https://github.com/viperproject/jni-gen.git#jni-gen:0.1.0" = { "path" = "jni-gen"}
