[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Translation of MIR into Viper"
name = "prusti-viper"
readme = "README.md"
license = "MPL-2.0"
version = "0.1.0"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-interface = { path = "../prusti-interface" }
prusti-filter = { path = "../prusti-filter" }
uuid = { version = "0.7", features = ["v4"] }
num-rational = "0.2.1"
num-traits = "0.2.6"
pretty_assertions = "0.5.1"
regex = "1.0.5"
derive_more = "0.12.0"

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.5.13"
prusti-interface = { path = "../prusti-interface" }
