[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Translation of MIR into Viper"
name = "prusti-viper"
readme = "README.md"
license = "MPL-2.0"
version = "0.1.0"

[dependencies]
log = "0.4"
viper = { path = "../viper" }
prusti-interface = { path = "../prusti-interface" }
prusti-filter = { path = "../prusti-filter" }
uuid = { version = "0.6.5", features = ["v4"] }

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.5.13"
prusti-interface = { path = "../prusti-interface" }
