[package]
name = "prusti-interface"
version = "0.1.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Interface between prusti and prusti-viper"
license = "MPL-2.0"
readme = "README.md"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
lazy_static = "1.0"
polonius = "0.2.0"
polonius-engine = "0.5.0"
csv = "1"
serde = "1.0"
serde_derive = "1.0"
regex = "1.0.5"
rustc-hash = "1.0.0"
prusti-common = { path = "../prusti-common" }

[dev-dependencies]
env_logger = "0.5.13"
