[package]
name = "jni-gen-systest"
version = "0.1.0"
build = "build.rs"

[dependencies]
error-chain = "0.11.0"
jni = { path = "../../../jni-rs", features = ["backtrace", "invocation"] }

[build-dependencies]
jni-gen = { path = "../" }
error-chain = "0.11.0"
env_logger = "0.4.3"
