[package]
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]
description = "Server-side logic & handling for Prusti"
name = "prusti-server"
license = "MPL-2.0"
version = "0.1.0"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-viper = { path = "../prusti-viper" }
prusti-common = { path = "../prusti-common" }
tarpc = "= 0.12.1"
tarpc-plugins = "= 0.4.0"
crc = "= 1.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "= 1.0.32" # TODO: caret version once compiler updated
futures = "0.1.24"
