[package]
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]
description = "Server-side logic & handling for Prusti"
name = "prusti-server"
license = "MPL-2.0"
version = "0.1.0"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-viper = { path = "../prusti-viper" }
