[package]
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]
description = "Server-side logic & handling for Prusti"
name = "prusti-server"
license = "MPL-2.0"
version = "0.1.0"

[lib]
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "prusti-server"
path = "src/prusti_server.rs"
test = false
doctest = false

[[bin]]
name = "prusti-server-driver"
path = "src/driver.rs"
test = false
doctest = false

# TODO: caret versions to replace "= x.y.z" requirements and updates once compiler updated
[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-launch = { path = "../prusti-launch" }
env_logger = "0.5.13"
clap = "2.32.0"
prusti-common = { path = "../prusti-common" }
serde = "1.0" # need this for the tarpc macro
futures = "0.1.24"
lru = "= 0.1.16"
reqwest = "0.9"
warp = "= 0.1.11"
tokio = "= 0.1.11"
# indirect dependencies we have to enforce earlier versions of because of our old compiler version (technically, these are enforced via Cargo.lock, but that feels fragile to me)
urlencoding = "= 1.0"
utf-8 = "= 0.7.4"
percent-encoding = "= 1.0.1"

[dev-dependencies]
lazy_static = "1.0"
