[package]
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]
description = "Server-side logic & handling for Prusti"
name = "prusti-server"
license = "MPL-2.0"
version = "0.1.0"

[lib]
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "prusti-server"
path = "src/prusti_server.rs"
test = false
doctest = false

[[bin]]
name = "prusti-server-driver"
path = "src/driver.rs"
test = false
doctest = false

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
utils = { path = "../utils" }
env_logger = "0.5.13"
clap = "2.32.0"
prusti-common = { path = "../prusti-common" }
tarpc = "= 0.12.1"
tarpc-plugins = "= 0.4.0"
crc = "= 1.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "= 1.0.32" # TODO: caret version once compiler updated
futures = "0.1.24"
lru = "= 0.1.16" # TODO: caret version once compiler updated
