[package]
name = "prusti-contracts"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[dependencies]
prusti-contracts-impl = { path = "../prusti-contracts-impl" }
proc-macro-hack = "0.5.15"

[dev-dependencies]
trybuild = "1.0"