[package]
name = "prusti-tests"
version = "0.1.0"
authors = []
license = "MPL-2.0"
readme = "README.md"

[dev-dependencies]
compiletest_rs = { git = "https://github.com/fpoli/compiletest-rs.git", branch="with-exit-code-101" }
