[package]
name = "systest"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
jni-gen = { path = ".." }
error-chain = "0.11.0"
env_logger = "0.4.3"
reqwest = "0.8.2"
tempdir = "0.3.5"

[dependencies]
error-chain = "0.11.0"
jni = { version = "0.9.3", features = ["backtrace", "invocation"] }
