[package]
name = "prusti-filter"
version = "0.1.0"
authors = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "prusti-filter"
test = false
path = "src/driver.rs"

[dependencies]
log = "0.4"
env_logger = "0.5.13"
