[package]
name = "prusti-filter"
version = "0.1.0"
license = "MPL-2.0"
authors = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "prusti-filter"
test = false
path = "src/driver.rs"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
env_logger = "0.5.13"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
prusti-interface = { path = "../prusti-interface" }
