[package]
name = "prusti-filter"
version = "0.1.0"
license = "MPL-2.0"
authors = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "prusti-filter-driver"
test = false
path = "src/driver.rs"

[[bin]]
name = "prusti-filter"
test = false
path = "src/prusti_filter.rs"

[[bin]]
name = "cargo-prusti-filter"
test = false
path = "src/cargo_prusti_filter.rs"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
env_logger = "0.5.13"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
prusti-interface = { path = "../prusti-interface" }
walkdir = "2"

[dev-dependencies]
compiletest_rs = { git = "https://github.com/fpoli/compiletest-rs.git", branch="with-exit-code-101" }
