[package]
name = "prusti"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"

[lib]
name = "prusti"

[[bin]]
name = "prusti-driver"
test = false
path = "src/driver.rs"

[[bin]]
name = "prusti-rustc"
test = false
path = "src/prusti_rustc.rs"

[[bin]]
name = "cargo-prusti"
test = false
path = "src/cargo_prusti.rs"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
env_logger = "0.5.13"
regex = "1.0.5"
prusti-contracts = { path = "../prusti-contracts" }
prusti-interface = { path = "../prusti-interface" }
prusti-viper = { path = "../prusti-viper" }
walkdir = "2"

[build-dependencies]
chrono = "0.4"

[dev-dependencies]
compiletest_rs = { git = "https://github.com/fpoli/compiletest-rs.git", branch="with-exit-code-101" }
