[package]
name = "prusti"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"

[lib]
name = "prusti"
plugin = true

[[bin]]
name = "cargo-prusti"
test = false
path = "src/main.rs"

[[bin]]
name = "prusti-driver"
test = false
path = "src/driver.rs"

[dependencies]
log = "0.3"
env_logger = "0.3"
regex = "0.2"
prusti-contracts = { path = "../prusti-contracts" }
prusti-interface = { path = "../prusti-interface" }
prusti-utils = { path = "../prusti-utils" }
prusti-viper = { path = "../prusti-viper" }

[dev-dependencies]
compiletest_rs = { git = "https://github.com/fpoli/compiletest-rs.git", branch="with-exit-code-101" }
