name: Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  RUST_BACKTRACE: 1
  PRUSTI_ASSERT_TIMEOUT: 60000

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
      fail-fast: false # don't cancel when one matrix job fails, so we can compare to the others
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up the environment
      run: ./x.py setup
    - name: Build with cargo
      run: ./x.py build --all --verbose
    - name: Run cargo tests
      run: ./x.py test --all --verbose
    - name: Check formatting
      run: echo "temporarily skipped" # ./x.py fmt -- --check
    - name: Check prusti-contracts
      run: |
        cd prusti-contracts-test/
        cargo build
    - name: Check prusti-rustc binary
      run: |
        ./target/debug/prusti-rustc prusti-tests/tests/verify/pass/no-annotations/assert-true.rs
        ! ./target/debug/prusti-rustc prusti-tests/tests/verify/fail/no-annotations/assert-false.rs
      env:
        VIPER_HOME: viper_tools/backends/
        Z3_EXE: viper_tools/z3/bin/z3
