name: Test on top crates

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  RUST_BACKTRACE: 1
  PRUSTI_ASSERT_TIMEOUT: 60000
  CRATES_DIR: "../top-crates"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Prepare environment
      run: .github/workflows/prepare-environment.sh
    - name: Compile Prusti in release mode
      run: cargo build --all --release
    - name: Download top crates
      run: |
        mkdir -p "$CRATES_DIR"
        ./evaluation/script/download-top-20.sh "$CRATES_DIR"
        ./evaluation/script/set-cargo-lock.sh "$CRATES_DIR"
    - name: Compile crates with standard rustc
      run: ./evaluation/script/compile-crates.sh "$CRATES_DIR"
    - name: Run Prusti on the top crates
      run: ./evaluation/script/core-evaluation.sh "$CRATES_DIR"
    - name: Check outcome
      run: |
        if grep "^[^,]*,false," "$CRATES_DIR"/coarse-grained-verification-report.csv; then
            echo "Prusti failed on some crates"
            exit 2
        fi
