CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::b64[0]::x86_64[0]::{{impl}}[19]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::b64[0]::x86_64[0]::{{impl}}[27]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::b64[0]::x86_64[0]::{{impl}}[29]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::b64[0]::{{impl}}[5]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[21]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[25]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[29]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[31]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[33]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[35]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[37]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[39]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[3]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[41]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::other[0]::{{impl}}[5]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[25]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[29]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[41]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[45]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[47]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[49]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[51]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[55]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[57]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[59]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[5]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[61]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[63]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[65]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[67]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[71]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[77]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[79]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[81]::clone[0]",
"libc::unix[0]::notbsd[0]::linux[0]::{{impl}}[89]::clone[0]",
"libc::unix[0]::notbsd[0]::{{impl}}[13]::clone[0]",
"libc::unix[0]::notbsd[0]::{{impl}}[21]::clone[0]",
"libc::unix[0]::notbsd[0]::{{impl}}[25]::clone[0]",
"libc::unix[0]::notbsd[0]::{{impl}}[33]::clone[0]",
"libc::unix[0]::notbsd[0]::{{impl}}[43]::clone[0]",
"libc::unix[0]::{{impl}}[11]::clone[0]",
"libc::unix[0]::{{impl}}[13]::clone[0]",
"libc::unix[0]::{{impl}}[17]::clone[0]",
"libc::unix[0]::{{impl}}[25]::clone[0]",
"libc::unix[0]::{{impl}}[27]::clone[0]",
"libc::unix[0]::{{impl}}[29]::clone[0]",
"libc::unix[0]::{{impl}}[33]::clone[0]",
"libc::unix[0]::{{impl}}[35]::clone[0]",
"libc::unix[0]::{{impl}}[3]::clone[0]",
"libc::unix[0]::{{impl}}[5]::clone[0]",
"libc::unix[0]::{{impl}}[7]::clone[0]",
"libc::unix[0]::{{impl}}[9]::clone[0]"
]
