CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"log::eq_ignore_ascii_case[0]::to_ascii_uppercase[0]",
"log::ok_or[0]",
"log::{{impl}}[0]::clone[0]",
"log::{{impl}}[11]::eq[0]",
"log::{{impl}}[12]::partial_cmp[0]",
"log::{{impl}}[17]::from_usize[0]",
"log::{{impl}}[17]::max[0]",
"log::{{impl}}[22]::flush[0]",
"log::{{impl}}[27]::assert_receiver_is_total_eq[0]",
"log::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"log::{{impl}}[3]::partial_cmp[0]",
"log::{{impl}}[50]::eq[0]",
"log::{{impl}}[50]::ne[0]",
"log::{{impl}}[8]::from_usize[0]",
"log::{{impl}}[8]::max[0]",
"log::{{impl}}[9]::clone[0]"
]
