CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"memchr::x86[0]::avx[0]::forward_pos2[0]",
"memchr::x86[0]::avx[0]::forward_pos3[0]",
"memchr::x86[0]::avx[0]::reverse_pos2[0]",
"memchr::x86[0]::avx[0]::reverse_pos3[0]",
"memchr::x86[0]::sse2[0]::forward_pos2[0]",
"memchr::x86[0]::sse2[0]::forward_pos3[0]",
"memchr::x86[0]::sse2[0]::reverse_pos2[0]",
"memchr::x86[0]::sse2[0]::reverse_pos3[0]"
]
