CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rustc_serialize::base64[0]::{{impl}}[10]::clone[0]",
"rustc_serialize::base64[0]::{{impl}}[13]::clone[0]",
"rustc_serialize::base64[0]::{{impl}}[16]::clone[0]",
"rustc_serialize::base64[0]::{{impl}}[18]::clone[0]",
"rustc_serialize::hex[0]::{{impl}}[8]::clone[0]",
"rustc_serialize::json[0]::{{impl}}[12]::from[0]",
"rustc_serialize::json[0]::{{impl}}[1]::eq[0]",
"rustc_serialize::json[0]::{{impl}}[2]::clone[0]",
"rustc_serialize::json[0]::{{impl}}[51]::clone[0]"
]
