CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicode_xid::{{impl}}[0]::is_xid_continue[0]",
"unicode_xid::{{impl}}[0]::is_xid_start[0]"
]
