CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"aho_corasick_dot::lib[0]::autiter[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"aho_corasick_dot::lib[0]::autiter[0]::{{impl}}[6]::eq[0]",
"aho_corasick_dot::lib[0]::autiter[0]::{{impl}}[6]::ne[0]",
"aho_corasick_dot::lib[0]::autiter[0]::{{impl}}[7]::hash[0]",
"aho_corasick_dot::lib[0]::autiter[0]::{{impl}}[9]::clone[0]",
"aho_corasick_dot::lib[0]::vec_bytes[0]",
"aho_corasick_dot::lib[0]::{{impl}}[4]::new[0]"
]
