CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"quote::__rt[0]::is_ident_continue[0]",
"quote::__rt[0]::is_ident_start[0]"
]
