CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"thread_local::thread_id[0]::THREAD_ID[0]::__init[0]",
"thread_local::{{impl}}[3]::clone[0]"
]
