CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"time::at[0]",
"time::at_utc[0]",
"time::display[0]::abs[0]",
"time::display[0]::days_in_year[0]",
"time::display[0]::is_leap_year[0]",
"time::display[0]::iso_week_days[0]",
"time::duration[0]::div_floor_64[0]",
"time::duration[0]::div_mod_floor_64[0]",
"time::duration[0]::div_rem_64[0]",
"time::duration[0]::mod_floor_64[0]",
"time::duration[0]::{{impl}}[0]::is_zero[0]",
"time::duration[0]::{{impl}}[0]::num_nanoseconds[0]",
"time::duration[0]::{{impl}}[0]::num_seconds[0]",
"time::duration[0]::{{impl}}[0]::num_weeks[0]",
"time::duration[0]::{{impl}}[0]::zero[0]",
"time::duration[0]::{{impl}}[10]::cmp[0]",
"time::duration[0]::{{impl}}[11]::partial_cmp[0]",
"time::duration[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"time::duration[0]::{{impl}}[13]::eq[0]",
"time::duration[0]::{{impl}}[13]::ne[0]",
"time::duration[0]::{{impl}}[15]::clone[0]",
"time::duration[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"time::duration[0]::{{impl}}[17]::eq[0]",
"time::duration[0]::{{impl}}[17]::ne[0]",
"time::duration[0]::{{impl}}[19]::clone[0]",
"time::empty_tm[0]",
"time::get_time[0]",
"time::now[0]",
"time::now_utc[0]",
"time::precise_time_ns[0]",
"time::sys[0]::inner[0]::unix[0]::{{impl}}[1]::clone[0]",
"time::sys[0]::inner[0]::unix[0]::{{impl}}[4]::sub[0]",
"time::sys[0]::inner[0]::unix[0]::{{impl}}[6]::partial_cmp[0]",
"time::sys[0]::inner[0]::unix[0]::{{impl}}[7]::cmp[0]",
"time::sys[0]::inner[0]::unix[0]::{{impl}}[8]::eq[0]",
"time::{{impl}}[10]::add[0]",
"time::{{impl}}[11]::sub[0]",
"time::{{impl}}[12]::sub[0]",
"time::{{impl}}[13]::partial_cmp[0]",
"time::{{impl}}[14]::cmp[0]",
"time::{{impl}}[15]::to_local[0]",
"time::{{impl}}[15]::to_timespec[0]",
"time::{{impl}}[15]::to_utc[0]",
"time::{{impl}}[18]::hash[0]",
"time::{{impl}}[20]::cmp[0]",
"time::{{impl}}[21]::partial_cmp[0]",
"time::{{impl}}[22]::assert_receiver_is_total_eq[0]",
"time::{{impl}}[23]::eq[0]",
"time::{{impl}}[23]::ne[0]",
"time::{{impl}}[24]::clone[0]",
"time::{{impl}}[26]::clone[0]",
"time::{{impl}}[29]::assert_receiver_is_total_eq[0]",
"time::{{impl}}[30]::eq[0]",
"time::{{impl}}[30]::ne[0]",
"time::{{impl}}[31]::cmp[0]",
"time::{{impl}}[32]::partial_cmp[0]",
"time::{{impl}}[34]::clone[0]",
"time::{{impl}}[35]::hash[0]",
"time::{{impl}}[37]::assert_receiver_is_total_eq[0]",
"time::{{impl}}[38]::eq[0]",
"time::{{impl}}[38]::ne[0]",
"time::{{impl}}[39]::clone[0]",
"time::{{impl}}[3]::sub[0]",
"time::{{impl}}[41]::clone[0]",
"time::{{impl}}[4]::now[0]",
"time::{{impl}}[5]::now[0]",
"time::{{impl}}[7]::sub[0]",
"time::{{impl}}[8]::sub[0]",
"time::{{impl}}[9]::add[0]"
]
