CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"utf8_ranges::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"utf8_ranges::{{impl}}[14]::eq[0]",
"utf8_ranges::{{impl}}[14]::ne[0]",
"utf8_ranges::{{impl}}[16]::clone[0]",
"utf8_ranges::{{impl}}[3]::matches[0]",
"utf8_ranges::{{impl}}[3]::new[0]",
"utf8_ranges::{{impl}}[8]::is_ascii[0]",
"utf8_ranges::{{impl}}[8]::is_valid[0]",
"utf8_ranges::{{impl}}[8]::split[0]"
]
