CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"byteorder::{{impl}}[0]::default[0]",
"byteorder::{{impl}}[11]::clone[0]",
"byteorder::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"byteorder::{{impl}}[19]::clone[0]",
"byteorder::{{impl}}[1]::default[0]",
"byteorder::{{impl}}[8]::assert_receiver_is_total_eq[0]"
]
