CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"url::encoding[0]::{{impl}}[0]::utf8[0]",
"url::encoding[0]::{{impl}}[2]::clone[0]",
"url::form_urlencoded[0]::byte_serialized_unchanged[0]",
"url::origin[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"url::origin[0]::{{impl}}[7]::clone[0]",
"url::origin[0]::{{impl}}[8]::hash[0]",
"url::origin[0]::{{impl}}[9]::eq[0]",
"url::origin[0]::{{impl}}[9]::ne[0]",
"url::parser[0]::ascii_alpha[0]",
"url::parser[0]::c0_control_or_space[0]",
"url::parser[0]::is_ascii_hex_digit[0]",
"url::parser[0]::is_url_code_point[0]",
"url::parser[0]::{{impl}}[15]::clone[0]",
"url::parser[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"url::parser[0]::{{impl}}[21]::clone[0]",
"url::parser[0]::{{impl}}[22]::assert_receiver_is_total_eq[0]",
"url::parser[0]::{{impl}}[24]::clone[0]",
"url::parser[0]::{{impl}}[29]::clone[0]",
"url::parser[0]::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"url::parser[0]::{{impl}}[3]::is_file[0]",
"url::parser[0]::{{impl}}[3]::is_special[0]",
"url::slicing[0]::{{impl}}[6]::clone[0]"
]
