CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"semver::version_req[0]::{{impl}}[1]::from[0]",
"semver::version_req[0]::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"semver::version_req[0]::{{impl}}[30]::assert_receiver_is_total_eq[0]"
]
