CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"num_integer::Integer[0]::div_mod_floor[0]",
"num_integer::div_floor[0]",
"num_integer::div_mod_floor[0]",
"num_integer::div_rem[0]",
"num_integer::gcd[0]",
"num_integer::lcm[0]",
"num_integer::mod_floor[0]",
"num_integer::multiply_and_divide[0]",
"num_integer::roots[0]::Roots[0]::cbrt[0]",
"num_integer::roots[0]::Roots[0]::sqrt[0]",
"num_integer::roots[0]::cbrt[0]",
"num_integer::roots[0]::nth_root[0]",
"num_integer::roots[0]::sqrt[0]",
"num_integer::{{impl}}[0]::new[0]",
"num_integer::{{impl}}[10]::div_floor[0]",
"num_integer::{{impl}}[10]::div_rem[0]",
"num_integer::{{impl}}[10]::divides[0]",
"num_integer::{{impl}}[10]::is_even[0]",
"num_integer::{{impl}}[10]::is_multiple_of[0]",
"num_integer::{{impl}}[10]::is_odd[0]",
"num_integer::{{impl}}[10]::lcm[0]",
"num_integer::{{impl}}[10]::mod_floor[0]",
"num_integer::{{impl}}[11]::div_floor[0]",
"num_integer::{{impl}}[11]::div_rem[0]",
"num_integer::{{impl}}[11]::divides[0]",
"num_integer::{{impl}}[11]::is_even[0]",
"num_integer::{{impl}}[11]::is_multiple_of[0]",
"num_integer::{{impl}}[11]::is_odd[0]",
"num_integer::{{impl}}[11]::lcm[0]",
"num_integer::{{impl}}[11]::mod_floor[0]",
"num_integer::{{impl}}[12]::div_floor[0]",
"num_integer::{{impl}}[12]::div_rem[0]",
"num_integer::{{impl}}[12]::divides[0]",
"num_integer::{{impl}}[12]::is_even[0]",
"num_integer::{{impl}}[12]::is_multiple_of[0]",
"num_integer::{{impl}}[12]::is_odd[0]",
"num_integer::{{impl}}[12]::lcm[0]",
"num_integer::{{impl}}[12]::mod_floor[0]",
"num_integer::{{impl}}[13]::div_floor[0]",
"num_integer::{{impl}}[13]::div_rem[0]",
"num_integer::{{impl}}[13]::divides[0]",
"num_integer::{{impl}}[13]::is_even[0]",
"num_integer::{{impl}}[13]::is_multiple_of[0]",
"num_integer::{{impl}}[13]::is_odd[0]",
"num_integer::{{impl}}[13]::lcm[0]",
"num_integer::{{impl}}[13]::mod_floor[0]",
"num_integer::{{impl}}[1]::next[0]",
"num_integer::{{impl}}[2]::div_floor[0]",
"num_integer::{{impl}}[2]::div_mod_floor[0]",
"num_integer::{{impl}}[2]::div_rem[0]",
"num_integer::{{impl}}[2]::divides[0]",
"num_integer::{{impl}}[2]::is_multiple_of[0]",
"num_integer::{{impl}}[2]::is_odd[0]",
"num_integer::{{impl}}[2]::lcm[0]",
"num_integer::{{impl}}[2]::mod_floor[0]",
"num_integer::{{impl}}[3]::div_floor[0]",
"num_integer::{{impl}}[3]::div_mod_floor[0]",
"num_integer::{{impl}}[3]::div_rem[0]",
"num_integer::{{impl}}[3]::divides[0]",
"num_integer::{{impl}}[3]::is_multiple_of[0]",
"num_integer::{{impl}}[3]::is_odd[0]",
"num_integer::{{impl}}[3]::lcm[0]",
"num_integer::{{impl}}[3]::mod_floor[0]",
"num_integer::{{impl}}[4]::div_floor[0]",
"num_integer::{{impl}}[4]::div_mod_floor[0]",
"num_integer::{{impl}}[4]::div_rem[0]",
"num_integer::{{impl}}[4]::divides[0]",
"num_integer::{{impl}}[4]::is_multiple_of[0]",
"num_integer::{{impl}}[4]::is_odd[0]",
"num_integer::{{impl}}[4]::lcm[0]",
"num_integer::{{impl}}[4]::mod_floor[0]",
"num_integer::{{impl}}[5]::div_floor[0]",
"num_integer::{{impl}}[5]::div_mod_floor[0]",
"num_integer::{{impl}}[5]::div_rem[0]",
"num_integer::{{impl}}[5]::divides[0]",
"num_integer::{{impl}}[5]::is_multiple_of[0]",
"num_integer::{{impl}}[5]::is_odd[0]",
"num_integer::{{impl}}[5]::lcm[0]",
"num_integer::{{impl}}[5]::mod_floor[0]",
"num_integer::{{impl}}[6]::div_floor[0]",
"num_integer::{{impl}}[6]::div_mod_floor[0]",
"num_integer::{{impl}}[6]::div_rem[0]",
"num_integer::{{impl}}[6]::divides[0]",
"num_integer::{{impl}}[6]::is_multiple_of[0]",
"num_integer::{{impl}}[6]::is_odd[0]",
"num_integer::{{impl}}[6]::lcm[0]",
"num_integer::{{impl}}[6]::mod_floor[0]",
"num_integer::{{impl}}[7]::div_floor[0]",
"num_integer::{{impl}}[7]::div_mod_floor[0]",
"num_integer::{{impl}}[7]::div_rem[0]",
"num_integer::{{impl}}[7]::divides[0]",
"num_integer::{{impl}}[7]::is_multiple_of[0]",
"num_integer::{{impl}}[7]::is_odd[0]",
"num_integer::{{impl}}[7]::lcm[0]",
"num_integer::{{impl}}[7]::mod_floor[0]",
"num_integer::{{impl}}[8]::div_floor[0]",
"num_integer::{{impl}}[8]::div_rem[0]",
"num_integer::{{impl}}[8]::divides[0]",
"num_integer::{{impl}}[8]::is_even[0]",
"num_integer::{{impl}}[8]::is_multiple_of[0]",
"num_integer::{{impl}}[8]::is_odd[0]",
"num_integer::{{impl}}[8]::lcm[0]",
"num_integer::{{impl}}[8]::mod_floor[0]",
"num_integer::{{impl}}[9]::div_floor[0]",
"num_integer::{{impl}}[9]::div_rem[0]",
"num_integer::{{impl}}[9]::divides[0]",
"num_integer::{{impl}}[9]::is_even[0]",
"num_integer::{{impl}}[9]::is_multiple_of[0]",
"num_integer::{{impl}}[9]::is_odd[0]",
"num_integer::{{impl}}[9]::lcm[0]",
"num_integer::{{impl}}[9]::mod_floor[0]"
]
