CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicode_normalization::quick_check[0]::{{impl}}[1]::assert_receiver_is_total_eq[0]",
"unicode_normalization::stream_safe[0]::{{impl}}[0]::new[0]",
"unicode_normalization::tables[0]::canonical_combining_class[0]",
"unicode_normalization::tables[0]::qc_nfc[0]",
"unicode_normalization::tables[0]::stream_safe_leading_nonstarters[0]",
"unicode_normalization::tables[0]::stream_safe_trailing_nonstarters[0]",
"unicode_normalization::{{impl}}[1]::stream_safe[0]"
]
