CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"void::unreachable[0]",
"void::{{impl}}[0]::clone[0]",
"void::{{impl}}[6]::void_unwrap[0]",
"void::{{impl}}[7]::void_unwrap_err[0]"
]
