CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicode_bidi::char_data[0]::is_rtl[0]",
"unicode_bidi::char_data[0]::tables[0]::{{impl}}[0]::assert_receiver_is_total_eq[0]",
"unicode_bidi::char_data[0]::tables[0]::{{impl}}[4]::clone[0]",
"unicode_bidi::implicit[0]::is_NI[0]",
"unicode_bidi::implicit[0]::resolve_weak[0]::id[0]",
"unicode_bidi::level[0]::{{impl}}[0]::bidi_class[0]",
"unicode_bidi::level[0]::{{impl}}[0]::is_ltr[0]",
"unicode_bidi::level[0]::{{impl}}[0]::is_rtl[0]",
"unicode_bidi::level[0]::{{impl}}[0]::lower[0]",
"unicode_bidi::level[0]::{{impl}}[0]::number[0]",
"unicode_bidi::level[0]::{{impl}}[10]::clone[0]",
"unicode_bidi::level[0]::{{impl}}[1]::into[0]",
"unicode_bidi::level[0]::{{impl}}[5]::partial_cmp[0]",
"unicode_bidi::level[0]::{{impl}}[6]::eq[0]",
"unicode_bidi::level[0]::{{impl}}[6]::ne[0]",
"unicode_bidi::level[0]::{{impl}}[7]::cmp[0]",
"unicode_bidi::level[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"unicode_bidi::prepare[0]::not_removed_by_x9[0]",
"unicode_bidi::prepare[0]::removed_by_x9[0]",
"unicode_bidi::{{impl}}[2]::eq[0]",
"unicode_bidi::{{impl}}[2]::ne[0]"
]
