CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"dtoa::diyfp[0]::{{impl}}[0]::new[0]",
"dtoa::diyfp[0]::{{impl}}[4]::clone[0]",
"dtoa::{{impl}}[0]::write[0]::count_decimal_digit32[0]",
"dtoa::{{impl}}[0]::write[0]::{{impl}}[1]::sub[0]",
"dtoa::{{impl}}[1]::write[0]::count_decimal_digit32[0]",
"dtoa::{{impl}}[1]::write[0]::{{impl}}[1]::sub[0]"
]
