CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"idna::uts46[0]::{{impl}}[2]::clone[0]",
"idna::uts46[0]::{{impl}}[6]::clone[0]",
"idna::uts46[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]"
]
