CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"clap::app[0]::help[0]::term_size[0]::dimensions[0]",
"clap::app[0]::settings[0]::{{impl}}[0]::bitor[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::ALLOW_MISSING_POS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::ALLOW_NEG_NUMS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::ALLOW_UNK_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::ARGS_NEGATE_SCS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::ARGS_OVERRIDE_SELF[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::A_REQUIRED_ELSE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::COLORED_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::COLOR_ALWAYS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::COLOR_AUTO[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::COLOR_NEVER[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::CONTAINS_LAST[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::DERIVE_DISP_ORDER[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::DISABLE_HELP_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::DISABLE_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::DONT_COLLAPSE_ARGS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::DONT_DELIM_TRAIL[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::GLOBAL_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::HIDDEN[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::INFER_SUBCOMMANDS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::LEADING_HYPHEN[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::LOW_INDEX_MUL_POS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NEEDS_LONG_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NEEDS_LONG_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NEEDS_SC_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NEXT_LINE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NO_BIN_NAME[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::NO_POS_VALUES[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::PROPAGATED[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::PROPAGATE_VALS_DOWN[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::SC_NEGATE_REQS[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::SC_REQUIRED[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::SC_REQUIRED_ELSE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::TRAILING_VALUES[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::TRAILING_VARARG[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::UNIFIED_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::UTF8_NONE[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::UTF8_STRICT[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::VALID_ARG_FOUND[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::VALID_NEG_NUM_FOUND[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::VERSIONLESS_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[11]::fmt[0]::__BitFlags[0]::WAIT_ON_ERROR[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::ALLOW_MISSING_POS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::ALLOW_NEG_NUMS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::ALLOW_UNK_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::ARGS_NEGATE_SCS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::ARGS_OVERRIDE_SELF[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::A_REQUIRED_ELSE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::COLORED_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::COLOR_ALWAYS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::COLOR_AUTO[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::COLOR_NEVER[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::CONTAINS_LAST[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::DERIVE_DISP_ORDER[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::DISABLE_HELP_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::DISABLE_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::DONT_COLLAPSE_ARGS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::DONT_DELIM_TRAIL[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::GLOBAL_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::HIDDEN[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::INFER_SUBCOMMANDS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::LEADING_HYPHEN[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::LOW_INDEX_MUL_POS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NEEDS_LONG_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NEEDS_LONG_VERSION[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NEEDS_SC_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NEXT_LINE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NO_BIN_NAME[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::NO_POS_VALUES[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::PROPAGATED[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::PROPAGATE_VALS_DOWN[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::SC_NEGATE_REQS[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::SC_REQUIRED[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::SC_REQUIRED_ELSE_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::TRAILING_VALUES[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::TRAILING_VARARG[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::UNIFIED_HELP[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::UTF8_NONE[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::UTF8_STRICT[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::VALID_ARG_FOUND[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::VALID_NEG_NUM_FOUND[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::VERSIONLESS_SC[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::all[0]::__BitFlags[0]::WAIT_ON_ERROR[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::bits[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::contains[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::empty[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::from_bits_truncate[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::intersects[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::is_all[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::is_empty[0]",
"clap::app[0]::settings[0]::{{impl}}[16]::set[0]",
"clap::app[0]::settings[0]::{{impl}}[27]::from_iter[0]",
"clap::app[0]::settings[0]::{{impl}}[28]::eq[0]",
"clap::app[0]::settings[0]::{{impl}}[28]::ne[0]",
"clap::app[0]::settings[0]::{{impl}}[29]::clone[0]",
"clap::app[0]::settings[0]::{{impl}}[2]::new[0]",
"clap::app[0]::settings[0]::{{impl}}[2]::zeroed[0]",
"clap::app[0]::settings[0]::{{impl}}[32]::clone[0]",
"clap::app[0]::settings[0]::{{impl}}[4]::hash[0]",
"clap::app[0]::settings[0]::{{impl}}[5]::cmp[0]",
"clap::app[0]::settings[0]::{{impl}}[6]::partial_cmp[0]",
"clap::app[0]::settings[0]::{{impl}}[7]::clone[0]",
"clap::app[0]::settings[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"clap::app[0]::settings[0]::{{impl}}[9]::eq[0]",
"clap::app[0]::settings[0]::{{impl}}[9]::ne[0]",
"clap::args[0]::arg_matches[0]::{{impl}}[1]::indices_of[0]::to_usize[0]",
"clap::args[0]::settings[0]::{{impl}}[0]::new[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ALLOW_TAC_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::CASE_INSENSITIVE[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::DELIM_NOT_SET[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::EMPTY_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::GLOBAL[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDDEN[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDDEN_LONG_H[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDDEN_SHORT_H[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDE_DEFAULT_VAL[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDE_ENV_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::HIDE_POS_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::LAST[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MULTIPLE[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::NEXT_LINE_HELP[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::REQUIRED[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::REQUIRE_EQUALS[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::REQ_DELIM[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::R_UNLESS_ALL[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::TAKES_VAL[0]",
"clap::args[0]::settings[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::USE_DELIM[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ALLOW_TAC_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::CASE_INSENSITIVE[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::DELIM_NOT_SET[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::EMPTY_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::GLOBAL[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDDEN[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDDEN_LONG_H[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDDEN_SHORT_H[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDE_DEFAULT_VAL[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDE_ENV_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::HIDE_POS_VALS[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::LAST[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MULTIPLE[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::NEXT_LINE_HELP[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::REQUIRED[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::REQUIRE_EQUALS[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::REQ_DELIM[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::R_UNLESS_ALL[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::TAKES_VAL[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::all[0]::__BitFlags[0]::USE_DELIM[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::bits[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::contains[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::empty[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::from_bits_truncate[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::intersects[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::is_all[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::is_empty[0]",
"clap::args[0]::settings[0]::{{impl}}[15]::set[0]",
"clap::args[0]::settings[0]::{{impl}}[26]::from_iter[0]",
"clap::args[0]::settings[0]::{{impl}}[28]::clone[0]",
"clap::args[0]::settings[0]::{{impl}}[30]::clone[0]",
"clap::args[0]::settings[0]::{{impl}}[3]::hash[0]",
"clap::args[0]::settings[0]::{{impl}}[4]::cmp[0]",
"clap::args[0]::settings[0]::{{impl}}[5]::partial_cmp[0]",
"clap::args[0]::settings[0]::{{impl}}[6]::clone[0]",
"clap::args[0]::settings[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"clap::args[0]::settings[0]::{{impl}}[8]::eq[0]",
"clap::args[0]::settings[0]::{{impl}}[8]::ne[0]",
"clap::completions[0]::shell[0]::{{impl}}[3]::clone[0]",
"clap::errors[0]::{{impl}}[6]::clone[0]",
"clap::fmt[0]::is_a_tty[0]",
"clap::fmt[0]::{{impl}}[0]::error[0]",
"clap::fmt[0]::{{impl}}[0]::good[0]",
"clap::fmt[0]::{{impl}}[0]::new[0]",
"clap::fmt[0]::{{impl}}[0]::none[0]",
"clap::fmt[0]::{{impl}}[0]::warning[0]",
"clap::fmt[0]::{{impl}}[1]::default[0]",
"clap::fmt[0]::{{impl}}[5]::clone[0]",
"clap::usage_parser[0]::help_start[0]",
"clap::usage_parser[0]::long_end[0]",
"clap::usage_parser[0]::name_end[0]",
"clap::usage_parser[0]::token[0]"
]
