CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"num_iter::{{impl}}[0]::next[0]",
"num_iter::{{impl}}[1]::next_back[0]",
"num_iter::{{impl}}[2]::next[0]",
"num_iter::{{impl}}[2]::size_hint[0]",
"num_iter::{{impl}}[3]::next_back[0]",
"num_iter::{{impl}}[4]::next[0]",
"num_iter::{{impl}}[5]::next[0]",
"num_iter::{{impl}}[6]::clone[0]",
"num_iter::{{impl}}[7]::clone[0]",
"num_iter::{{impl}}[8]::clone[0]",
"num_iter::{{impl}}[9]::clone[0]"
]
