CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ansi_term::ansi[0]::{{impl}}[12]::clone[0]",
"ansi_term::ansi[0]::{{impl}}[15]::clone[0]",
"ansi_term::ansi[0]::{{impl}}[2]::infix[0]",
"ansi_term::ansi[0]::{{impl}}[2]::prefix[0]",
"ansi_term::ansi[0]::{{impl}}[2]::suffix[0]",
"ansi_term::ansi[0]::{{impl}}[3]::infix[0]",
"ansi_term::ansi[0]::{{impl}}[3]::prefix[0]",
"ansi_term::ansi[0]::{{impl}}[3]::suffix[0]",
"ansi_term::ansi[0]::{{impl}}[9]::clone[0]",
"ansi_term::difference[0]::{{impl}}[3]::clone[0]",
"ansi_term::style[0]::{{impl}}[0]::blink[0]",
"ansi_term::style[0]::{{impl}}[0]::bold[0]",
"ansi_term::style[0]::{{impl}}[0]::dimmed[0]",
"ansi_term::style[0]::{{impl}}[0]::fg[0]",
"ansi_term::style[0]::{{impl}}[0]::hidden[0]",
"ansi_term::style[0]::{{impl}}[0]::is_plain[0]",
"ansi_term::style[0]::{{impl}}[0]::italic[0]",
"ansi_term::style[0]::{{impl}}[0]::new[0]",
"ansi_term::style[0]::{{impl}}[0]::on[0]",
"ansi_term::style[0]::{{impl}}[0]::reverse[0]",
"ansi_term::style[0]::{{impl}}[0]::strikethrough[0]",
"ansi_term::style[0]::{{impl}}[0]::underline[0]",
"ansi_term::style[0]::{{impl}}[1]::default[0]",
"ansi_term::style[0]::{{impl}}[2]::blink[0]",
"ansi_term::style[0]::{{impl}}[2]::bold[0]",
"ansi_term::style[0]::{{impl}}[2]::dimmed[0]",
"ansi_term::style[0]::{{impl}}[2]::hidden[0]",
"ansi_term::style[0]::{{impl}}[2]::italic[0]",
"ansi_term::style[0]::{{impl}}[2]::normal[0]",
"ansi_term::style[0]::{{impl}}[2]::on[0]",
"ansi_term::style[0]::{{impl}}[2]::reverse[0]",
"ansi_term::style[0]::{{impl}}[2]::strikethrough[0]",
"ansi_term::style[0]::{{impl}}[2]::underline[0]",
"ansi_term::style[0]::{{impl}}[3]::from[0]",
"ansi_term::style[0]::{{impl}}[5]::clone[0]",
"ansi_term::style[0]::{{impl}}[6]::eq[0]",
"ansi_term::style[0]::{{impl}}[6]::ne[0]",
"ansi_term::style[0]::{{impl}}[9]::clone[0]"
]
