CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicase::ascii[0]::{{impl}}[0]::new[0]",
"unicase::ascii[0]::{{impl}}[1]::deref[0]",
"unicase::ascii[0]::{{impl}}[2]::deref_mut[0]",
"unicase::ascii[0]::{{impl}}[3]::partial_cmp[0]",
"unicase::unicode[0]::fold[0]::{{impl}}[0]::next[0]",
"unicase::unicode[0]::fold[0]::{{impl}}[0]::size_hint[0]",
"unicase::unicode[0]::fold[0]::{{impl}}[5]::clone[0]",
"unicase::unicode[0]::{{impl}}[2]::partial_cmp[0]",
"unicase::unicode[0]::{{impl}}[7]::clone[0]",
"unicase::{{impl}}[0]::unicode[0]",
"unicase::{{impl}}[13]::clone[0]",
"unicase::{{impl}}[16]::clone[0]",
"unicase::{{impl}}[8]::hash[0]",
"unicase::{{impl}}[9]::partial_cmp[0]"
]
