CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"mime::parse[0]::is_restricted_quoted_char[0]",
"mime::{{impl}}[36]::clone[0]"
]
