CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"chrono::Timelike[0]::hour12[0]",
"chrono::Timelike[0]::num_seconds_from_midnight[0]",
"chrono::datetime[0]::{{impl}}[24]::assert_receiver_is_total_eq[0]",
"chrono::datetime[0]::{{impl}}[27]::clone[0]",
"chrono::format[0]::parsed[0]::{{impl}}[0]::default[0]",
"chrono::format[0]::parsed[0]::{{impl}}[1]::new[0]",
"chrono::format[0]::parsed[0]::{{impl}}[1]::set_ampm[0]",
"chrono::format[0]::parsed[0]::{{impl}}[1]::set_timestamp[0]",
"chrono::format[0]::parsed[0]::{{impl}}[1]::set_weekday[0]",
"chrono::format[0]::parsed[0]::{{impl}}[3]::eq[0]",
"chrono::format[0]::parsed[0]::{{impl}}[3]::ne[0]",
"chrono::format[0]::parsed[0]::{{impl}}[4]::clone[0]",
"chrono::format[0]::{{impl}}[0]::clone[0]",
"chrono::format[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[15]::clone[0]",
"chrono::format[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[1]::eq[0]",
"chrono::format[0]::{{impl}}[22]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[25]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[26]::eq[0]",
"chrono::format[0]::{{impl}}[26]::ne[0]",
"chrono::format[0]::{{impl}}[27]::clone[0]",
"chrono::format[0]::{{impl}}[29]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[38]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[39]::eq[0]",
"chrono::format[0]::{{impl}}[39]::ne[0]",
"chrono::format[0]::{{impl}}[40]::clone[0]",
"chrono::format[0]::{{impl}}[43]::assert_receiver_is_total_eq[0]",
"chrono::format[0]::{{impl}}[45]::clone[0]",
"chrono::format[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::and_time[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::from_mdf[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::from_ymd_opt[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::from_yo_opt[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::mdf[0]",
"chrono::naive[0]::date[0]::{{impl}}[0]::with_mdf[0]",
"chrono::naive[0]::date[0]::{{impl}}[10]::clone[0]",
"chrono::naive[0]::date[0]::{{impl}}[12]::cmp[0]",
"chrono::naive[0]::date[0]::{{impl}}[13]::partial_cmp[0]",
"chrono::naive[0]::date[0]::{{impl}}[14]::hash[0]",
"chrono::naive[0]::date[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::date[0]::{{impl}}[16]::eq[0]",
"chrono::naive[0]::date[0]::{{impl}}[16]::ne[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::day0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::day[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::iso_week[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::month0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::month[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::ordinal0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::ordinal[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::weekday[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_day0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_day[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_month0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_month[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_ordinal0[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_ordinal[0]",
"chrono::naive[0]::date[0]::{{impl}}[1]::with_year[0]",
"chrono::naive[0]::date[0]::{{impl}}[3]::add_assign[0]",
"chrono::naive[0]::date[0]::{{impl}}[5]::sub_assign[0]",
"chrono::naive[0]::date[0]::{{impl}}[6]::sub[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::date[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::new[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::signed_duration_since[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::time[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::timestamp_millis[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::timestamp_nanos[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::timestamp_subsec_micros[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::timestamp_subsec_millis[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[0]::timestamp_subsec_nanos[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[12]::clone[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[14]::cmp[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[15]::partial_cmp[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[17]::eq[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[17]::ne[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::day0[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::day[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::iso_week[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::month0[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::month[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::ordinal0[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::ordinal[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::weekday[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[1]::year[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[2]::hour[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[2]::minute[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[2]::nanosecond[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[2]::second[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[3]::hash[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[5]::add_assign[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[7]::sub_assign[0]",
"chrono::naive[0]::datetime[0]::{{impl}}[8]::sub[0]",
"chrono::naive[0]::internals[0]::{{impl}}[0]::from_year[0]",
"chrono::naive[0]::internals[0]::{{impl}}[10]::clone[0]",
"chrono::naive[0]::internals[0]::{{impl}}[12]::partial_cmp[0]",
"chrono::naive[0]::internals[0]::{{impl}}[13]::eq[0]",
"chrono::naive[0]::internals[0]::{{impl}}[13]::ne[0]",
"chrono::naive[0]::internals[0]::{{impl}}[14]::clone[0]",
"chrono::naive[0]::internals[0]::{{impl}}[16]::partial_cmp[0]",
"chrono::naive[0]::internals[0]::{{impl}}[17]::eq[0]",
"chrono::naive[0]::internals[0]::{{impl}}[17]::ne[0]",
"chrono::naive[0]::internals[0]::{{impl}}[2]::clamp_ordinal[0]",
"chrono::naive[0]::internals[0]::{{impl}}[2]::to_mdf[0]",
"chrono::naive[0]::internals[0]::{{impl}}[4]::clamp_day[0]",
"chrono::naive[0]::internals[0]::{{impl}}[4]::clamp_month[0]",
"chrono::naive[0]::internals[0]::{{impl}}[4]::to_of[0]",
"chrono::naive[0]::internals[0]::{{impl}}[6]::clone[0]",
"chrono::naive[0]::internals[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::internals[0]::{{impl}}[9]::eq[0]",
"chrono::naive[0]::internals[0]::{{impl}}[9]::ne[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[2]::clone[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[4]::cmp[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[5]::partial_cmp[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[7]::eq[0]",
"chrono::naive[0]::isoweek[0]::{{impl}}[7]::ne[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::from_hms_nano_opt[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::from_hms_opt[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::from_num_seconds_from_midnight_opt[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::hms[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::overflowing_sub_signed[0]",
"chrono::naive[0]::time[0]::{{impl}}[0]::signed_duration_since[0]",
"chrono::naive[0]::time[0]::{{impl}}[11]::clone[0]",
"chrono::naive[0]::time[0]::{{impl}}[13]::cmp[0]",
"chrono::naive[0]::time[0]::{{impl}}[14]::partial_cmp[0]",
"chrono::naive[0]::time[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"chrono::naive[0]::time[0]::{{impl}}[16]::eq[0]",
"chrono::naive[0]::time[0]::{{impl}}[16]::ne[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::hour[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::minute[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::nanosecond[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::num_seconds_from_midnight[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::second[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::with_hour[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::with_minute[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::with_nanosecond[0]",
"chrono::naive[0]::time[0]::{{impl}}[1]::with_second[0]",
"chrono::naive[0]::time[0]::{{impl}}[2]::hash[0]",
"chrono::naive[0]::time[0]::{{impl}}[3]::add[0]",
"chrono::naive[0]::time[0]::{{impl}}[4]::add_assign[0]",
"chrono::naive[0]::time[0]::{{impl}}[5]::sub[0]",
"chrono::naive[0]::time[0]::{{impl}}[6]::sub_assign[0]",
"chrono::naive[0]::time[0]::{{impl}}[7]::sub[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[0]::east_opt[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[0]::local_minus_utc[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[0]::utc_minus_local[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[0]::west_opt[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[11]::clone[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[13]::hash[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[15]::eq[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[15]::ne[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[1]::from_offset[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[1]::offset_from_local_date[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[1]::offset_from_local_datetime[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[1]::offset_from_utc_date[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[1]::offset_from_utc_datetime[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[2]::fix[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[5]::add[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[6]::sub[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[7]::add[0]",
"chrono::offset[0]::fixed[0]::{{impl}}[8]::sub[0]",
"chrono::offset[0]::local[0]::{{impl}}[1]::from_offset[0]",
"chrono::offset[0]::local[0]::{{impl}}[3]::clone[0]",
"chrono::offset[0]::utc[0]::{{impl}}[1]::from_offset[0]",
"chrono::offset[0]::utc[0]::{{impl}}[1]::offset_from_local_date[0]",
"chrono::offset[0]::utc[0]::{{impl}}[1]::offset_from_local_datetime[0]",
"chrono::offset[0]::utc[0]::{{impl}}[1]::offset_from_utc_date[0]",
"chrono::offset[0]::utc[0]::{{impl}}[1]::offset_from_utc_datetime[0]",
"chrono::offset[0]::utc[0]::{{impl}}[2]::fix[0]",
"chrono::offset[0]::utc[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"chrono::offset[0]::utc[0]::{{impl}}[6]::eq[0]",
"chrono::offset[0]::utc[0]::{{impl}}[7]::clone[0]",
"chrono::offset[0]::{{impl}}[0]::earliest[0]",
"chrono::offset[0]::{{impl}}[0]::latest[0]",
"chrono::offset[0]::{{impl}}[0]::single[0]",
"chrono::round[0]::span_for_digits[0]",
"chrono::round[0]::{{impl}}[0]::round_subsecs[0]",
"chrono::round[0]::{{impl}}[0]::trunc_subsecs[0]",
"chrono::{{impl}}[0]::num_days_from_monday[0]",
"chrono::{{impl}}[0]::num_days_from_sunday[0]",
"chrono::{{impl}}[0]::number_from_monday[0]",
"chrono::{{impl}}[0]::number_from_sunday[0]",
"chrono::{{impl}}[0]::pred[0]",
"chrono::{{impl}}[0]::succ[0]",
"chrono::{{impl}}[10]::clone[0]",
"chrono::{{impl}}[1]::from_i64[0]",
"chrono::{{impl}}[1]::from_u64[0]",
"chrono::{{impl}}[5]::clone[0]",
"chrono::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"chrono::{{impl}}[9]::eq[0]",
"chrono::{{impl}}[9]::ne[0]"
]
