CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicode_width::{{impl}}[0]::width[0]",
"unicode_width::{{impl}}[0]::width_cjk[0]"
]
