CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"term::terminfo[0]::parm[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"term::terminfo[0]::parm[0]::{{impl}}[16]::default[0]",
"term::terminfo[0]::parm[0]::{{impl}}[17]::clone[0]",
"term::terminfo[0]::parm[0]::{{impl}}[18]::eq[0]",
"term::terminfo[0]::parm[0]::{{impl}}[18]::ne[0]",
"term::terminfo[0]::parm[0]::{{impl}}[20]::clone[0]",
"term::terminfo[0]::parm[0]::{{impl}}[4]::from_char[0]",
"term::terminfo[0]::parm[0]::{{impl}}[7]::clone[0]",
"term::terminfo[0]::parm[0]::{{impl}}[8]::clone[0]",
"term::terminfo[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"term::{{impl}}[7]::clone[0]",
"term::{{impl}}[9]::assert_receiver_is_total_eq[0]"
]
