CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"backtrace::lock[0]::LOCK_HELD[0]::__init[0]",
"backtrace::{{impl}}[0]::drop[0]"
]
