CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"httparse::is_token[0]",
"httparse::{{impl}}[10]::clone[0]",
"httparse::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"httparse::{{impl}}[13]::eq[0]",
"httparse::{{impl}}[4]::is_complete[0]",
"httparse::{{impl}}[4]::is_partial[0]",
"httparse::{{impl}}[4]::unwrap[0]",
"httparse::{{impl}}[8]::assert_receiver_is_total_eq[0]"
]
