CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rustc_version::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"rustc_version::{{impl}}[7]::clone[0]"
]
