CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"smallvec::{{impl}}[55]::size[0]",
"smallvec::{{impl}}[56]::size[0]",
"smallvec::{{impl}}[57]::size[0]",
"smallvec::{{impl}}[58]::size[0]",
"smallvec::{{impl}}[59]::size[0]",
"smallvec::{{impl}}[60]::size[0]",
"smallvec::{{impl}}[61]::size[0]",
"smallvec::{{impl}}[62]::size[0]",
"smallvec::{{impl}}[63]::size[0]",
"smallvec::{{impl}}[64]::size[0]",
"smallvec::{{impl}}[65]::size[0]",
"smallvec::{{impl}}[66]::size[0]",
"smallvec::{{impl}}[67]::size[0]",
"smallvec::{{impl}}[68]::size[0]",
"smallvec::{{impl}}[69]::size[0]",
"smallvec::{{impl}}[70]::size[0]",
"smallvec::{{impl}}[71]::size[0]",
"smallvec::{{impl}}[72]::size[0]",
"smallvec::{{impl}}[73]::size[0]",
"smallvec::{{impl}}[74]::size[0]",
"smallvec::{{impl}}[75]::size[0]",
"smallvec::{{impl}}[76]::size[0]",
"smallvec::{{impl}}[77]::size[0]",
"smallvec::{{impl}}[78]::size[0]",
"smallvec::{{impl}}[79]::size[0]",
"smallvec::{{impl}}[80]::size[0]",
"smallvec::{{impl}}[81]::size[0]",
"smallvec::{{impl}}[82]::size[0]",
"smallvec::{{impl}}[83]::size[0]",
"smallvec::{{impl}}[84]::size[0]",
"smallvec::{{impl}}[85]::size[0]",
"smallvec::{{impl}}[86]::size[0]",
"smallvec::{{impl}}[87]::size[0]",
"smallvec::{{impl}}[88]::size[0]",
"smallvec::{{impl}}[89]::size[0]",
"smallvec::{{impl}}[90]::size[0]"
]
