CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rustc_demangle::is_ascii_alphanumeric[0]",
"rustc_demangle::is_ascii_punctuation[0]",
"rustc_demangle::{{impl}}[3]::clone[0]"
]
