CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"proc_macro2::stable[0]::is_ident_continue[0]",
"proc_macro2::stable[0]::is_ident_start[0]",
"proc_macro2::stable[0]::{{impl}}[16]::call_site[0]",
"proc_macro2::stable[0]::{{impl}}[16]::def_site[0]",
"proc_macro2::stable[0]::{{impl}}[16]::located_at[0]",
"proc_macro2::stable[0]::{{impl}}[16]::resolved_at[0]",
"proc_macro2::stable[0]::{{impl}}[38]::assert_receiver_is_total_eq[0]",
"proc_macro2::stable[0]::{{impl}}[39]::eq[0]",
"proc_macro2::stable[0]::{{impl}}[39]::ne[0]",
"proc_macro2::stable[0]::{{impl}}[42]::clone[0]",
"proc_macro2::stable[0]::{{impl}}[43]::assert_receiver_is_total_eq[0]",
"proc_macro2::stable[0]::{{impl}}[44]::eq[0]",
"proc_macro2::stable[0]::{{impl}}[46]::clone[0]",
"proc_macro2::strnom[0]::is_whitespace[0]",
"proc_macro2::{{impl}}[45]::assert_receiver_is_total_eq[0]",
"proc_macro2::{{impl}}[47]::clone[0]",
"proc_macro2::{{impl}}[51]::assert_receiver_is_total_eq[0]",
"proc_macro2::{{impl}}[53]::clone[0]"
]
