CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"base64::decode[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"base64::line_wrap[0]::{{impl}}[0]::eq[0]",
"base64::line_wrap[0]::{{impl}}[0]::ne[0]",
"base64::{{impl}}[11]::clone[0]",
"base64::{{impl}}[14]::clone[0]",
"base64::{{impl}}[1]::len[0]",
"base64::{{impl}}[2]::new[0]",
"base64::{{impl}}[5]::clone[0]",
"base64::{{impl}}[8]::clone[0]"
]
