CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"uuid::{{impl}}[0]::expected[0]",
"uuid::{{impl}}[0]::found[0]",
"uuid::{{impl}}[0]::new[0]",
"uuid::{{impl}}[10]::clone[0]",
"uuid::{{impl}}[17]::clone[0]",
"uuid::{{impl}}[2]::partial_cmp[0]",
"uuid::{{impl}}[3]::eq[0]",
"uuid::{{impl}}[3]::ne[0]",
"uuid::{{impl}}[4]::cmp[0]",
"uuid::{{impl}}[5]::hash[0]",
"uuid::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"uuid::{{impl}}[9]::clone[0]"
]
