CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"net2::ext[0]::int2bool[0]",
"net2::ext[0]::ms2dur[0]",
"net2::ext[0]::to_ipv6mr_interface[0]",
"net2::ext[0]::v[0]",
"net2::ext[0]::{{impl}}[0]::as_sock[0]",
"net2::hton[0]",
"net2::ntoh[0]",
"net2::socket[0]::{{impl}}[2]::as_inner[0]",
"net2::socket[0]::{{impl}}[3]::from_inner[0]",
"net2::socket[0]::{{impl}}[4]::into_inner[0]",
"net2::sys[0]::c[0]::in_addr_to_u32[0]",
"net2::sys[0]::{{impl}}[0]::into_fd[0]",
"net2::sys[0]::{{impl}}[0]::raw[0]",
"net2::sys[0]::{{impl}}[1]::from_inner[0]",
"net2::tcp[0]::{{impl}}[2]::as_inner[0]",
"net2::tcp[0]::{{impl}}[3]::from_inner[0]",
"net2::udp[0]::{{impl}}[2]::as_inner[0]",
"net2::udp[0]::{{impl}}[3]::from_inner[0]",
"net2::utils[0]::{{impl}}[0]::from_be[0]",
"net2::utils[0]::{{impl}}[0]::to_be[0]",
"net2::utils[0]::{{impl}}[10]::one[0]",
"net2::utils[0]::{{impl}}[11]::one[0]",
"net2::utils[0]::{{impl}}[12]::one[0]",
"net2::utils[0]::{{impl}}[13]::one[0]",
"net2::utils[0]::{{impl}}[14]::one[0]",
"net2::utils[0]::{{impl}}[15]::one[0]",
"net2::utils[0]::{{impl}}[16]::one[0]",
"net2::utils[0]::{{impl}}[17]::one[0]",
"net2::utils[0]::{{impl}}[18]::one[0]",
"net2::utils[0]::{{impl}}[19]::one[0]",
"net2::utils[0]::{{impl}}[1]::from_be[0]",
"net2::utils[0]::{{impl}}[1]::to_be[0]",
"net2::utils[0]::{{impl}}[20]::zero[0]",
"net2::utils[0]::{{impl}}[21]::zero[0]",
"net2::utils[0]::{{impl}}[22]::zero[0]",
"net2::utils[0]::{{impl}}[23]::zero[0]",
"net2::utils[0]::{{impl}}[24]::zero[0]",
"net2::utils[0]::{{impl}}[25]::zero[0]",
"net2::utils[0]::{{impl}}[26]::zero[0]",
"net2::utils[0]::{{impl}}[27]::zero[0]",
"net2::utils[0]::{{impl}}[28]::zero[0]",
"net2::utils[0]::{{impl}}[29]::zero[0]",
"net2::utils[0]::{{impl}}[2]::from_be[0]",
"net2::utils[0]::{{impl}}[2]::to_be[0]",
"net2::utils[0]::{{impl}}[3]::from_be[0]",
"net2::utils[0]::{{impl}}[3]::to_be[0]",
"net2::utils[0]::{{impl}}[4]::from_be[0]",
"net2::utils[0]::{{impl}}[4]::to_be[0]",
"net2::utils[0]::{{impl}}[5]::from_be[0]",
"net2::utils[0]::{{impl}}[5]::to_be[0]",
"net2::utils[0]::{{impl}}[6]::from_be[0]",
"net2::utils[0]::{{impl}}[6]::to_be[0]",
"net2::utils[0]::{{impl}}[7]::from_be[0]",
"net2::utils[0]::{{impl}}[7]::to_be[0]",
"net2::utils[0]::{{impl}}[8]::from_be[0]",
"net2::utils[0]::{{impl}}[8]::to_be[0]",
"net2::utils[0]::{{impl}}[9]::from_be[0]",
"net2::utils[0]::{{impl}}[9]::to_be[0]"
]
