CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"language_tags::{{impl}}[5]::fmt[0]::cmp_ignore_ascii_case[0]",
"language_tags::{{impl}}[5]::fmt[0]::cmp_ignore_ascii_case[0]::byte_to_uppercase[0]",
"language_tags::{{impl}}[7]::assert_receiver_is_total_eq[0]"
]
