CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"percent_encoding::{{impl}}[0]::contains[0]",
"percent_encoding::{{impl}}[12]::clone[0]",
"percent_encoding::{{impl}}[16]::clone[0]",
"percent_encoding::{{impl}}[20]::clone[0]",
"percent_encoding::{{impl}}[24]::clone[0]",
"percent_encoding::{{impl}}[8]::clone[0]"
]
