CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"futures::future[0]::Future[0]::catch_unwind[0]",
"futures::future[0]::Future[0]::into_stream[0]",
"futures::future[0]::chain[0]::{{impl}}[0]::new[0]",
"futures::future[0]::either[0]::{{impl}}[0]::split[0]",
"futures::future[0]::empty[0]::empty[0]",
"futures::future[0]::empty[0]::{{impl}}[0]::poll[0]",
"futures::future[0]::fuse[0]::new[0]",
"futures::future[0]::fuse[0]::{{impl}}[0]::is_done[0]",
"futures::future[0]::into_stream[0]::new[0]",
"futures::future[0]::poll_fn[0]::{{impl}}[0]::poll[0]",
"futures::future[0]::result_[0]::err[0]",
"futures::future[0]::result_[0]::ok[0]",
"futures::future[0]::result_[0]::result[0]",
"futures::future[0]::result_[0]::{{impl}}[1]::from[0]",
"futures::future[0]::result_[0]::{{impl}}[2]::clone[0]",
"futures::future[0]::select2[0]::new[0]",
"futures::future[0]::{{impl}}[1]::into_future[0]",
"futures::future[0]::{{impl}}[2]::into_future[0]",
"futures::future[0]::{{impl}}[3]::into_future[0]",
"futures::future[0]::{{impl}}[3]::kind[0]",
"futures::future[0]::{{impl}}[3]::new[0]",
"futures::future[0]::{{impl}}[7]::clone[0]",
"futures::lock[0]::{{impl}}[2]::new[0]",
"futures::poll[0]::{{impl}}[0]::is_not_ready[0]",
"futures::poll[0]::{{impl}}[0]::is_ready[0]",
"futures::poll[0]::{{impl}}[0]::map[0]",
"futures::poll[0]::{{impl}}[1]::from[0]",
"futures::poll[0]::{{impl}}[2]::is_not_ready[0]",
"futures::poll[0]::{{impl}}[2]::is_ready[0]",
"futures::poll[0]::{{impl}}[2]::map[0]",
"futures::sink[0]::Sink[0]::flush[0]",
"futures::sink[0]::Sink[0]::sink_from_err[0]",
"futures::sink[0]::Sink[0]::sink_map_err[0]",
"futures::sink[0]::flush[0]::new[0]",
"futures::sink[0]::from_err[0]::{{impl}}[0]::get_mut[0]",
"futures::sink[0]::from_err[0]::{{impl}}[0]::get_ref[0]",
"futures::sink[0]::from_err[0]::{{impl}}[0]::into_inner[0]",
"futures::sink[0]::from_err[0]::{{impl}}[4]::clone[0]",
"futures::sink[0]::map_err[0]::new[0]",
"futures::sink[0]::map_err[0]::{{impl}}[0]::get_mut[0]",
"futures::sink[0]::map_err[0]::{{impl}}[0]::get_ref[0]",
"futures::sink[0]::map_err[0]::{{impl}}[0]::into_inner[0]",
"futures::sink[0]::map_err[0]::{{impl}}[4]::clone[0]",
"futures::sink[0]::with[0]::{{impl}}[0]::is_empty[0]",
"futures::stream[0]::Stream[0]::by_ref[0]",
"futures::stream[0]::Stream[0]::catch_unwind[0]",
"futures::stream[0]::Stream[0]::chain[0]",
"futures::stream[0]::Stream[0]::filter[0]",
"futures::stream[0]::Stream[0]::filter_map[0]",
"futures::stream[0]::Stream[0]::from_err[0]",
"futures::stream[0]::Stream[0]::fuse[0]",
"futures::stream[0]::Stream[0]::inspect[0]",
"futures::stream[0]::Stream[0]::inspect_err[0]",
"futures::stream[0]::Stream[0]::into_future[0]",
"futures::stream[0]::Stream[0]::map[0]",
"futures::stream[0]::Stream[0]::map_err[0]",
"futures::stream[0]::Stream[0]::select[0]",
"futures::stream[0]::Stream[0]::skip[0]",
"futures::stream[0]::Stream[0]::take[0]",
"futures::stream[0]::empty[0]::empty[0]",
"futures::stream[0]::empty[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::filter[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::filter[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::filter[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::filter_map[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::filter_map[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::filter_map[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::from_err[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::from_err[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::from_err[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::fuse[0]::new[0]",
"futures::stream[0]::fuse[0]::{{impl}}[2]::get_mut[0]",
"futures::stream[0]::fuse[0]::{{impl}}[2]::get_ref[0]",
"futures::stream[0]::fuse[0]::{{impl}}[2]::into_inner[0]",
"futures::stream[0]::fuse[0]::{{impl}}[2]::is_done[0]",
"futures::stream[0]::future[0]::new[0]",
"futures::stream[0]::future[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::futures_ordered[0]::{{impl}}[0]::eq[0]",
"futures::stream[0]::futures_ordered[0]::{{impl}}[2]::partial_cmp[0]",
"futures::stream[0]::futures_ordered[0]::{{impl}}[3]::cmp[0]",
"futures::stream[0]::futures_unordered[0]::abort[0]::{{impl}}[0]::drop[0]",
"futures::stream[0]::inspect[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::inspect[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::inspect[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::inspect_err[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::inspect_err[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::inspect_err[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::iter[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::iter_result[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::map[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::map[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::map[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::map_err[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::map_err[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::map_err[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::once[0]::once[0]",
"futures::stream[0]::once[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::poll_fn[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::repeat[0]::{{impl}}[0]::poll[0]",
"futures::stream[0]::skip[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::skip[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::skip[0]::{{impl}}[0]::into_inner[0]",
"futures::stream[0]::take[0]::{{impl}}[0]::get_mut[0]",
"futures::stream[0]::take[0]::{{impl}}[0]::get_ref[0]",
"futures::stream[0]::take[0]::{{impl}}[0]::into_inner[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[30]::is_closed[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[35]::assert_receiver_is_total_eq[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[36]::eq[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[36]::ne[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[37]::clone[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[38]::assert_receiver_is_total_eq[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[39]::eq[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[39]::ne[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[40]::clone[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[41]::assert_receiver_is_total_eq[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[46]::clone[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[4]::into_inner[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[8]::into_inner[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[8]::is_disconnected[0]",
"futures::sync[0]::mpsc[0]::{{impl}}[8]::is_full[0]",
"futures::sync[0]::oneshot[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"futures::sync[0]::oneshot[0]::{{impl}}[20]::eq[0]",
"futures::sync[0]::oneshot[0]::{{impl}}[22]::clone[0]",
"futures::task_impl[0]::Notify[0]::clone_id[0]",
"futures::task_impl[0]::Notify[0]::drop_id[0]",
"futures::task_impl[0]::core[0]::local_map[0]",
"futures::task_impl[0]::core[0]::{{impl}}[10]::clone[0]",
"futures::task_impl[0]::core[0]::{{impl}}[2]::notify[0]",
"futures::task_impl[0]::std[0]::data[0]::{{impl}}[1]::default[0]",
"futures::task_impl[0]::std[0]::data[0]::{{impl}}[2]::finish[0]",
"futures::task_impl[0]::std[0]::data[0]::{{impl}}[2]::write_u64[0]",
"futures::unsync[0]::mpsc[0]::{{impl}}[16]::into_inner[0]"
]
