CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"lazycell::{{impl}}[0]::new[0]",
"lazycell::{{impl}}[6]::default[0]",
"lazycell::{{impl}}[8]::default[0]"
]
