CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"flate2::_assert_send_sync[0]::_assert_send_sync[0]",
"flate2::crc[0]::{{impl}}[0]::amount[0]",
"flate2::crc[0]::{{impl}}[0]::new[0]",
"flate2::crc[0]::{{impl}}[0]::reset[0]",
"flate2::crc[0]::{{impl}}[1]::new[0]",
"flate2::crc[0]::{{impl}}[2]::crc[0]",
"flate2::crc[0]::{{impl}}[2]::get_mut[0]",
"flate2::crc[0]::{{impl}}[2]::get_ref[0]",
"flate2::crc[0]::{{impl}}[2]::into_inner[0]",
"flate2::crc[0]::{{impl}}[2]::reset[0]",
"flate2::crc[0]::{{impl}}[5]::crc[0]",
"flate2::crc[0]::{{impl}}[5]::get_mut[0]",
"flate2::crc[0]::{{impl}}[5]::get_ref[0]",
"flate2::crc[0]::{{impl}}[5]::into_inner[0]",
"flate2::crc[0]::{{impl}}[5]::reset[0]",
"flate2::crc[0]::{{impl}}[6]::new[0]",
"flate2::mem[0]::{{impl}}[20]::assert_receiver_is_total_eq[0]",
"flate2::mem[0]::{{impl}}[22]::clone[0]",
"flate2::mem[0]::{{impl}}[25]::assert_receiver_is_total_eq[0]",
"flate2::mem[0]::{{impl}}[27]::clone[0]",
"flate2::mem[0]::{{impl}}[29]::default[0]",
"flate2::mem[0]::{{impl}}[2]::needs_dictionary[0]",
"flate2::mem[0]::{{impl}}[34]::assert_receiver_is_total_eq[0]",
"flate2::mem[0]::{{impl}}[36]::clone[0]",
"flate2::zio[0]::{{impl}}[2]::finish[0]",
"flate2::zio[0]::{{impl}}[2]::none[0]",
"flate2::zio[0]::{{impl}}[2]::sync[0]",
"flate2::zio[0]::{{impl}}[3]::finish[0]",
"flate2::zio[0]::{{impl}}[3]::none[0]",
"flate2::zio[0]::{{impl}}[3]::sync[0]",
"flate2::{{impl}}[0]::best[0]",
"flate2::{{impl}}[0]::fast[0]",
"flate2::{{impl}}[0]::level[0]",
"flate2::{{impl}}[0]::new[0]",
"flate2::{{impl}}[0]::none[0]",
"flate2::{{impl}}[1]::default[0]",
"flate2::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"flate2::{{impl}}[4]::eq[0]",
"flate2::{{impl}}[4]::ne[0]",
"flate2::{{impl}}[5]::clone[0]"
]
