CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"mio::deprecated[0]::event_loop[0]::{{impl}}[0]::default[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[11]::clone[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::messages_per_tick[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::new[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::notify_capacity[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::timer_capacity[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::timer_tick[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[1]::timer_wheel_size[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[7]::clone[0]",
"mio::deprecated[0]::event_loop[0]::{{impl}}[8]::default[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[11]::from[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[16]::from[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[21]::from[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[22]::into_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[23]::as_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[25]::into_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[26]::as_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[28]::into_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[29]::as_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[2]::from[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[31]::into_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[32]::as_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[34]::into_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[35]::as_raw_fd[0]",
"mio::deprecated[0]::unix[0]::{{impl}}[7]::from[0]",
"mio::event_imp[0]::kind_mut[0]",
"mio::event_imp[0]::opt_as_usize[0]",
"mio::event_imp[0]::opt_from_usize[0]",
"mio::event_imp[0]::ready_as_usize[0]",
"mio::event_imp[0]::ready_from_usize[0]",
"mio::event_imp[0]::{{impl}}[10]::as_usize[0]",
"mio::event_imp[0]::{{impl}}[10]::bits[0]",
"mio::event_imp[0]::{{impl}}[10]::contains[0]",
"mio::event_imp[0]::{{impl}}[10]::empty[0]",
"mio::event_imp[0]::{{impl}}[10]::from_usize[0]",
"mio::event_imp[0]::{{impl}}[10]::is_empty[0]",
"mio::event_imp[0]::{{impl}}[10]::is_none[0]",
"mio::event_imp[0]::{{impl}}[10]::is_readable[0]",
"mio::event_imp[0]::{{impl}}[10]::is_writable[0]",
"mio::event_imp[0]::{{impl}}[10]::none[0]",
"mio::event_imp[0]::{{impl}}[21]::kind[0]",
"mio::event_imp[0]::{{impl}}[21]::new[0]",
"mio::event_imp[0]::{{impl}}[21]::readiness[0]",
"mio::event_imp[0]::{{impl}}[21]::token[0]",
"mio::event_imp[0]::{{impl}}[22]::cmp[0]",
"mio::event_imp[0]::{{impl}}[23]::partial_cmp[0]",
"mio::event_imp[0]::{{impl}}[24]::clone[0]",
"mio::event_imp[0]::{{impl}}[25]::assert_receiver_is_total_eq[0]",
"mio::event_imp[0]::{{impl}}[26]::eq[0]",
"mio::event_imp[0]::{{impl}}[26]::ne[0]",
"mio::event_imp[0]::{{impl}}[28]::cmp[0]",
"mio::event_imp[0]::{{impl}}[29]::partial_cmp[0]",
"mio::event_imp[0]::{{impl}}[30]::clone[0]",
"mio::event_imp[0]::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"mio::event_imp[0]::{{impl}}[32]::eq[0]",
"mio::event_imp[0]::{{impl}}[32]::ne[0]",
"mio::event_imp[0]::{{impl}}[35]::eq[0]",
"mio::event_imp[0]::{{impl}}[35]::ne[0]",
"mio::event_imp[0]::{{impl}}[36]::assert_receiver_is_total_eq[0]",
"mio::event_imp[0]::{{impl}}[37]::clone[0]",
"mio::event_imp[0]::{{impl}}[3]::all[0]",
"mio::event_imp[0]::{{impl}}[3]::bits[0]",
"mio::event_imp[0]::{{impl}}[3]::contains[0]",
"mio::event_imp[0]::{{impl}}[3]::edge[0]",
"mio::event_imp[0]::{{impl}}[3]::empty[0]",
"mio::event_imp[0]::{{impl}}[3]::is_edge[0]",
"mio::event_imp[0]::{{impl}}[3]::is_level[0]",
"mio::event_imp[0]::{{impl}}[3]::is_oneshot[0]",
"mio::event_imp[0]::{{impl}}[3]::is_urgent[0]",
"mio::event_imp[0]::{{impl}}[3]::level[0]",
"mio::event_imp[0]::{{impl}}[3]::oneshot[0]",
"mio::event_imp[0]::{{impl}}[3]::urgent[0]",
"mio::net[0]::tcp[0]::{{impl}}[10]::into_raw_fd[0]",
"mio::net[0]::tcp[0]::{{impl}}[11]::as_raw_fd[0]",
"mio::net[0]::tcp[0]::{{impl}}[13]::into_raw_fd[0]",
"mio::net[0]::tcp[0]::{{impl}}[14]::as_raw_fd[0]",
"mio::net[0]::udp[0]::{{impl}}[3]::into_raw_fd[0]",
"mio::net[0]::udp[0]::{{impl}}[4]::as_raw_fd[0]",
"mio::poll[0]::is_send[0]",
"mio::poll[0]::is_sync[0]",
"mio::poll[0]::{{impl}}[29]::compare_and_swap[0]",
"mio::poll[0]::{{impl}}[29]::load[0]",
"mio::poll[0]::{{impl}}[29]::new[0]",
"mio::poll[0]::{{impl}}[30]::disarm[0]",
"mio::poll[0]::{{impl}}[30]::effective_readiness[0]",
"mio::poll[0]::{{impl}}[30]::next_token_pos[0]",
"mio::poll[0]::{{impl}}[31]::from[0]",
"mio::poll[0]::{{impl}}[32]::from[0]",
"mio::poll[0]::{{impl}}[33]::new[0]",
"mio::poll[0]::{{impl}}[34]::clone[0]",
"mio::poll[0]::{{impl}}[38]::eq[0]",
"mio::poll[0]::{{impl}}[38]::ne[0]",
"mio::poll[0]::{{impl}}[39]::assert_receiver_is_total_eq[0]",
"mio::poll[0]::{{impl}}[40]::clone[0]",
"mio::sys[0]::unix[0]::awakener[0]::pipe[0]::{{impl}}[0]::reader[0]",
"mio::sys[0]::unix[0]::epoll[0]::{{impl}}[0]::id[0]",
"mio::sys[0]::unix[0]::epoll[0]::{{impl}}[1]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::io[0]::{{impl}}[2]::into_raw_fd[0]",
"mio::sys[0]::unix[0]::io[0]::{{impl}}[3]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[0]::aio[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[0]::is_aio[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[11]::cmp[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[12]::partial_cmp[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[13]::clone[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[15]::eq[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[15]::ne[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[1]::from[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[2]::from[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[3]::deref[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[4]::deref_mut[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[5]::bitor[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[6]::bitxor[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[7]::bitand[0]",
"mio::sys[0]::unix[0]::ready[0]::{{impl}}[9]::not[0]",
"mio::sys[0]::unix[0]::tcp[0]::{{impl}}[0]::from_stream[0]",
"mio::sys[0]::unix[0]::tcp[0]::{{impl}}[12]::into_raw_fd[0]",
"mio::sys[0]::unix[0]::tcp[0]::{{impl}}[13]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::tcp[0]::{{impl}}[6]::into_raw_fd[0]",
"mio::sys[0]::unix[0]::tcp[0]::{{impl}}[7]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::udp[0]::{{impl}}[4]::into_raw_fd[0]",
"mio::sys[0]::unix[0]::udp[0]::{{impl}}[5]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::uds[0]::{{impl}}[1]::my_into[0]",
"mio::sys[0]::unix[0]::uds[0]::{{impl}}[6]::from[0]",
"mio::sys[0]::unix[0]::uds[0]::{{impl}}[8]::into_raw_fd[0]",
"mio::sys[0]::unix[0]::uds[0]::{{impl}}[9]::as_raw_fd[0]",
"mio::sys[0]::unix[0]::{{impl}}[0]::is_minus_one[0]",
"mio::sys[0]::unix[0]::{{impl}}[1]::is_minus_one[0]",
"mio::timer[0]::current_tick[0]",
"mio::timer[0]::duration_to_tick[0]",
"mio::timer[0]::{{impl}}[12]::clone[0]",
"mio::timer[0]::{{impl}}[14]::clone[0]",
"mio::timer[0]::{{impl}}[16]::clone[0]",
"mio::timer[0]::{{impl}}[2]::default[0]",
"mio::token[0]::{{impl}}[0]::from[0]",
"mio::token[0]::{{impl}}[1]::from[0]",
"mio::token[0]::{{impl}}[2]::hash[0]",
"mio::token[0]::{{impl}}[3]::cmp[0]",
"mio::token[0]::{{impl}}[4]::partial_cmp[0]",
"mio::token[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"mio::token[0]::{{impl}}[6]::eq[0]",
"mio::token[0]::{{impl}}[6]::ne[0]",
"mio::token[0]::{{impl}}[8]::clone[0]",
"mio::udp[0]::{{impl}}[2]::into_raw_fd[0]",
"mio::udp[0]::{{impl}}[3]::as_raw_fd[0]"
]
