CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"textwrap::{{impl}}[10]::clone[0]",
"textwrap::{{impl}}[8]::clone[0]"
]
