CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"scopeguard::{{impl}}[0]::should_run[0]",
"scopeguard::{{impl}}[1]::should_run[0]",
"scopeguard::{{impl}}[2]::with_strategy[0]",
"scopeguard::{{impl}}[3]::deref[0]",
"scopeguard::{{impl}}[4]::deref_mut[0]"
]
