CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"bytes::buf[0]::buf[0]::Buf[0]::by_ref[0]",
"bytes::buf[0]::buf[0]::Buf[0]::collect[0]",
"bytes::buf[0]::buf[0]::Buf[0]::has_remaining[0]",
"bytes::buf[0]::buf[0]::Buf[0]::iter[0]",
"bytes::buf[0]::buf[0]::Buf[0]::reader[0]",
"bytes::buf[0]::buf[0]::Buf[0]::take[0]",
"bytes::buf[0]::buf[0]::{{impl}}[1]::advance[0]",
"bytes::buf[0]::buf[0]::{{impl}}[1]::remaining[0]",
"bytes::buf[0]::buf_mut[0]::BufMut[0]::by_ref[0]",
"bytes::buf[0]::buf_mut[0]::BufMut[0]::has_remaining_mut[0]",
"bytes::buf[0]::buf_mut[0]::BufMut[0]::writer[0]",
"bytes::buf[0]::buf_mut[0]::{{impl}}[1]::remaining_mut[0]",
"bytes::buf[0]::buf_mut[0]::{{impl}}[2]::remaining_mut[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::first_mut[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::first_ref[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::into_inner[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::last_mut[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::last_ref[0]",
"bytes::buf[0]::chain[0]::{{impl}}[0]::new[0]",
"bytes::buf[0]::chain[0]::{{impl}}[1]::remaining[0]",
"bytes::buf[0]::chain[0]::{{impl}}[2]::remaining_mut[0]",
"bytes::buf[0]::into_buf[0]::{{impl}}[0]::into_buf[0]",
"bytes::buf[0]::iter[0]::new[0]",
"bytes::buf[0]::iter[0]::{{impl}}[0]::get_mut[0]",
"bytes::buf[0]::iter[0]::{{impl}}[0]::get_ref[0]",
"bytes::buf[0]::iter[0]::{{impl}}[0]::into_inner[0]",
"bytes::buf[0]::iter[0]::{{impl}}[1]::size_hint[0]",
"bytes::buf[0]::reader[0]::new[0]",
"bytes::buf[0]::reader[0]::{{impl}}[0]::get_mut[0]",
"bytes::buf[0]::reader[0]::{{impl}}[0]::get_ref[0]",
"bytes::buf[0]::reader[0]::{{impl}}[0]::into_inner[0]",
"bytes::buf[0]::take[0]::new[0]",
"bytes::buf[0]::take[0]::{{impl}}[0]::get_mut[0]",
"bytes::buf[0]::take[0]::{{impl}}[0]::get_ref[0]",
"bytes::buf[0]::take[0]::{{impl}}[0]::into_inner[0]",
"bytes::buf[0]::take[0]::{{impl}}[0]::limit[0]",
"bytes::buf[0]::take[0]::{{impl}}[0]::set_limit[0]",
"bytes::buf[0]::take[0]::{{impl}}[1]::advance[0]",
"bytes::buf[0]::take[0]::{{impl}}[1]::remaining[0]",
"bytes::buf[0]::writer[0]::new[0]",
"bytes::buf[0]::writer[0]::{{impl}}[0]::get_mut[0]",
"bytes::buf[0]::writer[0]::{{impl}}[0]::get_ref[0]",
"bytes::buf[0]::writer[0]::{{impl}}[0]::into_inner[0]",
"bytes::bytes[0]::abort[0]",
"bytes::bytes[0]::{{impl}}[104]::drop[0]"
]
