CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"getopts::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"getopts::{{impl}}[16]::clone[0]",
"getopts::{{impl}}[17]::assert_receiver_is_total_eq[0]",
"getopts::{{impl}}[20]::clone[0]",
"getopts::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"getopts::{{impl}}[9]::clone[0]"
]
