CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"nodrop::imp[0]::needs_drop[0]",
"nodrop::imp[0]::{{impl}}[0]::new[0]"
]
