CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"glob::chars_eq[0]",
"glob::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"glob::{{impl}}[33]::clone[0]",
"glob::{{impl}}[36]::clone[0]",
"glob::{{impl}}[38]::default[0]",
"glob::{{impl}}[39]::hash[0]",
"glob::{{impl}}[40]::cmp[0]",
"glob::{{impl}}[41]::partial_cmp[0]",
"glob::{{impl}}[42]::assert_receiver_is_total_eq[0]",
"glob::{{impl}}[43]::eq[0]",
"glob::{{impl}}[43]::ne[0]",
"glob::{{impl}}[44]::clone[0]",
"glob::{{impl}}[9]::new[0]"
]
