CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"either::{{impl}}[0]::either[0]",
"either::{{impl}}[0]::either_with[0]",
"either::{{impl}}[0]::flip[0]",
"either::{{impl}}[0]::is_left[0]",
"either::{{impl}}[0]::is_right[0]",
"either::{{impl}}[0]::left[0]",
"either::{{impl}}[0]::left_and_then[0]",
"either::{{impl}}[0]::map_left[0]",
"either::{{impl}}[0]::map_right[0]",
"either::{{impl}}[0]::right[0]",
"either::{{impl}}[0]::right_and_then[0]",
"either::{{impl}}[11]::consume[0]",
"either::{{impl}}[13]::as_ref[0]",
"either::{{impl}}[14]::as_mut[0]",
"either::{{impl}}[1]::factor_first[0]",
"either::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"either::{{impl}}[2]::factor_second[0]",
"either::{{impl}}[3]::into_inner[0]",
"either::{{impl}}[4]::from[0]",
"either::{{impl}}[5]::into[0]",
"either::{{impl}}[6]::extend[0]",
"either::{{impl}}[7]::all[0]",
"either::{{impl}}[7]::collect[0]",
"either::{{impl}}[7]::count[0]",
"either::{{impl}}[7]::fold[0]",
"either::{{impl}}[7]::size_hint[0]"
]
