CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unicode_segmentation::grapheme[0]::check_pair[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[12]::clone[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[6]::cur_cursor[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[6]::decide[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[6]::decision[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[6]::new[0]",
"unicode_segmentation::grapheme[0]::{{impl}}[6]::set_cursor[0]",
"unicode_segmentation::tables[0]::grapheme[0]::{{impl}}[0]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::tables[0]::grapheme[0]::{{impl}}[3]::clone[0]",
"unicode_segmentation::tables[0]::util[0]::is_alphabetic[0]",
"unicode_segmentation::tables[0]::util[0]::is_alphanumeric[0]",
"unicode_segmentation::tables[0]::util[0]::is_numeric[0]",
"unicode_segmentation::tables[0]::word[0]::{{impl}}[0]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::tables[0]::word[0]::{{impl}}[3]::clone[0]",
"unicode_segmentation::word[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::word[0]::{{impl}}[14]::clone[0]",
"unicode_segmentation::word[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::word[0]::{{impl}}[19]::clone[0]",
"unicode_segmentation::word[0]::{{impl}}[21]::assert_receiver_is_total_eq[0]",
"unicode_segmentation::word[0]::{{impl}}[24]::clone[0]"
]
