CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fnv::{{impl}}[0]::default[0]",
"fnv::{{impl}}[1]::with_key[0]",
"fnv::{{impl}}[2]::finish[0]"
]
