CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"num_rational::WrappingAbs[0]::wrapping_abs[0]",
"num_rational::opassign[0]::{{impl}}[0]::add_assign[0]",
"num_rational::opassign[0]::{{impl}}[10]::add_assign[0]",
"num_rational::opassign[0]::{{impl}}[11]::add_assign[0]",
"num_rational::opassign[0]::{{impl}}[12]::div_assign[0]",
"num_rational::opassign[0]::{{impl}}[13]::div_assign[0]",
"num_rational::opassign[0]::{{impl}}[14]::mul_assign[0]",
"num_rational::opassign[0]::{{impl}}[15]::mul_assign[0]",
"num_rational::opassign[0]::{{impl}}[16]::rem_assign[0]",
"num_rational::opassign[0]::{{impl}}[17]::rem_assign[0]",
"num_rational::opassign[0]::{{impl}}[18]::sub_assign[0]",
"num_rational::opassign[0]::{{impl}}[19]::sub_assign[0]",
"num_rational::opassign[0]::{{impl}}[1]::div_assign[0]",
"num_rational::opassign[0]::{{impl}}[2]::mul_assign[0]",
"num_rational::opassign[0]::{{impl}}[3]::rem_assign[0]",
"num_rational::opassign[0]::{{impl}}[4]::sub_assign[0]",
"num_rational::opassign[0]::{{impl}}[5]::add_assign[0]",
"num_rational::opassign[0]::{{impl}}[6]::div_assign[0]",
"num_rational::opassign[0]::{{impl}}[7]::mul_assign[0]",
"num_rational::opassign[0]::{{impl}}[8]::rem_assign[0]",
"num_rational::opassign[0]::{{impl}}[9]::sub_assign[0]",
"num_rational::{{impl}}[0]::ceil[0]",
"num_rational::{{impl}}[0]::denom[0]",
"num_rational::{{impl}}[0]::floor[0]",
"num_rational::{{impl}}[0]::fract[0]",
"num_rational::{{impl}}[0]::from_integer[0]",
"num_rational::{{impl}}[0]::is_integer[0]",
"num_rational::{{impl}}[0]::new_raw[0]",
"num_rational::{{impl}}[0]::numer[0]",
"num_rational::{{impl}}[0]::reduce[0]",
"num_rational::{{impl}}[0]::reduced[0]",
"num_rational::{{impl}}[0]::round[0]",
"num_rational::{{impl}}[0]::to_integer[0]",
"num_rational::{{impl}}[0]::trunc[0]",
"num_rational::{{impl}}[100]::sub[0]",
"num_rational::{{impl}}[101]::sub[0]",
"num_rational::{{impl}}[102]::sub[0]",
"num_rational::{{impl}}[103]::sub[0]",
"num_rational::{{impl}}[104]::sub[0]",
"num_rational::{{impl}}[105]::sub[0]",
"num_rational::{{impl}}[106]::sub[0]",
"num_rational::{{impl}}[107]::sub[0]",
"num_rational::{{impl}}[108]::rem[0]",
"num_rational::{{impl}}[109]::rem[0]",
"num_rational::{{impl}}[10]::cmp[0]",
"num_rational::{{impl}}[110]::rem[0]",
"num_rational::{{impl}}[111]::rem[0]",
"num_rational::{{impl}}[112]::rem[0]",
"num_rational::{{impl}}[113]::rem[0]",
"num_rational::{{impl}}[114]::rem[0]",
"num_rational::{{impl}}[115]::rem[0]",
"num_rational::{{impl}}[116]::checked_add[0]",
"num_rational::{{impl}}[117]::checked_sub[0]",
"num_rational::{{impl}}[118]::eq[0]",
"num_rational::{{impl}}[118]::ne[0]",
"num_rational::{{impl}}[11]::partial_cmp[0]",
"num_rational::{{impl}}[120]::clone[0]",
"num_rational::{{impl}}[124]::clone[0]",
"num_rational::{{impl}}[14]::hash[0]",
"num_rational::{{impl}}[14]::hash[0]::recurse[0]",
"num_rational::{{impl}}[15]::mul[0]",
"num_rational::{{impl}}[16]::mul[0]",
"num_rational::{{impl}}[17]::div[0]",
"num_rational::{{impl}}[18]::div[0]",
"num_rational::{{impl}}[19]::checked_mul[0]",
"num_rational::{{impl}}[1]::pow[0]",
"num_rational::{{impl}}[20]::checked_div[0]",
"num_rational::{{impl}}[21]::neg[0]",
"num_rational::{{impl}}[22]::neg[0]",
"num_rational::{{impl}}[23]::inv[0]",
"num_rational::{{impl}}[24]::inv[0]",
"num_rational::{{impl}}[25]::is_zero[0]",
"num_rational::{{impl}}[25]::zero[0]",
"num_rational::{{impl}}[26]::is_one[0]",
"num_rational::{{impl}}[26]::one[0]",
"num_rational::{{impl}}[28]::abs[0]",
"num_rational::{{impl}}[28]::abs_sub[0]",
"num_rational::{{impl}}[28]::is_negative[0]",
"num_rational::{{impl}}[28]::is_positive[0]",
"num_rational::{{impl}}[28]::signum[0]",
"num_rational::{{impl}}[31]::into[0]",
"num_rational::{{impl}}[38]::clone[0]",
"num_rational::{{impl}}[41]::pow[0]",
"num_rational::{{impl}}[42]::pow[0]",
"num_rational::{{impl}}[43]::pow[0]",
"num_rational::{{impl}}[45]::pow[0]",
"num_rational::{{impl}}[46]::pow[0]",
"num_rational::{{impl}}[47]::pow[0]",
"num_rational::{{impl}}[49]::pow[0]",
"num_rational::{{impl}}[50]::pow[0]",
"num_rational::{{impl}}[51]::pow[0]",
"num_rational::{{impl}}[53]::pow[0]",
"num_rational::{{impl}}[54]::pow[0]",
"num_rational::{{impl}}[55]::pow[0]",
"num_rational::{{impl}}[57]::pow[0]",
"num_rational::{{impl}}[58]::pow[0]",
"num_rational::{{impl}}[59]::pow[0]",
"num_rational::{{impl}}[61]::pow[0]",
"num_rational::{{impl}}[62]::pow[0]",
"num_rational::{{impl}}[63]::pow[0]",
"num_rational::{{impl}}[65]::pow[0]",
"num_rational::{{impl}}[66]::pow[0]",
"num_rational::{{impl}}[67]::pow[0]",
"num_rational::{{impl}}[69]::pow[0]",
"num_rational::{{impl}}[70]::pow[0]",
"num_rational::{{impl}}[71]::pow[0]",
"num_rational::{{impl}}[73]::pow[0]",
"num_rational::{{impl}}[74]::pow[0]",
"num_rational::{{impl}}[75]::pow[0]",
"num_rational::{{impl}}[77]::pow[0]",
"num_rational::{{impl}}[78]::pow[0]",
"num_rational::{{impl}}[79]::pow[0]",
"num_rational::{{impl}}[80]::mul[0]",
"num_rational::{{impl}}[81]::mul[0]",
"num_rational::{{impl}}[82]::mul[0]",
"num_rational::{{impl}}[83]::mul[0]",
"num_rational::{{impl}}[84]::mul[0]",
"num_rational::{{impl}}[85]::mul[0]",
"num_rational::{{impl}}[86]::div[0]",
"num_rational::{{impl}}[87]::div[0]",
"num_rational::{{impl}}[88]::div[0]",
"num_rational::{{impl}}[89]::div[0]",
"num_rational::{{impl}}[8]::from[0]",
"num_rational::{{impl}}[90]::div[0]",
"num_rational::{{impl}}[91]::div[0]",
"num_rational::{{impl}}[92]::add[0]",
"num_rational::{{impl}}[93]::add[0]",
"num_rational::{{impl}}[94]::add[0]",
"num_rational::{{impl}}[95]::add[0]",
"num_rational::{{impl}}[96]::add[0]",
"num_rational::{{impl}}[97]::add[0]",
"num_rational::{{impl}}[98]::add[0]",
"num_rational::{{impl}}[99]::add[0]",
"num_rational::{{impl}}[9]::from[0]"
]
