CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crossbeam_utils::cache_padded[0]::{{impl}}[2]::new[0]",
"crossbeam_utils::cache_padded[0]::{{impl}}[3]::deref[0]",
"crossbeam_utils::cache_padded[0]::{{impl}}[4]::deref_mut[0]",
"crossbeam_utils::cache_padded[0]::{{impl}}[6]::from[0]",
"crossbeam_utils::cache_padded[0]::{{impl}}[7]::default[0]",
"crossbeam_utils::cache_padded[0]::{{impl}}[8]::clone[0]",
"crossbeam_utils::consume[0]::{{impl}}[1]::load_consume[0]",
"crossbeam_utils::consume[0]::{{impl}}[2]::load_consume[0]",
"crossbeam_utils::consume[0]::{{impl}}[3]::load_consume[0]",
"crossbeam_utils::thread[0]::{{impl}}[0]::call_box[0]"
]
