CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"semver_parser::lexer[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"semver_parser::range[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"semver_parser::range[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]"
]
