CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"arrayvec::array[0]::{{impl}}[10]::capacity[0]",
"arrayvec::array[0]::{{impl}}[11]::capacity[0]",
"arrayvec::array[0]::{{impl}}[12]::capacity[0]",
"arrayvec::array[0]::{{impl}}[13]::capacity[0]",
"arrayvec::array[0]::{{impl}}[14]::capacity[0]",
"arrayvec::array[0]::{{impl}}[15]::capacity[0]",
"arrayvec::array[0]::{{impl}}[16]::capacity[0]",
"arrayvec::array[0]::{{impl}}[17]::capacity[0]",
"arrayvec::array[0]::{{impl}}[18]::capacity[0]",
"arrayvec::array[0]::{{impl}}[19]::capacity[0]",
"arrayvec::array[0]::{{impl}}[20]::capacity[0]",
"arrayvec::array[0]::{{impl}}[21]::capacity[0]",
"arrayvec::array[0]::{{impl}}[22]::capacity[0]",
"arrayvec::array[0]::{{impl}}[23]::capacity[0]",
"arrayvec::array[0]::{{impl}}[24]::capacity[0]",
"arrayvec::array[0]::{{impl}}[25]::capacity[0]",
"arrayvec::array[0]::{{impl}}[26]::capacity[0]",
"arrayvec::array[0]::{{impl}}[27]::capacity[0]",
"arrayvec::array[0]::{{impl}}[28]::capacity[0]",
"arrayvec::array[0]::{{impl}}[29]::capacity[0]",
"arrayvec::array[0]::{{impl}}[30]::capacity[0]",
"arrayvec::array[0]::{{impl}}[31]::capacity[0]",
"arrayvec::array[0]::{{impl}}[32]::capacity[0]",
"arrayvec::array[0]::{{impl}}[33]::capacity[0]",
"arrayvec::array[0]::{{impl}}[34]::capacity[0]",
"arrayvec::array[0]::{{impl}}[35]::capacity[0]",
"arrayvec::array[0]::{{impl}}[36]::capacity[0]",
"arrayvec::array[0]::{{impl}}[37]::capacity[0]",
"arrayvec::array[0]::{{impl}}[38]::capacity[0]",
"arrayvec::array[0]::{{impl}}[39]::capacity[0]",
"arrayvec::array[0]::{{impl}}[40]::capacity[0]",
"arrayvec::array[0]::{{impl}}[41]::capacity[0]",
"arrayvec::array[0]::{{impl}}[42]::capacity[0]",
"arrayvec::array[0]::{{impl}}[43]::capacity[0]",
"arrayvec::array[0]::{{impl}}[44]::capacity[0]",
"arrayvec::array[0]::{{impl}}[45]::capacity[0]",
"arrayvec::array[0]::{{impl}}[46]::capacity[0]",
"arrayvec::array[0]::{{impl}}[47]::capacity[0]",
"arrayvec::array[0]::{{impl}}[48]::capacity[0]",
"arrayvec::array[0]::{{impl}}[49]::capacity[0]",
"arrayvec::array[0]::{{impl}}[4]::from[0]",
"arrayvec::array[0]::{{impl}}[4]::to_usize[0]",
"arrayvec::array[0]::{{impl}}[50]::capacity[0]",
"arrayvec::array[0]::{{impl}}[51]::capacity[0]",
"arrayvec::array[0]::{{impl}}[52]::capacity[0]",
"arrayvec::array[0]::{{impl}}[53]::capacity[0]",
"arrayvec::array[0]::{{impl}}[54]::capacity[0]",
"arrayvec::array[0]::{{impl}}[55]::capacity[0]",
"arrayvec::array[0]::{{impl}}[56]::capacity[0]",
"arrayvec::array[0]::{{impl}}[57]::capacity[0]",
"arrayvec::array[0]::{{impl}}[58]::capacity[0]",
"arrayvec::array[0]::{{impl}}[59]::capacity[0]",
"arrayvec::array[0]::{{impl}}[5]::capacity[0]",
"arrayvec::array[0]::{{impl}}[60]::capacity[0]",
"arrayvec::array[0]::{{impl}}[6]::capacity[0]",
"arrayvec::array[0]::{{impl}}[7]::capacity[0]",
"arrayvec::array[0]::{{impl}}[8]::capacity[0]",
"arrayvec::array[0]::{{impl}}[9]::capacity[0]",
"arrayvec::errors[0]::{{impl}}[0]::element[0]",
"arrayvec::errors[0]::{{impl}}[0]::new[0]",
"arrayvec::errors[0]::{{impl}}[0]::simplify[0]",
"arrayvec::errors[0]::{{impl}}[4]::partial_cmp[0]",
"arrayvec::errors[0]::{{impl}}[5]::eq[0]",
"arrayvec::errors[0]::{{impl}}[5]::ne[0]",
"arrayvec::errors[0]::{{impl}}[6]::cmp[0]",
"arrayvec::errors[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"arrayvec::errors[0]::{{impl}}[9]::clone[0]",
"arrayvec::range[0]::RangeArgument[0]::end[0]",
"arrayvec::range[0]::RangeArgument[0]::start[0]",
"arrayvec::range[0]::{{impl}}[1]::start[0]",
"arrayvec::range[0]::{{impl}}[2]::end[0]",
"arrayvec::range[0]::{{impl}}[3]::end[0]",
"arrayvec::range[0]::{{impl}}[3]::start[0]"
]
