CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crossbeam_epoch::atomic[0]::strongest_failure_ordering[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[15]::into_usize[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[16]::new[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[19]::clone[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[1]::failure[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[1]::success[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[22]::from[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[24]::borrow[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[25]::borrow_mut[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[26]::as_ref[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[27]::as_mut[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[2]::failure[0]",
"crossbeam_epoch::atomic[0]::{{impl}}[2]::success[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[0]::starting[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[0]::successor[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[1]::compare_and_swap[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[1]::load[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[1]::new[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[1]::store[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[2]::eq[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[2]::ne[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[5]::default[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[6]::clone[0]",
"crossbeam_epoch::epoch[0]::{{impl}}[9]::default[0]"
]
