CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"num_bigint::big_digit[0]::from_doublebigdigit[0]",
"num_bigint::bigint[0]::{{impl}}[0]::neg[0]",
"num_bigint::bigint[0]::{{impl}}[122]::clone[0]",
"num_bigint::bigint[0]::{{impl}}[125]::assert_receiver_is_total_eq[0]",
"num_bigint::bigint[0]::{{impl}}[1]::mul[0]",
"num_bigint::biguint[0]::algorithms[0]::ilog2[0]",
"num_bigint::{{impl}}[0]::empty[0]",
"num_bigint::{{impl}}[0]::invalid[0]",
"num_bigint::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"num_bigint::{{impl}}[4]::eq[0]",
"num_bigint::{{impl}}[4]::ne[0]",
"num_bigint::{{impl}}[5]::clone[0]",
"num_bigint::{{impl}}[7]::assert_receiver_is_total_eq[0]"
]
