CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"filetime::{{impl}}[0]::from_unix_time[0]",
"filetime::{{impl}}[0]::nanoseconds[0]",
"filetime::{{impl}}[0]::seconds[0]",
"filetime::{{impl}}[0]::unix_seconds[0]",
"filetime::{{impl}}[0]::zero[0]",
"filetime::{{impl}}[2]::hash[0]",
"filetime::{{impl}}[3]::clone[0]",
"filetime::{{impl}}[6]::partial_cmp[0]",
"filetime::{{impl}}[7]::cmp[0]",
"filetime::{{impl}}[8]::eq[0]",
"filetime::{{impl}}[8]::ne[0]",
"filetime::{{impl}}[9]::assert_receiver_is_total_eq[0]"
]
