CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"phf_shared::displace[0]",
"phf_shared::hash[0]",
"phf_shared::{{impl}}[10]::phf_hash[0]",
"phf_shared::{{impl}}[11]::phf_hash[0]",
"phf_shared::{{impl}}[12]::phf_hash[0]",
"phf_shared::{{impl}}[13]::phf_hash[0]",
"phf_shared::{{impl}}[14]::phf_hash[0]",
"phf_shared::{{impl}}[15]::phf_hash[0]",
"phf_shared::{{impl}}[6]::phf_hash[0]",
"phf_shared::{{impl}}[7]::phf_hash[0]",
"phf_shared::{{impl}}[8]::phf_hash[0]",
"phf_shared::{{impl}}[9]::phf_hash[0]"
]
