CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"num_complex::cast[0]::{{impl}}[0]::to_i128[0]",
"num_complex::cast[0]::{{impl}}[0]::to_i16[0]",
"num_complex::cast[0]::{{impl}}[0]::to_i32[0]",
"num_complex::cast[0]::{{impl}}[0]::to_i64[0]",
"num_complex::cast[0]::{{impl}}[0]::to_i8[0]",
"num_complex::cast[0]::{{impl}}[0]::to_isize[0]",
"num_complex::cast[0]::{{impl}}[0]::to_u128[0]",
"num_complex::cast[0]::{{impl}}[0]::to_u16[0]",
"num_complex::cast[0]::{{impl}}[0]::to_u32[0]",
"num_complex::cast[0]::{{impl}}[0]::to_u64[0]",
"num_complex::cast[0]::{{impl}}[0]::to_u8[0]",
"num_complex::cast[0]::{{impl}}[0]::to_usize[0]",
"num_complex::cast[0]::{{impl}}[3]::as_[0]",
"num_complex::opassign[0]::{{impl}}[0]::add_assign[0]",
"num_complex::opassign[0]::{{impl}}[10]::rem_assign[0]",
"num_complex::opassign[0]::{{impl}}[11]::rem_assign[0]",
"num_complex::opassign[0]::{{impl}}[12]::add_assign[0]",
"num_complex::opassign[0]::{{impl}}[13]::add_assign[0]",
"num_complex::opassign[0]::{{impl}}[14]::sub_assign[0]",
"num_complex::opassign[0]::{{impl}}[15]::sub_assign[0]",
"num_complex::opassign[0]::{{impl}}[16]::mul_assign[0]",
"num_complex::opassign[0]::{{impl}}[17]::mul_assign[0]",
"num_complex::opassign[0]::{{impl}}[18]::div_assign[0]",
"num_complex::opassign[0]::{{impl}}[19]::div_assign[0]",
"num_complex::opassign[0]::{{impl}}[1]::sub_assign[0]",
"num_complex::opassign[0]::{{impl}}[2]::mul_assign[0]",
"num_complex::opassign[0]::{{impl}}[3]::div_assign[0]",
"num_complex::opassign[0]::{{impl}}[4]::rem_assign[0]",
"num_complex::opassign[0]::{{impl}}[5]::add_assign[0]",
"num_complex::opassign[0]::{{impl}}[6]::sub_assign[0]",
"num_complex::opassign[0]::{{impl}}[7]::mul_assign[0]",
"num_complex::opassign[0]::{{impl}}[8]::div_assign[0]",
"num_complex::opassign[0]::{{impl}}[9]::rem_assign[0]",
"num_complex::{{impl}}[0]::i[0]",
"num_complex::{{impl}}[0]::new[0]",
"num_complex::{{impl}}[0]::norm_sqr[0]",
"num_complex::{{impl}}[0]::scale[0]",
"num_complex::{{impl}}[0]::unscale[0]",
"num_complex::{{impl}}[100]::add[0]",
"num_complex::{{impl}}[101]::sub[0]",
"num_complex::{{impl}}[102]::mul[0]",
"num_complex::{{impl}}[103]::div[0]",
"num_complex::{{impl}}[104]::rem[0]",
"num_complex::{{impl}}[105]::add[0]",
"num_complex::{{impl}}[106]::sub[0]",
"num_complex::{{impl}}[107]::mul[0]",
"num_complex::{{impl}}[108]::div[0]",
"num_complex::{{impl}}[109]::rem[0]",
"num_complex::{{impl}}[10]::rem[0]",
"num_complex::{{impl}}[110]::add[0]",
"num_complex::{{impl}}[111]::sub[0]",
"num_complex::{{impl}}[112]::mul[0]",
"num_complex::{{impl}}[113]::div[0]",
"num_complex::{{impl}}[114]::rem[0]",
"num_complex::{{impl}}[115]::add[0]",
"num_complex::{{impl}}[116]::sub[0]",
"num_complex::{{impl}}[117]::mul[0]",
"num_complex::{{impl}}[118]::div[0]",
"num_complex::{{impl}}[119]::rem[0]",
"num_complex::{{impl}}[11]::neg[0]",
"num_complex::{{impl}}[12]::neg[0]",
"num_complex::{{impl}}[130]::add[0]",
"num_complex::{{impl}}[131]::add[0]",
"num_complex::{{impl}}[132]::add[0]",
"num_complex::{{impl}}[133]::add[0]",
"num_complex::{{impl}}[134]::add[0]",
"num_complex::{{impl}}[135]::add[0]",
"num_complex::{{impl}}[136]::add[0]",
"num_complex::{{impl}}[137]::add[0]",
"num_complex::{{impl}}[138]::add[0]",
"num_complex::{{impl}}[139]::add[0]",
"num_complex::{{impl}}[13]::inv[0]",
"num_complex::{{impl}}[140]::add[0]",
"num_complex::{{impl}}[141]::add[0]",
"num_complex::{{impl}}[142]::add[0]",
"num_complex::{{impl}}[143]::add[0]",
"num_complex::{{impl}}[144]::add[0]",
"num_complex::{{impl}}[145]::add[0]",
"num_complex::{{impl}}[146]::add[0]",
"num_complex::{{impl}}[147]::add[0]",
"num_complex::{{impl}}[148]::add[0]",
"num_complex::{{impl}}[149]::add[0]",
"num_complex::{{impl}}[14]::inv[0]",
"num_complex::{{impl}}[150]::add[0]",
"num_complex::{{impl}}[151]::add[0]",
"num_complex::{{impl}}[152]::add[0]",
"num_complex::{{impl}}[153]::add[0]",
"num_complex::{{impl}}[154]::add[0]",
"num_complex::{{impl}}[155]::add[0]",
"num_complex::{{impl}}[156]::add[0]",
"num_complex::{{impl}}[157]::add[0]",
"num_complex::{{impl}}[158]::add[0]",
"num_complex::{{impl}}[159]::add[0]",
"num_complex::{{impl}}[15]::add[0]",
"num_complex::{{impl}}[160]::add[0]",
"num_complex::{{impl}}[161]::add[0]",
"num_complex::{{impl}}[162]::add[0]",
"num_complex::{{impl}}[163]::add[0]",
"num_complex::{{impl}}[164]::add[0]",
"num_complex::{{impl}}[165]::add[0]",
"num_complex::{{impl}}[166]::add[0]",
"num_complex::{{impl}}[167]::add[0]",
"num_complex::{{impl}}[168]::add[0]",
"num_complex::{{impl}}[16]::sub[0]",
"num_complex::{{impl}}[175]::sub[0]",
"num_complex::{{impl}}[176]::sub[0]",
"num_complex::{{impl}}[177]::sub[0]",
"num_complex::{{impl}}[178]::sub[0]",
"num_complex::{{impl}}[179]::sub[0]",
"num_complex::{{impl}}[17]::mul[0]",
"num_complex::{{impl}}[180]::sub[0]",
"num_complex::{{impl}}[181]::sub[0]",
"num_complex::{{impl}}[182]::sub[0]",
"num_complex::{{impl}}[183]::sub[0]",
"num_complex::{{impl}}[184]::sub[0]",
"num_complex::{{impl}}[185]::sub[0]",
"num_complex::{{impl}}[186]::sub[0]",
"num_complex::{{impl}}[187]::sub[0]",
"num_complex::{{impl}}[188]::sub[0]",
"num_complex::{{impl}}[189]::sub[0]",
"num_complex::{{impl}}[18]::div[0]",
"num_complex::{{impl}}[190]::sub[0]",
"num_complex::{{impl}}[191]::sub[0]",
"num_complex::{{impl}}[192]::sub[0]",
"num_complex::{{impl}}[193]::sub[0]",
"num_complex::{{impl}}[194]::sub[0]",
"num_complex::{{impl}}[195]::sub[0]",
"num_complex::{{impl}}[196]::sub[0]",
"num_complex::{{impl}}[197]::sub[0]",
"num_complex::{{impl}}[198]::sub[0]",
"num_complex::{{impl}}[199]::sub[0]",
"num_complex::{{impl}}[19]::rem[0]",
"num_complex::{{impl}}[1]::conj[0]",
"num_complex::{{impl}}[1]::inv[0]",
"num_complex::{{impl}}[200]::sub[0]",
"num_complex::{{impl}}[201]::sub[0]",
"num_complex::{{impl}}[202]::sub[0]",
"num_complex::{{impl}}[203]::sub[0]",
"num_complex::{{impl}}[204]::sub[0]",
"num_complex::{{impl}}[205]::sub[0]",
"num_complex::{{impl}}[206]::sub[0]",
"num_complex::{{impl}}[207]::sub[0]",
"num_complex::{{impl}}[208]::sub[0]",
"num_complex::{{impl}}[209]::sub[0]",
"num_complex::{{impl}}[20]::is_zero[0]",
"num_complex::{{impl}}[20]::zero[0]",
"num_complex::{{impl}}[210]::sub[0]",
"num_complex::{{impl}}[211]::sub[0]",
"num_complex::{{impl}}[212]::sub[0]",
"num_complex::{{impl}}[213]::sub[0]",
"num_complex::{{impl}}[21]::is_one[0]",
"num_complex::{{impl}}[21]::one[0]",
"num_complex::{{impl}}[220]::mul[0]",
"num_complex::{{impl}}[221]::mul[0]",
"num_complex::{{impl}}[222]::mul[0]",
"num_complex::{{impl}}[223]::mul[0]",
"num_complex::{{impl}}[224]::mul[0]",
"num_complex::{{impl}}[225]::mul[0]",
"num_complex::{{impl}}[226]::mul[0]",
"num_complex::{{impl}}[227]::mul[0]",
"num_complex::{{impl}}[228]::mul[0]",
"num_complex::{{impl}}[229]::mul[0]",
"num_complex::{{impl}}[230]::mul[0]",
"num_complex::{{impl}}[231]::mul[0]",
"num_complex::{{impl}}[232]::mul[0]",
"num_complex::{{impl}}[233]::mul[0]",
"num_complex::{{impl}}[234]::mul[0]",
"num_complex::{{impl}}[235]::mul[0]",
"num_complex::{{impl}}[236]::mul[0]",
"num_complex::{{impl}}[237]::mul[0]",
"num_complex::{{impl}}[238]::mul[0]",
"num_complex::{{impl}}[239]::mul[0]",
"num_complex::{{impl}}[240]::mul[0]",
"num_complex::{{impl}}[241]::mul[0]",
"num_complex::{{impl}}[242]::mul[0]",
"num_complex::{{impl}}[243]::mul[0]",
"num_complex::{{impl}}[244]::mul[0]",
"num_complex::{{impl}}[245]::mul[0]",
"num_complex::{{impl}}[246]::mul[0]",
"num_complex::{{impl}}[247]::mul[0]",
"num_complex::{{impl}}[248]::mul[0]",
"num_complex::{{impl}}[249]::mul[0]",
"num_complex::{{impl}}[250]::mul[0]",
"num_complex::{{impl}}[251]::mul[0]",
"num_complex::{{impl}}[252]::mul[0]",
"num_complex::{{impl}}[253]::mul[0]",
"num_complex::{{impl}}[254]::mul[0]",
"num_complex::{{impl}}[255]::mul[0]",
"num_complex::{{impl}}[256]::mul[0]",
"num_complex::{{impl}}[257]::mul[0]",
"num_complex::{{impl}}[258]::mul[0]",
"num_complex::{{impl}}[265]::div[0]",
"num_complex::{{impl}}[266]::div[0]",
"num_complex::{{impl}}[267]::div[0]",
"num_complex::{{impl}}[268]::div[0]",
"num_complex::{{impl}}[269]::div[0]",
"num_complex::{{impl}}[270]::div[0]",
"num_complex::{{impl}}[271]::div[0]",
"num_complex::{{impl}}[272]::div[0]",
"num_complex::{{impl}}[273]::div[0]",
"num_complex::{{impl}}[274]::div[0]",
"num_complex::{{impl}}[275]::div[0]",
"num_complex::{{impl}}[276]::div[0]",
"num_complex::{{impl}}[277]::div[0]",
"num_complex::{{impl}}[278]::div[0]",
"num_complex::{{impl}}[279]::div[0]",
"num_complex::{{impl}}[280]::div[0]",
"num_complex::{{impl}}[281]::div[0]",
"num_complex::{{impl}}[282]::div[0]",
"num_complex::{{impl}}[283]::div[0]",
"num_complex::{{impl}}[284]::div[0]",
"num_complex::{{impl}}[285]::div[0]",
"num_complex::{{impl}}[286]::div[0]",
"num_complex::{{impl}}[287]::div[0]",
"num_complex::{{impl}}[288]::div[0]",
"num_complex::{{impl}}[289]::div[0]",
"num_complex::{{impl}}[290]::div[0]",
"num_complex::{{impl}}[291]::div[0]",
"num_complex::{{impl}}[292]::div[0]",
"num_complex::{{impl}}[293]::div[0]",
"num_complex::{{impl}}[294]::div[0]",
"num_complex::{{impl}}[295]::div[0]",
"num_complex::{{impl}}[296]::div[0]",
"num_complex::{{impl}}[297]::div[0]",
"num_complex::{{impl}}[298]::div[0]",
"num_complex::{{impl}}[299]::div[0]",
"num_complex::{{impl}}[2]::acos[0]",
"num_complex::{{impl}}[2]::acosh[0]",
"num_complex::{{impl}}[2]::arg[0]",
"num_complex::{{impl}}[2]::asin[0]",
"num_complex::{{impl}}[2]::asinh[0]",
"num_complex::{{impl}}[2]::atan[0]",
"num_complex::{{impl}}[2]::atanh[0]",
"num_complex::{{impl}}[2]::cos[0]",
"num_complex::{{impl}}[2]::cosh[0]",
"num_complex::{{impl}}[2]::exp[0]",
"num_complex::{{impl}}[2]::expf[0]",
"num_complex::{{impl}}[2]::from_polar[0]",
"num_complex::{{impl}}[2]::ln[0]",
"num_complex::{{impl}}[2]::log[0]",
"num_complex::{{impl}}[2]::norm[0]",
"num_complex::{{impl}}[2]::powc[0]",
"num_complex::{{impl}}[2]::powf[0]",
"num_complex::{{impl}}[2]::sin[0]",
"num_complex::{{impl}}[2]::sinh[0]",
"num_complex::{{impl}}[2]::sqrt[0]",
"num_complex::{{impl}}[2]::tan[0]",
"num_complex::{{impl}}[2]::tanh[0]",
"num_complex::{{impl}}[2]::to_polar[0]",
"num_complex::{{impl}}[300]::div[0]",
"num_complex::{{impl}}[301]::div[0]",
"num_complex::{{impl}}[302]::div[0]",
"num_complex::{{impl}}[303]::div[0]",
"num_complex::{{impl}}[310]::rem[0]",
"num_complex::{{impl}}[311]::rem[0]",
"num_complex::{{impl}}[312]::rem[0]",
"num_complex::{{impl}}[313]::rem[0]",
"num_complex::{{impl}}[314]::rem[0]",
"num_complex::{{impl}}[315]::rem[0]",
"num_complex::{{impl}}[316]::rem[0]",
"num_complex::{{impl}}[317]::rem[0]",
"num_complex::{{impl}}[318]::rem[0]",
"num_complex::{{impl}}[319]::rem[0]",
"num_complex::{{impl}}[320]::rem[0]",
"num_complex::{{impl}}[321]::rem[0]",
"num_complex::{{impl}}[322]::rem[0]",
"num_complex::{{impl}}[323]::rem[0]",
"num_complex::{{impl}}[324]::rem[0]",
"num_complex::{{impl}}[325]::rem[0]",
"num_complex::{{impl}}[326]::rem[0]",
"num_complex::{{impl}}[327]::rem[0]",
"num_complex::{{impl}}[328]::rem[0]",
"num_complex::{{impl}}[329]::rem[0]",
"num_complex::{{impl}}[330]::rem[0]",
"num_complex::{{impl}}[331]::rem[0]",
"num_complex::{{impl}}[332]::rem[0]",
"num_complex::{{impl}}[333]::rem[0]",
"num_complex::{{impl}}[334]::rem[0]",
"num_complex::{{impl}}[335]::rem[0]",
"num_complex::{{impl}}[336]::rem[0]",
"num_complex::{{impl}}[337]::rem[0]",
"num_complex::{{impl}}[338]::rem[0]",
"num_complex::{{impl}}[339]::rem[0]",
"num_complex::{{impl}}[340]::rem[0]",
"num_complex::{{impl}}[341]::rem[0]",
"num_complex::{{impl}}[342]::rem[0]",
"num_complex::{{impl}}[343]::rem[0]",
"num_complex::{{impl}}[344]::rem[0]",
"num_complex::{{impl}}[345]::rem[0]",
"num_complex::{{impl}}[346]::rem[0]",
"num_complex::{{impl}}[347]::rem[0]",
"num_complex::{{impl}}[348]::rem[0]",
"num_complex::{{impl}}[355]::eq[0]",
"num_complex::{{impl}}[355]::ne[0]",
"num_complex::{{impl}}[35]::from_error[0]",
"num_complex::{{impl}}[35]::new[0]",
"num_complex::{{impl}}[38]::default[0]",
"num_complex::{{impl}}[3]::is_finite[0]",
"num_complex::{{impl}}[3]::is_infinite[0]",
"num_complex::{{impl}}[3]::is_nan[0]",
"num_complex::{{impl}}[3]::is_normal[0]",
"num_complex::{{impl}}[40]::hash[0]",
"num_complex::{{impl}}[41]::clone[0]",
"num_complex::{{impl}}[43]::assert_receiver_is_total_eq[0]",
"num_complex::{{impl}}[44]::eq[0]",
"num_complex::{{impl}}[44]::ne[0]",
"num_complex::{{impl}}[45]::add[0]",
"num_complex::{{impl}}[46]::add[0]",
"num_complex::{{impl}}[47]::add[0]",
"num_complex::{{impl}}[48]::sub[0]",
"num_complex::{{impl}}[49]::sub[0]",
"num_complex::{{impl}}[4]::from[0]",
"num_complex::{{impl}}[50]::sub[0]",
"num_complex::{{impl}}[51]::mul[0]",
"num_complex::{{impl}}[52]::mul[0]",
"num_complex::{{impl}}[53]::mul[0]",
"num_complex::{{impl}}[54]::div[0]",
"num_complex::{{impl}}[55]::div[0]",
"num_complex::{{impl}}[56]::div[0]",
"num_complex::{{impl}}[57]::rem[0]",
"num_complex::{{impl}}[58]::rem[0]",
"num_complex::{{impl}}[59]::rem[0]",
"num_complex::{{impl}}[5]::from[0]",
"num_complex::{{impl}}[60]::add[0]",
"num_complex::{{impl}}[61]::sub[0]",
"num_complex::{{impl}}[62]::mul[0]",
"num_complex::{{impl}}[63]::div[0]",
"num_complex::{{impl}}[64]::rem[0]",
"num_complex::{{impl}}[65]::add[0]",
"num_complex::{{impl}}[66]::sub[0]",
"num_complex::{{impl}}[67]::mul[0]",
"num_complex::{{impl}}[68]::div[0]",
"num_complex::{{impl}}[69]::rem[0]",
"num_complex::{{impl}}[6]::add[0]",
"num_complex::{{impl}}[70]::add[0]",
"num_complex::{{impl}}[71]::sub[0]",
"num_complex::{{impl}}[72]::mul[0]",
"num_complex::{{impl}}[73]::div[0]",
"num_complex::{{impl}}[74]::rem[0]",
"num_complex::{{impl}}[75]::add[0]",
"num_complex::{{impl}}[76]::sub[0]",
"num_complex::{{impl}}[77]::mul[0]",
"num_complex::{{impl}}[78]::div[0]",
"num_complex::{{impl}}[79]::rem[0]",
"num_complex::{{impl}}[7]::sub[0]",
"num_complex::{{impl}}[80]::add[0]",
"num_complex::{{impl}}[81]::sub[0]",
"num_complex::{{impl}}[82]::mul[0]",
"num_complex::{{impl}}[83]::div[0]",
"num_complex::{{impl}}[84]::rem[0]",
"num_complex::{{impl}}[85]::add[0]",
"num_complex::{{impl}}[86]::sub[0]",
"num_complex::{{impl}}[87]::mul[0]",
"num_complex::{{impl}}[88]::div[0]",
"num_complex::{{impl}}[89]::rem[0]",
"num_complex::{{impl}}[8]::mul[0]",
"num_complex::{{impl}}[90]::add[0]",
"num_complex::{{impl}}[91]::sub[0]",
"num_complex::{{impl}}[92]::mul[0]",
"num_complex::{{impl}}[93]::div[0]",
"num_complex::{{impl}}[94]::rem[0]",
"num_complex::{{impl}}[95]::add[0]",
"num_complex::{{impl}}[96]::sub[0]",
"num_complex::{{impl}}[97]::mul[0]",
"num_complex::{{impl}}[98]::div[0]",
"num_complex::{{impl}}[99]::rem[0]",
"num_complex::{{impl}}[9]::div[0]"
]
