CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"termcolor::WriteColor[0]::is_synchronous[0]",
"termcolor::{{impl}}[17]::is_synchronous[0]",
"termcolor::{{impl}}[17]::supports_color[0]",
"termcolor::{{impl}}[1]::is_synchronous[0]",
"termcolor::{{impl}}[1]::supports_color[0]",
"termcolor::{{impl}}[24]::get_mut[0]",
"termcolor::{{impl}}[24]::get_ref[0]",
"termcolor::{{impl}}[24]::into_inner[0]",
"termcolor::{{impl}}[24]::new[0]",
"termcolor::{{impl}}[26]::is_synchronous[0]",
"termcolor::{{impl}}[26]::supports_color[0]",
"termcolor::{{impl}}[27]::get_mut[0]",
"termcolor::{{impl}}[27]::get_ref[0]",
"termcolor::{{impl}}[27]::into_inner[0]",
"termcolor::{{impl}}[27]::new[0]",
"termcolor::{{impl}}[29]::is_synchronous[0]",
"termcolor::{{impl}}[29]::supports_color[0]",
"termcolor::{{impl}}[31]::bold[0]",
"termcolor::{{impl}}[31]::clear[0]",
"termcolor::{{impl}}[31]::intense[0]",
"termcolor::{{impl}}[31]::is_none[0]",
"termcolor::{{impl}}[31]::new[0]",
"termcolor::{{impl}}[31]::set_bg[0]",
"termcolor::{{impl}}[31]::set_bold[0]",
"termcolor::{{impl}}[31]::set_fg[0]",
"termcolor::{{impl}}[31]::set_intense[0]",
"termcolor::{{impl}}[31]::set_underline[0]",
"termcolor::{{impl}}[31]::underline[0]",
"termcolor::{{impl}}[37]::get_ref[0]",
"termcolor::{{impl}}[37]::new[0]",
"termcolor::{{impl}}[37]::wrap[0]",
"termcolor::{{impl}}[38]::is_synchronous[0]",
"termcolor::{{impl}}[38]::supports_color[0]",
"termcolor::{{impl}}[41]::assert_receiver_is_total_eq[0]",
"termcolor::{{impl}}[44]::clone[0]",
"termcolor::{{impl}}[45]::eq[0]",
"termcolor::{{impl}}[45]::ne[0]",
"termcolor::{{impl}}[46]::assert_receiver_is_total_eq[0]",
"termcolor::{{impl}}[47]::default[0]",
"termcolor::{{impl}}[49]::clone[0]",
"termcolor::{{impl}}[51]::assert_receiver_is_total_eq[0]",
"termcolor::{{impl}}[54]::clone[0]",
"termcolor::{{impl}}[60]::assert_receiver_is_total_eq[0]"
]
