CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"cookie::draft[0]::{{impl}}[0]::is_lax[0]",
"cookie::draft[0]::{{impl}}[0]::is_none[0]",
"cookie::draft[0]::{{impl}}[0]::is_strict[0]",
"cookie::draft[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"cookie::draft[0]::{{impl}}[6]::clone[0]",
"cookie::parse[0]::{{impl}}[2]::from[0]",
"cookie::parse[0]::{{impl}}[5]::clone[0]",
"cookie::parse[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]"
]
