CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crossbeam_deque::{{impl}}[17]::assert_receiver_is_total_eq[0]",
"crossbeam_deque::{{impl}}[24]::assert_receiver_is_total_eq[0]",
"crossbeam_deque::{{impl}}[28]::assert_receiver_is_total_eq[0]",
"crossbeam_deque::{{impl}}[31]::clone[0]"
]
