CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"same_file::unix[0]::{{impl}}[0]::drop[0]",
"same_file::unix[0]::{{impl}}[2]::eq[0]",
"same_file::unix[0]::{{impl}}[5]::hash[0]",
"same_file::unix[0]::{{impl}}[6]::dev[0]",
"same_file::unix[0]::{{impl}}[6]::ino[0]",
"same_file::{{impl}}[0]::as_file[0]",
"same_file::{{impl}}[0]::as_file_mut[0]",
"same_file::{{impl}}[0]::dev[0]",
"same_file::{{impl}}[0]::ino[0]",
"same_file::{{impl}}[1]::eq[0]",
"same_file::{{impl}}[1]::ne[0]",
"same_file::{{impl}}[2]::assert_receiver_is_total_eq[0]"
]
