CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"siphasher::sip128[0]::{{impl}}[0]::keys[0]",
"siphasher::sip128[0]::{{impl}}[0]::new[0]",
"siphasher::sip128[0]::{{impl}}[0]::new_with_keys[0]",
"siphasher::sip128[0]::{{impl}}[10]::finish[0]",
"siphasher::sip128[0]::{{impl}}[11]::finish[0]",
"siphasher::sip128[0]::{{impl}}[12]::clone[0]",
"siphasher::sip128[0]::{{impl}}[13]::default[0]",
"siphasher::sip128[0]::{{impl}}[17]::default[0]",
"siphasher::sip128[0]::{{impl}}[19]::clone[0]",
"siphasher::sip128[0]::{{impl}}[1]::finish128[0]",
"siphasher::sip128[0]::{{impl}}[21]::default[0]",
"siphasher::sip128[0]::{{impl}}[23]::clone[0]",
"siphasher::sip128[0]::{{impl}}[25]::default[0]",
"siphasher::sip128[0]::{{impl}}[27]::clone[0]",
"siphasher::sip128[0]::{{impl}}[29]::default[0]",
"siphasher::sip128[0]::{{impl}}[2]::keys[0]",
"siphasher::sip128[0]::{{impl}}[2]::new[0]",
"siphasher::sip128[0]::{{impl}}[2]::new_with_keys[0]",
"siphasher::sip128[0]::{{impl}}[31]::clone[0]",
"siphasher::sip128[0]::{{impl}}[36]::clone[0]",
"siphasher::sip128[0]::{{impl}}[38]::default[0]",
"siphasher::sip128[0]::{{impl}}[3]::finish128[0]",
"siphasher::sip128[0]::{{impl}}[40]::clone[0]",
"siphasher::sip128[0]::{{impl}}[42]::default[0]",
"siphasher::sip128[0]::{{impl}}[44]::clone[0]",
"siphasher::sip128[0]::{{impl}}[4]::keys[0]",
"siphasher::sip128[0]::{{impl}}[4]::new[0]",
"siphasher::sip128[0]::{{impl}}[4]::new_with_keys[0]",
"siphasher::sip128[0]::{{impl}}[5]::finish128[0]",
"siphasher::sip128[0]::{{impl}}[6]::new_with_keys[0]",
"siphasher::sip128[0]::{{impl}}[8]::finish[0]",
"siphasher::sip128[0]::{{impl}}[9]::finish[0]",
"siphasher::sip[0]::{{impl}}[0]::keys[0]",
"siphasher::sip[0]::{{impl}}[0]::new[0]",
"siphasher::sip[0]::{{impl}}[0]::new_with_keys[0]",
"siphasher::sip[0]::{{impl}}[11]::default[0]",
"siphasher::sip[0]::{{impl}}[13]::clone[0]",
"siphasher::sip[0]::{{impl}}[15]::default[0]",
"siphasher::sip[0]::{{impl}}[17]::clone[0]",
"siphasher::sip[0]::{{impl}}[19]::default[0]",
"siphasher::sip[0]::{{impl}}[1]::keys[0]",
"siphasher::sip[0]::{{impl}}[1]::new[0]",
"siphasher::sip[0]::{{impl}}[1]::new_with_keys[0]",
"siphasher::sip[0]::{{impl}}[21]::clone[0]",
"siphasher::sip[0]::{{impl}}[24]::clone[0]",
"siphasher::sip[0]::{{impl}}[27]::clone[0]",
"siphasher::sip[0]::{{impl}}[29]::default[0]",
"siphasher::sip[0]::{{impl}}[2]::keys[0]",
"siphasher::sip[0]::{{impl}}[2]::new[0]",
"siphasher::sip[0]::{{impl}}[2]::new_with_keys[0]",
"siphasher::sip[0]::{{impl}}[31]::clone[0]",
"siphasher::sip[0]::{{impl}}[33]::default[0]",
"siphasher::sip[0]::{{impl}}[35]::clone[0]",
"siphasher::sip[0]::{{impl}}[3]::new_with_keys[0]",
"siphasher::sip[0]::{{impl}}[4]::finish[0]",
"siphasher::sip[0]::{{impl}}[5]::finish[0]",
"siphasher::sip[0]::{{impl}}[6]::finish[0]",
"siphasher::sip[0]::{{impl}}[8]::default[0]"
]
