CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rayon_core::current_num_threads[0]",
"rayon_core::job[0]::{{impl}}[5]::new[0]",
"rayon_core::latch[0]::{{impl}}[0]::new[0]",
"rayon_core::latch[0]::{{impl}}[1]::probe[0]",
"rayon_core::latch[0]::{{impl}}[2]::set[0]",
"rayon_core::latch[0]::{{impl}}[6]::increment[0]",
"rayon_core::latch[0]::{{impl}}[6]::new[0]",
"rayon_core::latch[0]::{{impl}}[7]::probe[0]",
"rayon_core::latch[0]::{{impl}}[8]::set[0]",
"rayon_core::log[0]::{{impl}}[1]::deref[0]",
"rayon_core::log[0]::{{impl}}[2]::initialize[0]",
"rayon_core::registry[0]::{{impl}}[11]::clone[0]",
"rayon_core::registry[0]::{{impl}}[6]::cmp[0]",
"rayon_core::registry[0]::{{impl}}[7]::partial_cmp[0]",
"rayon_core::registry[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"rayon_core::registry[0]::{{impl}}[9]::eq[0]",
"rayon_core::registry[0]::{{impl}}[9]::ne[0]"
]
