CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"linked_hash_map::{{impl}}[60]::assert_receiver_is_total_eq[0]",
"linked_hash_map::{{impl}}[61]::eq[0]",
"linked_hash_map::{{impl}}[61]::ne[0]",
"linked_hash_map::{{impl}}[62]::hash[0]"
]
