CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_io::_assert_objects[0]::_assert[0]",
"tokio_io::allow_std[0]::{{impl}}[0]::get_mut[0]",
"tokio_io::allow_std[0]::{{impl}}[0]::get_ref[0]",
"tokio_io::allow_std[0]::{{impl}}[0]::into_inner[0]",
"tokio_io::allow_std[0]::{{impl}}[0]::new[0]",
"tokio_io::allow_std[0]::{{impl}}[10]::clone[0]",
"tokio_io::allow_std[0]::{{impl}}[5]::hash[0]",
"tokio_io::allow_std[0]::{{impl}}[6]::partial_cmp[0]",
"tokio_io::allow_std[0]::{{impl}}[7]::cmp[0]",
"tokio_io::allow_std[0]::{{impl}}[8]::eq[0]",
"tokio_io::allow_std[0]::{{impl}}[8]::ne[0]",
"tokio_io::allow_std[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[0]::new[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[3]::hash[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[4]::partial_cmp[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[5]::cmp[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[6]::eq[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[6]::ne[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_io::codec[0]::bytes_codec[0]::{{impl}}[9]::clone[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[0]::new[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[3]::hash[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[4]::partial_cmp[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[5]::cmp[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[6]::eq[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[6]::ne[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_io::codec[0]::lines_codec[0]::{{impl}}[9]::clone[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::big_endian[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::get_num_skip[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::length_adjustment[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::length_field_length[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::length_field_offset[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::little_endian[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::max_frame_length[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::native_endian[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::new[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::num_head_bytes[0]",
"tokio_io::length_delimited[0]::{{impl}}[21]::num_skip[0]",
"tokio_io::length_delimited[0]::{{impl}}[26]::clone[0]",
"tokio_io::length_delimited[0]::{{impl}}[31]::clone[0]",
"tokio_io::window[0]::{{impl}}[0]::end[0]",
"tokio_io::window[0]::{{impl}}[0]::get_mut[0]",
"tokio_io::window[0]::{{impl}}[0]::get_ref[0]",
"tokio_io::window[0]::{{impl}}[0]::into_inner[0]",
"tokio_io::window[0]::{{impl}}[0]::start[0]"
]
