CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"curl::easy[0]::handler[0]::Handler[0]::open_socket[0]::cvt[0]",
"curl::easy[0]::handler[0]::Handler[0]::seek[0]",
"curl::easy[0]::handler[0]::{{impl}}[19]::clone[0]",
"curl::easy[0]::handler[0]::{{impl}}[20]::clone[0]",
"curl::easy[0]::handler[0]::{{impl}}[5]::new[0]",
"curl::easy[0]::handler[0]::{{impl}}[7]::new[0]",
"curl::error[0]::{{impl}}[12]::code[0]",
"curl::error[0]::{{impl}}[12]::new[0]",
"curl::error[0]::{{impl}}[23]::eq[0]",
"curl::error[0]::{{impl}}[23]::ne[0]",
"curl::error[0]::{{impl}}[24]::clone[0]",
"curl::error[0]::{{impl}}[25]::eq[0]",
"curl::error[0]::{{impl}}[25]::ne[0]",
"curl::error[0]::{{impl}}[26]::clone[0]",
"curl::error[0]::{{impl}}[27]::eq[0]",
"curl::error[0]::{{impl}}[27]::ne[0]",
"curl::error[0]::{{impl}}[28]::clone[0]",
"curl::error[0]::{{impl}}[4]::code[0]",
"curl::error[0]::{{impl}}[4]::new[0]",
"curl::error[0]::{{impl}}[8]::code[0]",
"curl::error[0]::{{impl}}[8]::new[0]",
"curl::init[0]::platform_init[0]",
"curl::multi[0]::{{impl}}[13]::new[0]",
"curl::multi[0]::{{impl}}[13]::set_fd[0]",
"curl::multi[0]::{{impl}}[9]::new[0]"
]
