CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"parking_lot::condvar[0]::{{impl}}[0]::timed_out[0]",
"parking_lot::condvar[0]::{{impl}}[4]::clone[0]",
"parking_lot::condvar[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"parking_lot::condvar[0]::{{impl}}[7]::eq[0]",
"parking_lot::condvar[0]::{{impl}}[7]::ne[0]",
"parking_lot::elision[0]::have_elision[0]",
"parking_lot::once[0]::{{impl}}[0]::done[0]",
"parking_lot::once[0]::{{impl}}[0]::poisoned[0]",
"parking_lot::once[0]::{{impl}}[2]::default[0]",
"parking_lot::once[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"parking_lot::once[0]::{{impl}}[7]::clone[0]"
]
