CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"owning_ref::{{impl}}[8]::as_owner[0]",
"owning_ref::{{impl}}[8]::into_owner[0]"
]
