CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"parking_lot_core::parking_lot[0]::deadlock[0]::{{impl}}[0]::new[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[12]::eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[12]::ne[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[14]::clone[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[19]::clone[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[24]::clone[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[27]::eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[27]::ne[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[28]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[29]::clone[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[2]::new[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[2]::should_timeout[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[32]::eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[32]::ne[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[33]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[34]::clone[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[5]::is_unparked[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"parking_lot_core::parking_lot[0]::{{impl}}[9]::clone[0]",
"parking_lot_core::spinwait[0]::{{impl}}[0]::new[0]",
"parking_lot_core::spinwait[0]::{{impl}}[0]::reset[0]",
"parking_lot_core::spinwait[0]::{{impl}}[1]::default[0]",
"parking_lot_core::word_lock[0]::{{impl}}[1]::new[0]"
]
