CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fs2::{{impl}}[1]::allocation_granularity[0]",
"fs2::{{impl}}[1]::available_space[0]",
"fs2::{{impl}}[1]::free_space[0]",
"fs2::{{impl}}[1]::total_space[0]",
"fs2::{{impl}}[2]::hash[0]",
"fs2::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"fs2::{{impl}}[4]::eq[0]",
"fs2::{{impl}}[4]::ne[0]",
"fs2::{{impl}}[6]::clone[0]"
]
