CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"libgit2_sys::openssl_init[0]",
"libgit2_sys::ssh_init[0]",
"libgit2_sys::{{impl}}[10]::clone[0]",
"libgit2_sys::{{impl}}[20]::eq[0]",
"libgit2_sys::{{impl}}[20]::ne[0]",
"libgit2_sys::{{impl}}[21]::assert_receiver_is_total_eq[0]",
"libgit2_sys::{{impl}}[22]::clone[0]",
"libgit2_sys::{{impl}}[6]::eq[0]",
"libgit2_sys::{{impl}}[6]::ne[0]",
"libgit2_sys::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"libgit2_sys::{{impl}}[8]::clone[0]"
]
