CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"yaml_rust::emitter[0]::{{impl}}[2]::from[0]",
"yaml_rust::emitter[0]::{{impl}}[5]::clone[0]",
"yaml_rust::parser[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"yaml_rust::parser[0]::{{impl}}[7]::clone[0]",
"yaml_rust::scanner[0]::as_hex[0]",
"yaml_rust::scanner[0]::is_alpha[0]",
"yaml_rust::scanner[0]::is_blank[0]",
"yaml_rust::scanner[0]::is_blankz[0]",
"yaml_rust::scanner[0]::is_break[0]",
"yaml_rust::scanner[0]::is_breakz[0]",
"yaml_rust::scanner[0]::is_digit[0]",
"yaml_rust::scanner[0]::is_hex[0]",
"yaml_rust::scanner[0]::is_z[0]",
"yaml_rust::scanner[0]::{{impl}}[0]::col[0]",
"yaml_rust::scanner[0]::{{impl}}[0]::index[0]",
"yaml_rust::scanner[0]::{{impl}}[0]::line[0]",
"yaml_rust::scanner[0]::{{impl}}[0]::new[0]",
"yaml_rust::scanner[0]::{{impl}}[11]::clone[0]",
"yaml_rust::scanner[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"yaml_rust::scanner[0]::{{impl}}[16]::clone[0]",
"yaml_rust::scanner[0]::{{impl}}[17]::assert_receiver_is_total_eq[0]",
"yaml_rust::scanner[0]::{{impl}}[19]::eq[0]",
"yaml_rust::scanner[0]::{{impl}}[19]::ne[0]",
"yaml_rust::scanner[0]::{{impl}}[21]::clone[0]",
"yaml_rust::scanner[0]::{{impl}}[34]::assert_receiver_is_total_eq[0]",
"yaml_rust::scanner[0]::{{impl}}[36]::eq[0]",
"yaml_rust::scanner[0]::{{impl}}[36]::ne[0]",
"yaml_rust::scanner[0]::{{impl}}[37]::clone[0]",
"yaml_rust::scanner[0]::{{impl}}[4]::new[0]",
"yaml_rust::scanner[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]"
]
