CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"nom::internal[0]::{{impl}}[0]::map[0]",
"nom::internal[0]::{{impl}}[3]::convert[0]",
"nom::internal[0]::{{impl}}[4]::into_error_kind[0]",
"nom::internal[0]::{{impl}}[4]::is_incomplete[0]",
"nom::internal[0]::{{impl}}[6]::clone[0]",
"nom::internal[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"nom::nom[0]::be_i128[0]::_unify[0]",
"nom::nom[0]::be_i16[0]::_unify[0]",
"nom::nom[0]::be_i24[0]::_unify[0]",
"nom::nom[0]::be_i32[0]::_unify[0]",
"nom::nom[0]::be_i64[0]::_unify[0]",
"nom::nom[0]::be_i8[0]::_unify[0]",
"nom::nom[0]::is_alphabetic[0]",
"nom::nom[0]::is_alphanumeric[0]",
"nom::nom[0]::is_digit[0]",
"nom::nom[0]::is_hex_digit[0]",
"nom::nom[0]::is_oct_digit[0]",
"nom::nom[0]::is_space[0]",
"nom::nom[0]::le_i128[0]::_unify[0]",
"nom::nom[0]::le_i16[0]::_unify[0]",
"nom::nom[0]::le_i24[0]::_unify[0]",
"nom::nom[0]::le_i32[0]::_unify[0]",
"nom::nom[0]::le_i64[0]::_unify[0]",
"nom::nom[0]::le_i8[0]::_unify[0]",
"nom::nom[0]::{{impl}}[1]::clone[0]",
"nom::nom[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"nom::simple_errors[0]::{{impl}}[0]::convert[0]",
"nom::simple_errors[0]::{{impl}}[1]::into_error_kind[0]",
"nom::traits[0]::need_more[0]",
"nom::traits[0]::need_more_err[0]",
"nom::traits[0]::star[0]",
"nom::traits[0]::{{impl}}[11]::as_char[0]",
"nom::traits[0]::{{impl}}[11]::is_alpha[0]",
"nom::traits[0]::{{impl}}[11]::is_alphanum[0]",
"nom::traits[0]::{{impl}}[11]::is_dec_digit[0]",
"nom::traits[0]::{{impl}}[11]::is_hex_digit[0]",
"nom::traits[0]::{{impl}}[11]::is_oct_digit[0]",
"nom::traits[0]::{{impl}}[11]::len[0]",
"nom::traits[0]::{{impl}}[12]::as_char[0]",
"nom::traits[0]::{{impl}}[12]::is_alpha[0]",
"nom::traits[0]::{{impl}}[12]::is_alphanum[0]",
"nom::traits[0]::{{impl}}[12]::is_dec_digit[0]",
"nom::traits[0]::{{impl}}[12]::is_hex_digit[0]",
"nom::traits[0]::{{impl}}[12]::is_oct_digit[0]",
"nom::traits[0]::{{impl}}[12]::len[0]",
"nom::traits[0]::{{impl}}[13]::as_char[0]",
"nom::traits[0]::{{impl}}[13]::is_alpha[0]",
"nom::traits[0]::{{impl}}[13]::is_alphanum[0]",
"nom::traits[0]::{{impl}}[13]::is_dec_digit[0]",
"nom::traits[0]::{{impl}}[13]::is_hex_digit[0]",
"nom::traits[0]::{{impl}}[13]::is_oct_digit[0]",
"nom::traits[0]::{{impl}}[13]::len[0]",
"nom::traits[0]::{{impl}}[14]::as_char[0]",
"nom::traits[0]::{{impl}}[14]::is_alpha[0]",
"nom::traits[0]::{{impl}}[14]::is_alphanum[0]",
"nom::traits[0]::{{impl}}[14]::is_dec_digit[0]",
"nom::traits[0]::{{impl}}[14]::is_hex_digit[0]",
"nom::traits[0]::{{impl}}[14]::is_oct_digit[0]",
"nom::traits[0]::{{impl}}[14]::len[0]",
"nom::traits[0]::{{impl}}[19]::split_at_position1[0]",
"nom::traits[0]::{{impl}}[19]::split_at_position[0]",
"nom::traits[0]::{{impl}}[38]::at_eof[0]",
"nom::types[0]::{{impl}}[44]::at_eof[0]",
"nom::types[0]::{{impl}}[45]::slice[0]",
"nom::types[0]::{{impl}}[46]::slice[0]",
"nom::types[0]::{{impl}}[47]::slice[0]",
"nom::types[0]::{{impl}}[48]::slice[0]",
"nom::types[0]::{{impl}}[49]::position[0]",
"nom::types[0]::{{impl}}[49]::slice_index[0]",
"nom::types[0]::{{impl}}[50]::take[0]",
"nom::types[0]::{{impl}}[50]::take_split[0]",
"nom::types[0]::{{impl}}[51]::input_len[0]",
"nom::types[0]::{{impl}}[54]::find_token[0]",
"nom::types[0]::{{impl}}[55]::find_token[0]",
"nom::types[0]::{{impl}}[56]::find_token[0]",
"nom::types[0]::{{impl}}[57]::parse_to[0]",
"nom::types[0]::{{impl}}[58]::offset[0]",
"nom::types[0]::{{impl}}[72]::hash[0]",
"nom::types[0]::{{impl}}[73]::eq[0]",
"nom::types[0]::{{impl}}[73]::ne[0]",
"nom::types[0]::{{impl}}[76]::clone[0]",
"nom::util[0]::error_to_u32[0]",
"nom::util[0]::{{impl}}[2]::into_error_kind[0]",
"nom::util[0]::{{impl}}[3]::convert[0]",
"nom::util[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]"
]
