CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tar::archive[0]::{{impl}}[0]::into_inner[0]",
"tar::archive[0]::{{impl}}[0]::new[0]",
"tar::archive[0]::{{impl}}[0]::set_preserve_permissions[0]",
"tar::archive[0]::{{impl}}[0]::set_unpack_xattrs[0]",
"tar::builder[0]::{{impl}}[0]::follow_symlinks[0]",
"tar::builder[0]::{{impl}}[0]::mode[0]",
"tar::builder[0]::{{impl}}[0]::new[0]",
"tar::entry_type[0]::{{impl}}[0]::as_byte[0]",
"tar::entry_type[0]::{{impl}}[0]::block_special[0]",
"tar::entry_type[0]::{{impl}}[0]::character_special[0]",
"tar::entry_type[0]::{{impl}}[0]::contiguous[0]",
"tar::entry_type[0]::{{impl}}[0]::dir[0]",
"tar::entry_type[0]::{{impl}}[0]::fifo[0]",
"tar::entry_type[0]::{{impl}}[0]::file[0]",
"tar::entry_type[0]::{{impl}}[0]::hard_link[0]",
"tar::entry_type[0]::{{impl}}[0]::new[0]",
"tar::entry_type[0]::{{impl}}[0]::symlink[0]",
"tar::entry_type[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"tar::entry_type[0]::{{impl}}[5]::clone[0]",
"tar::header[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"tar::header[0]::{{impl}}[19]::clone[0]",
"tar::pax[0]::pax_extensions[0]::is_newline[0]",
"tar::{{impl}}[0]::deref[0]",
"tar::{{impl}}[1]::deref_mut[0]"
]
