CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"humantime::date[0]::format_rfc3339[0]",
"humantime::date[0]::format_rfc3339_nanos[0]",
"humantime::date[0]::format_rfc3339_seconds[0]",
"humantime::date[0]::is_leap_year[0]",
"humantime::date[0]::two_digits[0]",
"humantime::date[0]::{{impl}}[2]::clone[0]",
"humantime::date[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"humantime::duration[0]::format_duration[0]",
"humantime::duration[0]::{{impl}}[0]::add[0]",
"humantime::duration[0]::{{impl}}[0]::mul[0]",
"humantime::duration[0]::{{impl}}[4]::clone[0]",
"humantime::wrapper[0]::{{impl}}[0]::as_ref[0]",
"humantime::wrapper[0]::{{impl}}[13]::clone[0]",
"humantime::wrapper[0]::{{impl}}[14]::hash[0]",
"humantime::wrapper[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"humantime::wrapper[0]::{{impl}}[16]::eq[0]",
"humantime::wrapper[0]::{{impl}}[16]::ne[0]",
"humantime::wrapper[0]::{{impl}}[18]::clone[0]",
"humantime::wrapper[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"humantime::wrapper[0]::{{impl}}[1]::deref[0]",
"humantime::wrapper[0]::{{impl}}[20]::eq[0]",
"humantime::wrapper[0]::{{impl}}[20]::ne[0]",
"humantime::wrapper[0]::{{impl}}[2]::into[0]",
"humantime::wrapper[0]::{{impl}}[3]::from[0]",
"humantime::wrapper[0]::{{impl}}[6]::as_ref[0]",
"humantime::wrapper[0]::{{impl}}[7]::deref[0]",
"humantime::wrapper[0]::{{impl}}[8]::into[0]",
"humantime::wrapper[0]::{{impl}}[9]::from[0]"
]
