CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"syscall::data[0]::{{impl}}[11]::default[0]",
"syscall::data[0]::{{impl}}[13]::clone[0]",
"syscall::data[0]::{{impl}}[15]::default[0]",
"syscall::data[0]::{{impl}}[17]::clone[0]",
"syscall::data[0]::{{impl}}[22]::default[0]",
"syscall::data[0]::{{impl}}[24]::clone[0]",
"syscall::data[0]::{{impl}}[26]::default[0]",
"syscall::data[0]::{{impl}}[28]::clone[0]",
"syscall::data[0]::{{impl}}[30]::default[0]",
"syscall::data[0]::{{impl}}[32]::clone[0]",
"syscall::error[0]::{{impl}}[0]::new[0]",
"syscall::error[0]::{{impl}}[3]::eq[0]",
"syscall::error[0]::{{impl}}[3]::ne[0]",
"syscall::error[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"syscall::flag[0]::wifcontinued[0]",
"syscall::flag[0]::wifexited[0]",
"syscall::io[0]::io[0]::{{impl}}[0]::new[0]",
"syscall::io[0]::io[0]::{{impl}}[1]::new[0]",
"syscall::io[0]::pio[0]::{{impl}}[0]::new[0]",
"syscall::io[0]::pio[0]::{{impl}}[4]::clone[0]"
]
