CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"libssh2_sys::issue_14344_workaround[0]",
"libssh2_sys::{{impl}}[0]::clone[0]",
"libssh2_sys::{{impl}}[2]::clone[0]"
]
