CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"hpack::decoder[0]::{{impl}}[11]::clone[0]",
"hpack::decoder[0]::{{impl}}[3]::clone[0]",
"hpack::decoder[0]::{{impl}}[7]::clone[0]",
"hpack::huffman[0]::{{impl}}[5]::clone[0]"
]
