CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crypto::aes[0]::{{impl}}[1]::clone[0]",
"crypto::aessafe[0]::bit_slice_4x1_with_u16[0]",
"crypto::aessafe[0]::bit_slice_4x4_with_u16[0]",
"crypto::aessafe[0]::sub_word[0]",
"crypto::aessafe[0]::un_bit_slice_4x1_with_u16[0]",
"crypto::aessafe[0]::un_bit_slice_4x4_with_u16[0]",
"crypto::aessafe[0]::{{impl}}[0]::split[0]",
"crypto::aessafe[0]::{{impl}}[10]::add_round_key[0]",
"crypto::aessafe[0]::{{impl}}[10]::inv_mix_columns[0]",
"crypto::aessafe[0]::{{impl}}[10]::inv_shift_rows[0]",
"crypto::aessafe[0]::{{impl}}[10]::inv_sub_bytes[0]",
"crypto::aessafe[0]::{{impl}}[10]::mix_columns[0]",
"crypto::aessafe[0]::{{impl}}[10]::shift_rows[0]",
"crypto::aessafe[0]::{{impl}}[10]::sub_bytes[0]",
"crypto::aessafe[0]::{{impl}}[14]::default[0]",
"crypto::aessafe[0]::{{impl}}[15]::ror1[0]",
"crypto::aessafe[0]::{{impl}}[15]::ror2[0]",
"crypto::aessafe[0]::{{impl}}[15]::ror3[0]",
"crypto::aessafe[0]::{{impl}}[1]::change_basis_a2x[0]",
"crypto::aessafe[0]::{{impl}}[1]::change_basis_s2x[0]",
"crypto::aessafe[0]::{{impl}}[1]::change_basis_x2a[0]",
"crypto::aessafe[0]::{{impl}}[1]::change_basis_x2s[0]",
"crypto::aessafe[0]::{{impl}}[1]::xor[0]",
"crypto::aessafe[0]::{{impl}}[2]::xor_x63[0]",
"crypto::aessafe[0]::{{impl}}[3]::join[0]",
"crypto::aessafe[0]::{{impl}}[3]::split[0]",
"crypto::aessafe[0]::{{impl}}[4]::xor[0]",
"crypto::aessafe[0]::{{impl}}[5]::join[0]",
"crypto::aessafe[0]::{{impl}}[5]::split[0]",
"crypto::aessafe[0]::{{impl}}[65]::clone[0]",
"crypto::aessafe[0]::{{impl}}[67]::clone[0]",
"crypto::aessafe[0]::{{impl}}[69]::clone[0]",
"crypto::aessafe[0]::{{impl}}[6]::xor[0]",
"crypto::aessafe[0]::{{impl}}[7]::inv[0]",
"crypto::aessafe[0]::{{impl}}[7]::mul[0]",
"crypto::aessafe[0]::{{impl}}[7]::scl_n2[0]",
"crypto::aessafe[0]::{{impl}}[7]::scl_n[0]",
"crypto::aessafe[0]::{{impl}}[7]::sq[0]",
"crypto::aessafe[0]::{{impl}}[8]::inv[0]",
"crypto::aessafe[0]::{{impl}}[8]::mul[0]",
"crypto::aessafe[0]::{{impl}}[8]::sq_scl[0]",
"crypto::aessafe[0]::{{impl}}[9]::inv[0]",
"crypto::blockmodes[0]::{{impl}}[0]::fast_mode[0]::has_next[0]",
"crypto::blockmodes[0]::{{impl}}[28]::clone[0]",
"crypto::blockmodes[0]::{{impl}}[30]::clone[0]",
"crypto::blockmodes[0]::{{impl}}[32]::clone[0]",
"crypto::blockmodes[0]::{{impl}}[3]::wrap[0]",
"crypto::blockmodes[0]::{{impl}}[4]::pad_input[0]",
"crypto::blockmodes[0]::{{impl}}[5]::wrap[0]",
"crypto::blockmodes[0]::{{impl}}[6]::strip_output[0]",
"crypto::buffer[0]::ReadBuffer[0]::position[0]",
"crypto::buffer[0]::WriteBuffer[0]::position[0]",
"crypto::buffer[0]::{{impl}}[11]::clone[0]",
"crypto::chacha20[0]::{{impl}}[6]::clone[0]",
"crypto::cryptoutil[0]::add_bytes_to_bits_tuple[0]",
"crypto::digest[0]::Digest[0]::output_bytes[0]",
"crypto::ghash[0]::{{impl}}[0]::cond_xor[0]",
"crypto::ghash[0]::{{impl}}[0]::new[0]",
"crypto::ghash[0]::{{impl}}[1]::bitxor[0]",
"crypto::ghash[0]::{{impl}}[8]::clone[0]",
"crypto::md5[0]::{{impl}}[0]::new[0]",
"crypto::md5[0]::{{impl}}[0]::process_block[0]::op_f[0]",
"crypto::md5[0]::{{impl}}[0]::process_block[0]::op_g[0]",
"crypto::md5[0]::{{impl}}[0]::process_block[0]::op_h[0]",
"crypto::md5[0]::{{impl}}[0]::process_block[0]::op_i[0]",
"crypto::md5[0]::{{impl}}[0]::reset[0]",
"crypto::md5[0]::{{impl}}[4]::clone[0]",
"crypto::salsa20[0]::{{impl}}[6]::clone[0]",
"crypto::scrypt[0]::{{impl}}[2]::clone[0]",
"crypto::sha1[0]::sha1_first[0]",
"crypto::sha1[0]::sha1_first_add[0]",
"crypto::sha1[0]::sha1_first_half[0]",
"crypto::sha1[0]::sha1_schedule_x4[0]",
"crypto::sha1[0]::sha1msg1[0]",
"crypto::sha2[0]::sha256_schedule_x4[0]",
"crypto::sha2[0]::sha256load[0]",
"crypto::sha2[0]::sha256msg1[0]",
"crypto::sha2[0]::sha256msg1[0]::sigma0x4[0]",
"crypto::sha2[0]::sha256swap[0]",
"crypto::sha2[0]::sha512_schedule_x2[0]",
"crypto::sha2[0]::sha512load[0]",
"crypto::sha3[0]::{{impl}}[0]::capacity[0]",
"crypto::sha3[0]::{{impl}}[0]::digest_length[0]",
"crypto::sha3[0]::{{impl}}[0]::is_keccak[0]",
"crypto::sha3[0]::{{impl}}[0]::is_shake[0]",
"crypto::sha3[0]::{{impl}}[5]::clone[0]",
"crypto::simd[0]::fake[0]::{{impl}}[0]::add[0]",
"crypto::simd[0]::fake[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"crypto::simd[0]::fake[0]::{{impl}}[11]::eq[0]",
"crypto::simd[0]::fake[0]::{{impl}}[11]::ne[0]",
"crypto::simd[0]::fake[0]::{{impl}}[13]::clone[0]",
"crypto::simd[0]::fake[0]::{{impl}}[15]::clone[0]",
"crypto::simd[0]::fake[0]::{{impl}}[1]::sub[0]",
"crypto::simd[0]::fake[0]::{{impl}}[9]::add[0]",
"crypto::simd[0]::{{impl}}[0]::simd_eq[0]",
"crypto::step_by[0]::{{impl}}[0]::next[0]",
"crypto::step_by[0]::{{impl}}[1]::step_up[0]",
"crypto::step_by[0]::{{impl}}[2]::clone[0]",
"crypto::symmetriccipher[0]::{{impl}}[4]::clone[0]"
]
