CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"core_foundation::base[0]::TCFType[0]::instance_of[0]",
"core_foundation::base[0]::{{impl}}[6]::type_id[0]"
]
