CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"core_foundation_sys::base[0]::{{impl}}[0]::into[0]",
"core_foundation_sys::base[0]::{{impl}}[1]::init[0]",
"core_foundation_sys::base[0]::{{impl}}[5]::clone[0]",
"core_foundation_sys::base[0]::{{impl}}[7]::clone[0]",
"core_foundation_sys::uuid[0]::{{impl}}[0]::default[0]",
"core_foundation_sys::uuid[0]::{{impl}}[2]::clone[0]"
]
