CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"native_tls::_check_kinds[0]::is_send[0]",
"native_tls::_check_kinds[0]::is_sync[0]",
"native_tls::{{impl}}[21]::clone[0]"
]
