CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"pest::error[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"pest::error[0]::{{impl}}[20]::assert_receiver_is_total_eq[0]",
"pest::parser_state[0]::{{impl}}[10]::clone[0]",
"pest::parser_state[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"pest::parser_state[0]::{{impl}}[5]::clone[0]",
"pest::parser_state[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"pest::prec_climber[0]::{{impl}}[0]::new[0]",
"pest::prec_climber[0]::{{impl}}[1]::bitor[0]::assign_next[0]",
"pest::prec_climber[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"pest::prec_climber[0]::{{impl}}[7]::clone[0]"
]
