CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rand_core::error[0]::{{impl}}[5]::clone[0]",
"rand_core::error[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"rand_core::{{impl}}[1]::next_u32[0]",
"rand_core::{{impl}}[1]::next_u64[0]"
]
