CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"gl_generator::registry[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"gl_generator::registry[0]::{{impl}}[13]::clone[0]",
"gl_generator::registry[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"gl_generator::registry[0]::{{impl}}[18]::clone[0]",
"gl_generator::registry[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"gl_generator::registry[0]::{{impl}}[8]::clone[0]"
]
