CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"untrusted::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"untrusted::{{impl}}[13]::clone[0]",
"untrusted::{{impl}}[9]::eq[0]"
]
