CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ordermap::equivalent[0]::{{impl}}[0]::equivalent[0]",
"ordermap::map[0]::Size[0]::is_same_size[0]",
"ordermap::map[0]::to_raw_capacity[0]",
"ordermap::map[0]::usable_capacity[0]",
"ordermap::map[0]::{{impl}}[0]::into_hash[0]",
"ordermap::map[0]::{{impl}}[14]::is_64_bit[0]",
"ordermap::map[0]::{{impl}}[15]::is_64_bit[0]",
"ordermap::map[0]::{{impl}}[2]::clone[0]",
"ordermap::map[0]::{{impl}}[3]::eq[0]",
"ordermap::map[0]::{{impl}}[5]::from[0]",
"ordermap::map[0]::{{impl}}[6]::clone[0]",
"ordermap::map[0]::{{impl}}[9]::new[0]",
"ordermap::util[0]::third[0]",
"ordermap::{{impl}}[0]::get[0]",
"ordermap::{{impl}}[1]::clone[0]",
"ordermap::{{impl}}[2]::eq[0]",
"ordermap::{{impl}}[3]::key[0]",
"ordermap::{{impl}}[3]::key_ref[0]",
"ordermap::{{impl}}[3]::key_value[0]",
"ordermap::{{impl}}[3]::value_mut[0]",
"ordermap::{{impl}}[3]::value_ref[0]",
"ordermap::{{impl}}[7]::clone[0]"
]
