CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"memmap::{{impl}}[0]::len[0]",
"memmap::{{impl}}[0]::new[0]",
"memmap::{{impl}}[0]::offset[0]",
"memmap::{{impl}}[0]::stack[0]",
"memmap::{{impl}}[11]::default[0]",
"memmap::{{impl}}[13]::clone[0]"
]
