CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fuchsia_zircon_sys::{{impl}}[0]::default[0]",
"fuchsia_zircon_sys::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[11]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[14]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[14]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[16]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[29]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[29]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[30]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[31]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[34]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[34]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[35]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[36]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[39]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[39]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[40]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[41]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[44]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[44]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[45]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[46]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[50]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[51]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[54]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[6]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[74]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[75]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[82]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[82]::ne[0]",
"fuchsia_zircon_sys::{{impl}}[83]::assert_receiver_is_total_eq[0]",
"fuchsia_zircon_sys::{{impl}}[84]::clone[0]",
"fuchsia_zircon_sys::{{impl}}[9]::eq[0]",
"fuchsia_zircon_sys::{{impl}}[9]::ne[0]"
]
