CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_reactor::_assert_kinds[0]::_assert[0]",
"tokio_reactor::platform[0]::hup[0]",
"tokio_reactor::platform[0]::is_hup[0]",
"tokio_reactor::{{impl}}[11]::mask[0]",
"tokio_reactor::{{impl}}[18]::clone[0]",
"tokio_reactor::{{impl}}[20]::clone[0]",
"tokio_reactor::{{impl}}[22]::assert_receiver_is_total_eq[0]"
]
