CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_threadpool::notifier[0]::{{impl}}[1]::new[0]",
"tokio_threadpool::notifier[0]::{{impl}}[3]::drop[0]",
"tokio_threadpool::park[0]::boxed[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[12]::eq[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[12]::ne[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[15]::clone[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[1]::new[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[3]::from[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[6]::clone[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[8]::eq[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[8]::ne[0]",
"tokio_threadpool::pool[0]::backup[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[3]::from[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[6]::clone[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[7]::eq[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[7]::ne[0]",
"tokio_threadpool::pool[0]::backup_stack[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[11]::clone[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[1]::from[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[7]::clone[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[8]::eq[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[8]::ne[0]",
"tokio_threadpool::pool[0]::state[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[11]::eq[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[11]::ne[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[13]::clone[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[3]::from[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::task[0]::blocking[0]::{{impl}}[9]::clone[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[1]::from[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[4]::eq[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[4]::ne[0]",
"tokio_threadpool::task[0]::blocking_state[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::task[0]::state[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::task[0]::state[0]::{{impl}}[0]::stub[0]",
"tokio_threadpool::task[0]::state[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::task[0]::state[0]::{{impl}}[6]::clone[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[0]::new[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[3]::from[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[7]::clone[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[8]::eq[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[8]::ne[0]",
"tokio_threadpool::worker[0]::stack[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[0]::is_notified[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[10]::clone[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[12]::clone[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[2]::from[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[3]::from[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[7]::eq[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[7]::ne[0]",
"tokio_threadpool::worker[0]::state[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::worker[0]::{{impl}}[3]::new[0]",
"tokio_threadpool::worker[0]::{{impl}}[6]::eq[0]",
"tokio_threadpool::worker[0]::{{impl}}[6]::ne[0]",
"tokio_threadpool::worker[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_threadpool::worker[0]::{{impl}}[8]::hash[0]",
"tokio_threadpool::worker[0]::{{impl}}[9]::clone[0]"
]
