CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"sha1::sha1_first[0]",
"sha1::sha1_first_add[0]",
"sha1::sha1_first_half[0]",
"sha1::sha1msg1[0]",
"sha1::simd[0]::fake[0]::{{impl}}[0]::add[0]",
"sha1::simd[0]::fake[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"sha1::simd[0]::fake[0]::{{impl}}[11]::eq[0]",
"sha1::simd[0]::fake[0]::{{impl}}[11]::ne[0]",
"sha1::simd[0]::fake[0]::{{impl}}[13]::clone[0]",
"sha1::simd[0]::fake[0]::{{impl}}[15]::clone[0]",
"sha1::simd[0]::fake[0]::{{impl}}[1]::sub[0]",
"sha1::simd[0]::fake[0]::{{impl}}[9]::add[0]",
"sha1::simd[0]::{{impl}}[0]::simd_eq[0]",
"sha1::{{impl}}[38]::partial_cmp[0]",
"sha1::{{impl}}[39]::cmp[0]",
"sha1::{{impl}}[40]::eq[0]",
"sha1::{{impl}}[40]::ne[0]",
"sha1::{{impl}}[41]::assert_receiver_is_total_eq[0]",
"sha1::{{impl}}[42]::hash[0]",
"sha1::{{impl}}[43]::clone[0]"
]
