CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_executor::Executor[0]::status[0]",
"tokio_executor::enter[0]::ENTERED[0]::__init[0]",
"tokio_executor::enter[0]::{{impl}}[6]::call[0]",
"tokio_executor::global[0]::{{impl}}[0]::current[0]",
"tokio_executor::global[0]::{{impl}}[3]::clone[0]",
"tokio_executor::{{impl}}[0]::status[0]",
"tokio_executor::{{impl}}[1]::at_capacity[0]",
"tokio_executor::{{impl}}[1]::is_at_capacity[0]",
"tokio_executor::{{impl}}[1]::is_shutdown[0]",
"tokio_executor::{{impl}}[1]::shutdown[0]"
]
