CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"generic_array::{{impl}}[1]::clone[0]",
"generic_array::{{impl}}[3]::clone[0]"
]
