CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fixedbitset::div_rem[0]",
"fixedbitset::range[0]::IndexRange[0]::end[0]",
"fixedbitset::range[0]::IndexRange[0]::start[0]",
"fixedbitset::range[0]::{{impl}}[1]::start[0]",
"fixedbitset::range[0]::{{impl}}[2]::end[0]",
"fixedbitset::range[0]::{{impl}}[3]::end[0]",
"fixedbitset::range[0]::{{impl}}[3]::start[0]"
]
