CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"quine_mc_cluskey::{{impl}}[11]::new[0]",
"quine_mc_cluskey::{{impl}}[11]::with_dontcare[0]",
"quine_mc_cluskey::{{impl}}[15]::cmp[0]",
"quine_mc_cluskey::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"quine_mc_cluskey::{{impl}}[17]::clone[0]",
"quine_mc_cluskey::{{impl}}[19]::assert_receiver_is_total_eq[0]"
]
