CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"termion::clear[0]::{{impl}}[10]::clone[0]",
"termion::clear[0]::{{impl}}[13]::clone[0]",
"termion::clear[0]::{{impl}}[1]::clone[0]",
"termion::clear[0]::{{impl}}[4]::clone[0]",
"termion::clear[0]::{{impl}}[7]::clone[0]",
"termion::color[0]::{{impl}}[10]::clone[0]",
"termion::color[0]::{{impl}}[14]::clone[0]",
"termion::color[0]::{{impl}}[18]::clone[0]",
"termion::color[0]::{{impl}}[22]::clone[0]",
"termion::color[0]::{{impl}}[26]::clone[0]",
"termion::color[0]::{{impl}}[30]::clone[0]",
"termion::color[0]::{{impl}}[34]::clone[0]",
"termion::color[0]::{{impl}}[38]::clone[0]",
"termion::color[0]::{{impl}}[42]::clone[0]",
"termion::color[0]::{{impl}}[46]::clone[0]",
"termion::color[0]::{{impl}}[50]::clone[0]",
"termion::color[0]::{{impl}}[54]::clone[0]",
"termion::color[0]::{{impl}}[58]::clone[0]",
"termion::color[0]::{{impl}}[62]::clone[0]",
"termion::color[0]::{{impl}}[66]::clone[0]",
"termion::color[0]::{{impl}}[70]::clone[0]",
"termion::color[0]::{{impl}}[74]::clone[0]",
"termion::color[0]::{{impl}}[75]::eq[0]",
"termion::color[0]::{{impl}}[75]::ne[0]",
"termion::color[0]::{{impl}}[77]::clone[0]",
"termion::color[0]::{{impl}}[80]::clone[0]",
"termion::color[0]::{{impl}}[83]::clone[0]",
"termion::color[0]::{{impl}}[86]::clone[0]",
"termion::cursor[0]::{{impl}}[0]::default[0]",
"termion::cursor[0]::{{impl}}[11]::clone[0]",
"termion::cursor[0]::{{impl}}[14]::clone[0]",
"termion::cursor[0]::{{impl}}[17]::clone[0]",
"termion::cursor[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"termion::cursor[0]::{{impl}}[20]::eq[0]",
"termion::cursor[0]::{{impl}}[20]::ne[0]",
"termion::cursor[0]::{{impl}}[21]::clone[0]",
"termion::cursor[0]::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"termion::cursor[0]::{{impl}}[24]::eq[0]",
"termion::cursor[0]::{{impl}}[24]::ne[0]",
"termion::cursor[0]::{{impl}}[25]::clone[0]",
"termion::cursor[0]::{{impl}}[27]::assert_receiver_is_total_eq[0]",
"termion::cursor[0]::{{impl}}[28]::eq[0]",
"termion::cursor[0]::{{impl}}[28]::ne[0]",
"termion::cursor[0]::{{impl}}[29]::clone[0]",
"termion::cursor[0]::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"termion::cursor[0]::{{impl}}[32]::eq[0]",
"termion::cursor[0]::{{impl}}[32]::ne[0]",
"termion::cursor[0]::{{impl}}[33]::clone[0]",
"termion::cursor[0]::{{impl}}[35]::assert_receiver_is_total_eq[0]",
"termion::cursor[0]::{{impl}}[36]::eq[0]",
"termion::cursor[0]::{{impl}}[36]::ne[0]",
"termion::cursor[0]::{{impl}}[37]::clone[0]",
"termion::cursor[0]::{{impl}}[8]::clone[0]",
"termion::event[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"termion::event[0]::{{impl}}[14]::clone[0]",
"termion::event[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"termion::event[0]::{{impl}}[20]::clone[0]",
"termion::event[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"termion::event[0]::{{impl}}[8]::clone[0]",
"termion::input[0]::{{impl}}[3]::events[0]",
"termion::input[0]::{{impl}}[3]::keys[0]",
"termion::input[0]::{{impl}}[4]::events_and_raw[0]",
"termion::input[0]::{{impl}}[7]::deref[0]",
"termion::input[0]::{{impl}}[8]::deref_mut[0]",
"termion::screen[0]::{{impl}}[4]::deref[0]",
"termion::screen[0]::{{impl}}[5]::deref_mut[0]",
"termion::scroll[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"termion::scroll[0]::{{impl}}[3]::eq[0]",
"termion::scroll[0]::{{impl}}[3]::ne[0]",
"termion::scroll[0]::{{impl}}[4]::clone[0]",
"termion::scroll[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"termion::scroll[0]::{{impl}}[7]::eq[0]",
"termion::scroll[0]::{{impl}}[7]::ne[0]",
"termion::scroll[0]::{{impl}}[8]::clone[0]",
"termion::style[0]::{{impl}}[10]::clone[0]",
"termion::style[0]::{{impl}}[13]::clone[0]",
"termion::style[0]::{{impl}}[16]::clone[0]",
"termion::style[0]::{{impl}}[19]::clone[0]",
"termion::style[0]::{{impl}}[1]::clone[0]",
"termion::style[0]::{{impl}}[22]::clone[0]",
"termion::style[0]::{{impl}}[25]::clone[0]",
"termion::style[0]::{{impl}}[28]::clone[0]",
"termion::style[0]::{{impl}}[31]::clone[0]",
"termion::style[0]::{{impl}}[34]::clone[0]",
"termion::style[0]::{{impl}}[37]::clone[0]",
"termion::style[0]::{{impl}}[40]::clone[0]",
"termion::style[0]::{{impl}}[43]::clone[0]",
"termion::style[0]::{{impl}}[46]::clone[0]",
"termion::style[0]::{{impl}}[4]::clone[0]",
"termion::style[0]::{{impl}}[7]::clone[0]",
"termion::sys[0]::{{impl}}[0]::is_minus_one[0]",
"termion::sys[0]::{{impl}}[1]::is_minus_one[0]",
"termion::sys[0]::{{impl}}[2]::is_minus_one[0]",
"termion::sys[0]::{{impl}}[3]::is_minus_one[0]",
"termion::sys[0]::{{impl}}[4]::is_minus_one[0]"
]
