CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"png::common[0]::{{impl}}[0]::from_u8[0]",
"png::common[0]::{{impl}}[0]::samples[0]",
"png::common[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"png::common[0]::{{impl}}[13]::clone[0]",
"png::common[0]::{{impl}}[17]::clone[0]",
"png::common[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"png::common[0]::{{impl}}[1]::from_u8[0]",
"png::common[0]::{{impl}}[21]::clone[0]",
"png::common[0]::{{impl}}[26]::clone[0]",
"png::common[0]::{{impl}}[28]::hash[0]",
"png::common[0]::{{impl}}[29]::cmp[0]",
"png::common[0]::{{impl}}[2]::from_u8[0]",
"png::common[0]::{{impl}}[30]::partial_cmp[0]",
"png::common[0]::{{impl}}[31]::clone[0]",
"png::common[0]::{{impl}}[32]::assert_receiver_is_total_eq[0]",
"png::common[0]::{{impl}}[33]::eq[0]",
"png::common[0]::{{impl}}[33]::ne[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::BGR[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::EXPAND[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::EXPAND_16[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::GRAY_TO_RGB[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::IDENTITY[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::INVERT_ALPHA[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::INVERT_MONO[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::PACKING[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::PACKSWAP[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::SCALE_16[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::SHIFT[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::STRIP_16[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::STRIP_ALPHA[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::STRIP_FILLER[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::STRIP_FILLER_AFTER[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::STRIP_FILLER_BEFORE[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::SWAP_ALPHA[0]",
"png::common[0]::{{impl}}[35]::fmt[0]::__BitFlags[0]::SWAP_ENDIAN[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::BGR[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::EXPAND[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::EXPAND_16[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::GRAY_TO_RGB[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::IDENTITY[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::INVERT_ALPHA[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::INVERT_MONO[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::PACKING[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::PACKSWAP[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::SCALE_16[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::SHIFT[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::STRIP_16[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::STRIP_ALPHA[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::STRIP_FILLER[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::STRIP_FILLER_AFTER[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::STRIP_FILLER_BEFORE[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::SWAP_ALPHA[0]",
"png::common[0]::{{impl}}[40]::all[0]::__BitFlags[0]::SWAP_ENDIAN[0]",
"png::common[0]::{{impl}}[40]::bits[0]",
"png::common[0]::{{impl}}[40]::contains[0]",
"png::common[0]::{{impl}}[40]::empty[0]",
"png::common[0]::{{impl}}[40]::from_bits_truncate[0]",
"png::common[0]::{{impl}}[40]::intersects[0]",
"png::common[0]::{{impl}}[40]::is_all[0]",
"png::common[0]::{{impl}}[40]::is_empty[0]",
"png::common[0]::{{impl}}[40]::set[0]",
"png::common[0]::{{impl}}[51]::from_iter[0]",
"png::common[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"png::common[0]::{{impl}}[8]::clone[0]",
"png::crc[0]::{{impl}}[0]::new[0]",
"png::crc[0]::{{impl}}[0]::reset[0]",
"png::decoder[0]::{{impl}}[0]::set_param[0]",
"png::decoder[0]::{{impl}}[3]::new[0]",
"png::decoder[0]::{{impl}}[3]::set_limits[0]",
"png::decoder[0]::{{impl}}[9]::clone[0]",
"png::filter[0]::{{impl}}[0]::from_u8[0]",
"png::filter[0]::{{impl}}[1]::assert_receiver_is_total_eq[0]",
"png::filter[0]::{{impl}}[4]::clone[0]",
"png::traits[0]::HasParameters[0]::set[0]",
"png::utils[0]::{{impl}}[0]::current_pass[0]",
"png::utils[0]::{{impl}}[0]::new[0]",
"png::utils[0]::{{impl}}[1]::next[0]",
"png::utils[0]::{{impl}}[2]::clone[0]"
]
