CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"bit_vec::BitBlock[0]::bytes[0]",
"bit_vec::blocks_for_bits[0]",
"bit_vec::mask_for_bits[0]",
"bit_vec::{{impl}}[24]::bits[0]",
"bit_vec::{{impl}}[24]::from_byte[0]",
"bit_vec::{{impl}}[24]::one[0]",
"bit_vec::{{impl}}[24]::zero[0]",
"bit_vec::{{impl}}[25]::bits[0]",
"bit_vec::{{impl}}[25]::from_byte[0]",
"bit_vec::{{impl}}[25]::one[0]",
"bit_vec::{{impl}}[25]::zero[0]",
"bit_vec::{{impl}}[26]::bits[0]",
"bit_vec::{{impl}}[26]::from_byte[0]",
"bit_vec::{{impl}}[26]::one[0]",
"bit_vec::{{impl}}[26]::zero[0]",
"bit_vec::{{impl}}[27]::bits[0]",
"bit_vec::{{impl}}[27]::from_byte[0]",
"bit_vec::{{impl}}[27]::one[0]",
"bit_vec::{{impl}}[27]::zero[0]",
"bit_vec::{{impl}}[28]::bits[0]",
"bit_vec::{{impl}}[28]::one[0]",
"bit_vec::{{impl}}[28]::zero[0]"
]
