CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ring::aead[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"ring::arithmetic[0]::montgomery[0]::{{impl}}[16]::clone[0]",
"ring::arithmetic[0]::montgomery[0]::{{impl}}[18]::clone[0]",
"ring::arithmetic[0]::montgomery[0]::{{impl}}[20]::clone[0]",
"ring::arithmetic[0]::montgomery[0]::{{impl}}[22]::clone[0]",
"ring::arithmetic[0]::montgomery[0]::{{impl}}[24]::clone[0]",
"ring::bits[0]::{{impl}}[0]::as_usize_bits[0]",
"ring::bits[0]::{{impl}}[0]::from_usize_bits[0]",
"ring::bits[0]::{{impl}}[0]::from_usize_bytes[0]",
"ring::bits[0]::{{impl}}[0]::try_sub[0]",
"ring::bits[0]::{{impl}}[1]::partial_cmp[0]",
"ring::bits[0]::{{impl}}[2]::eq[0]",
"ring::bits[0]::{{impl}}[2]::ne[0]",
"ring::bits[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"ring::bits[0]::{{impl}}[6]::clone[0]",
"ring::bssl[0]::map_result[0]",
"ring::der[0]::{{impl}}[2]::clone[0]",
"ring::digest[0]::sha1[0]::ch[0]",
"ring::digest[0]::sha1[0]::maj[0]",
"ring::digest[0]::sha1[0]::parity[0]",
"ring::digest[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"ring::ec[0]::suite_b[0]::ecdsa[0]::signing[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"ring::ec[0]::suite_b[0]::ops[0]::{{impl}}[7]::clone[0]",
"ring::ec[0]::suite_b[0]::ops[0]::{{impl}}[9]::clone[0]",
"ring::ec[0]::{{impl}}[8]::clone[0]",
"ring::error[0]::{{impl}}[3]::eq[0]",
"ring::error[0]::{{impl}}[6]::clone[0]",
"ring::limb[0]::{{impl}}[4]::clone[0]",
"ring::polyfill[0]::ref_from_mut_ref[0]",
"ring::polyfill[0]::wrapping_rotate_left_u32[0]",
"ring::rand[0]::sysrand_or_urandom[0]::fill[0]::{{impl}}[0]::deref[0]",
"ring::rand[0]::sysrand_or_urandom[0]::fill[0]::{{impl}}[1]::initialize[0]",
"ring::rand[0]::{{impl}}[0]::new[0]",
"ring::rsa[0]::bigint[0]::{{impl}}[17]::clone[0]",
"ring::rsa[0]::{{impl}}[0]::clone[0]",
"ring::test[0]::compile_time_assert_clone[0]",
"ring::test[0]::compile_time_assert_copy[0]",
"ring::test[0]::compile_time_assert_debug[0]",
"ring::test[0]::compile_time_assert_send[0]",
"ring::test[0]::compile_time_assert_sync[0]"
]
