CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"libloading::util[0]::ensure_compatible_types[0]",
"libloading::util[0]::ensure_compatible_types[0]::dopanic[0]"
]
