CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"redox_termios::{{impl}}[12]::clone[0]",
"redox_termios::{{impl}}[9]::default[0]"
]
