CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rls_data::{{impl}}[102]::clone[0]",
"rls_data::{{impl}}[10]::clone[0]",
"rls_data::{{impl}}[40]::assert_receiver_is_total_eq[0]",
"rls_data::{{impl}}[43]::clone[0]",
"rls_data::{{impl}}[51]::assert_receiver_is_total_eq[0]",
"rls_data::{{impl}}[54]::clone[0]",
"rls_data::{{impl}}[5]::hash[0]",
"rls_data::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"rls_data::{{impl}}[76]::assert_receiver_is_total_eq[0]",
"rls_data::{{impl}}[79]::clone[0]",
"rls_data::{{impl}}[7]::eq[0]",
"rls_data::{{impl}}[7]::ne[0]",
"rls_data::{{impl}}[91]::assert_receiver_is_total_eq[0]",
"rls_data::{{impl}}[94]::clone[0]"
]
