CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"inflate::checksum[0]::{{impl}}[0]::current_value[0]",
"inflate::checksum[0]::{{impl}}[0]::is_none[0]",
"inflate::checksum[0]::{{impl}}[0]::new[0]",
"inflate::checksum[0]::{{impl}}[0]::none[0]",
"inflate::checksum[0]::{{impl}}[0]::zlib[0]",
"inflate::{{impl}}[5]::clone[0]"
]
