CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"gif::common[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"gif::common[0]::{{impl}}[12]::clone[0]",
"gif::common[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"gif::common[0]::{{impl}}[17]::clone[0]",
"gif::common[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"gif::common[0]::{{impl}}[7]::clone[0]",
"gif::encoder[0]::flag_size[0]"
]
