CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tendril::fmt[0]::wtf8_meaningful[0]",
"tendril::fmt[0]::{{impl}}[16]::default[0]",
"tendril::fmt[0]::{{impl}}[17]::clone[0]",
"tendril::fmt[0]::{{impl}}[20]::default[0]",
"tendril::fmt[0]::{{impl}}[21]::clone[0]",
"tendril::fmt[0]::{{impl}}[24]::default[0]",
"tendril::fmt[0]::{{impl}}[25]::clone[0]",
"tendril::fmt[0]::{{impl}}[28]::default[0]",
"tendril::fmt[0]::{{impl}}[29]::clone[0]",
"tendril::fmt[0]::{{impl}}[32]::default[0]",
"tendril::fmt[0]::{{impl}}[33]::clone[0]",
"tendril::tendril[0]::{{impl}}[0]::decrement[0]",
"tendril::tendril[0]::{{impl}}[0]::fence_acquire[0]",
"tendril::tendril[0]::{{impl}}[0]::new[0]",
"tendril::tendril[0]::{{impl}}[1]::decrement[0]",
"tendril::tendril[0]::{{impl}}[1]::fence_acquire[0]",
"tendril::tendril[0]::{{impl}}[1]::increment[0]",
"tendril::tendril[0]::{{impl}}[1]::new[0]",
"tendril::tendril[0]::{{impl}}[48]::assert_receiver_is_total_eq[0]",
"tendril::tendril[0]::{{impl}}[52]::clone[0]"
]
