CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"futf::{{impl}}[17]::assert_receiver_is_total_eq[0]",
"futf::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"futf::{{impl}}[7]::clone[0]"
]
