CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"modifier::Set[0]::set_mut[0]",
"modifier::impls[0]::{{impl}}[0]::modify[0]",
"modifier::impls[0]::{{impl}}[1]::modify[0]",
"modifier::impls[0]::{{impl}}[2]::modify[0]",
"modifier::impls[0]::{{impl}}[3]::modify[0]",
"modifier::impls[0]::{{impl}}[4]::modify[0]",
"modifier::impls[0]::{{impl}}[5]::modify[0]"
]
