CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"bit_set::blocks_for_bits[0]",
"bit_set::{{impl}}[13]::size_hint[0]",
"bit_set::{{impl}}[21]::clone[0]",
"bit_set::{{impl}}[9]::difference[0]::diff[0]",
"bit_set::{{impl}}[9]::intersection[0]::bitand[0]",
"bit_set::{{impl}}[9]::symmetric_difference[0]::bitxor[0]",
"bit_set::{{impl}}[9]::union[0]::or[0]"
]
