CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rls_span::{{impl}}[0]::new[0]",
"rls_span::{{impl}}[10]::new[0]",
"rls_span::{{impl}}[11]::clone[0]",
"rls_span::{{impl}}[13]::zero_indexed[0]",
"rls_span::{{impl}}[14]::one_indexed[0]",
"rls_span::{{impl}}[15]::end[0]",
"rls_span::{{impl}}[15]::from_positions[0]",
"rls_span::{{impl}}[15]::new[0]",
"rls_span::{{impl}}[15]::start[0]",
"rls_span::{{impl}}[16]::clone[0]",
"rls_span::{{impl}}[18]::zero_indexed[0]",
"rls_span::{{impl}}[19]::one_indexed[0]",
"rls_span::{{impl}}[1]::clone[0]",
"rls_span::{{impl}}[30]::cmp[0]",
"rls_span::{{impl}}[31]::partial_cmp[0]",
"rls_span::{{impl}}[32]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[33]::eq[0]",
"rls_span::{{impl}}[33]::ne[0]",
"rls_span::{{impl}}[34]::hash[0]",
"rls_span::{{impl}}[36]::cmp[0]",
"rls_span::{{impl}}[37]::partial_cmp[0]",
"rls_span::{{impl}}[38]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[39]::eq[0]",
"rls_span::{{impl}}[39]::ne[0]",
"rls_span::{{impl}}[3]::new_one_indexed[0]",
"rls_span::{{impl}}[3]::zero_indexed[0]",
"rls_span::{{impl}}[40]::hash[0]",
"rls_span::{{impl}}[42]::cmp[0]",
"rls_span::{{impl}}[43]::partial_cmp[0]",
"rls_span::{{impl}}[44]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[45]::eq[0]",
"rls_span::{{impl}}[45]::ne[0]",
"rls_span::{{impl}}[46]::hash[0]",
"rls_span::{{impl}}[48]::cmp[0]",
"rls_span::{{impl}}[49]::partial_cmp[0]",
"rls_span::{{impl}}[4]::new_zero_indexed[0]",
"rls_span::{{impl}}[4]::one_indexed[0]",
"rls_span::{{impl}}[50]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[51]::eq[0]",
"rls_span::{{impl}}[51]::ne[0]",
"rls_span::{{impl}}[52]::hash[0]",
"rls_span::{{impl}}[5]::new[0]",
"rls_span::{{impl}}[66]::cmp[0]",
"rls_span::{{impl}}[67]::partial_cmp[0]",
"rls_span::{{impl}}[69]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[6]::clone[0]",
"rls_span::{{impl}}[70]::eq[0]",
"rls_span::{{impl}}[71]::hash[0]",
"rls_span::{{impl}}[72]::cmp[0]",
"rls_span::{{impl}}[73]::partial_cmp[0]",
"rls_span::{{impl}}[75]::assert_receiver_is_total_eq[0]",
"rls_span::{{impl}}[76]::eq[0]",
"rls_span::{{impl}}[77]::hash[0]",
"rls_span::{{impl}}[8]::new_one_indexed[0]",
"rls_span::{{impl}}[8]::zero_indexed[0]",
"rls_span::{{impl}}[9]::new_zero_indexed[0]",
"rls_span::{{impl}}[9]::one_indexed[0]"
]
