CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"lzw::bitstream[0]::{{impl}}[10]::new[0]",
"lzw::bitstream[0]::{{impl}}[4]::new[0]",
"lzw::bitstream[0]::{{impl}}[5]::new[0]",
"lzw::bitstream[0]::{{impl}}[8]::new[0]",
"lzw::lzw[0]::{{impl}}[1]::new[0]"
]
