CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"digest::digest[0]::{{impl}}[0]::chain[0]",
"digest::digest[0]::{{impl}}[0]::input[0]",
"digest::digest[0]::{{impl}}[0]::new[0]",
"digest::digest[0]::{{impl}}[0]::reset[0]",
"digest::errors[0]::{{impl}}[1]::default[0]",
"digest::errors[0]::{{impl}}[4]::clone[0]"
]
