CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_fs::create_dir[0]::create_dir[0]",
"tokio_fs::create_dir[0]::{{impl}}[0]::new[0]",
"tokio_fs::create_dir_all[0]::create_dir_all[0]",
"tokio_fs::create_dir_all[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::create[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::metadata[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::open[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::append[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::create[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::create_new[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::open[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::read[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::truncate[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[0]::write[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[1]::from[0]",
"tokio_fs::file[0]::open_options[0]::{{impl}}[3]::clone[0]",
"tokio_fs::file[0]::seek[0]::{{impl}}[0]::new[0]",
"tokio_fs::file[0]::{{impl}}[0]::create[0]",
"tokio_fs::file[0]::{{impl}}[0]::from_std[0]",
"tokio_fs::file[0]::{{impl}}[0]::metadata[0]",
"tokio_fs::file[0]::{{impl}}[0]::open[0]",
"tokio_fs::file[0]::{{impl}}[0]::seek[0]",
"tokio_fs::file[0]::{{impl}}[5]::drop[0]",
"tokio_fs::hard_link[0]::hard_link[0]",
"tokio_fs::hard_link[0]::{{impl}}[0]::new[0]",
"tokio_fs::metadata[0]::{{impl}}[0]::new[0]",
"tokio_fs::os[0]::unix[0]::symlink[0]",
"tokio_fs::os[0]::unix[0]::{{impl}}[0]::new[0]",
"tokio_fs::read_dir[0]::{{impl}}[0]::new[0]",
"tokio_fs::read_link[0]::read_link[0]",
"tokio_fs::read_link[0]::{{impl}}[0]::new[0]",
"tokio_fs::remove_dir[0]::remove_dir[0]",
"tokio_fs::remove_dir[0]::{{impl}}[0]::new[0]",
"tokio_fs::remove_file[0]::remove_file[0]",
"tokio_fs::remove_file[0]::{{impl}}[0]::new[0]",
"tokio_fs::rename[0]::rename[0]",
"tokio_fs::rename[0]::{{impl}}[0]::new[0]",
"tokio_fs::set_permissions[0]::set_permissions[0]",
"tokio_fs::set_permissions[0]::{{impl}}[0]::new[0]",
"tokio_fs::symlink_metadata[0]::{{impl}}[0]::new[0]"
]
