CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"xz2::stream[0]::{{impl}}[12]::clone[0]",
"xz2::stream[0]::{{impl}}[15]::clone[0]",
"xz2::stream[0]::{{impl}}[21]::clone[0]",
"xz2::stream[0]::{{impl}}[23]::clone[0]",
"xz2::stream[0]::{{impl}}[25]::clone[0]"
]
