CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"coco::deque[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"coco::epoch[0]::atomic[0]::strongest_failure_ordering[0]",
"coco::epoch[0]::atomic[0]::{{impl}}[4]::from_data[0]",
"coco::epoch[0]::atomic[0]::{{impl}}[4]::new[0]",
"coco::epoch[0]::atomic[0]::{{impl}}[4]::with_tag[0]"
]
