CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ryu::d2s[0]::mul_shift_all[0]",
"ryu::d2s[0]::multiple_of_power_of_5[0]",
"ryu::d2s_intrinsics[0]::div100[0]",
"ryu::d2s_intrinsics[0]::div100_000_000[0]",
"ryu::d2s_intrinsics[0]::div10[0]",
"ryu::d2s_intrinsics[0]::div5[0]",
"ryu::f2s[0]::multiple_of_power_of_5[0]"
]
