CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"glutin::api[0]::caca[0]::{{impl}}[0]::new[0]::get_masks[0]",
"glutin::api[0]::egl[0]::ffi[0]::egl[0]::missing_fn_panic[0]",
"glutin::api[0]::glx[0]::ffi[0]::glx[0]::missing_fn_panic[0]",
"glutin::api[0]::glx[0]::ffi[0]::glx_extra[0]::missing_fn_panic[0]",
"glutin::platform[0]::platform[0]::{{impl}}[5]::default[0]",
"glutin::platform[0]::platform[0]::{{impl}}[6]::clone[0]",
"glutin::{{impl}}[13]::default[0]",
"glutin::{{impl}}[14]::map_sharing[0]",
"glutin::{{impl}}[15]::default[0]",
"glutin::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"glutin::{{impl}}[21]::clone[0]",
"glutin::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"glutin::{{impl}}[26]::clone[0]",
"glutin::{{impl}}[28]::clone[0]",
"glutin::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"glutin::{{impl}}[33]::clone[0]",
"glutin::{{impl}}[36]::assert_receiver_is_total_eq[0]",
"glutin::{{impl}}[38]::clone[0]",
"glutin::{{impl}}[41]::clone[0]",
"glutin::{{impl}}[44]::clone[0]",
"glutin::{{impl}}[45]::clone[0]"
]
