CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"sha2::sha256_utils[0]::sha256load[0]",
"sha2::sha256_utils[0]::sha256msg1[0]",
"sha2::sha256_utils[0]::sha256msg1[0]::sigma0x4[0]",
"sha2::sha256_utils[0]::sha256swap[0]",
"sha2::sha512_utils[0]::sha512_schedule_x2[0]",
"sha2::sha512_utils[0]::sha512load[0]"
]
