CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fake_simd::{{impl}}[0]::add[0]",
"fake_simd::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"fake_simd::{{impl}}[11]::eq[0]",
"fake_simd::{{impl}}[11]::ne[0]",
"fake_simd::{{impl}}[13]::clone[0]",
"fake_simd::{{impl}}[15]::clone[0]",
"fake_simd::{{impl}}[1]::sub[0]",
"fake_simd::{{impl}}[9]::add[0]"
]
