CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"mio_uds::datagram[0]::{{impl}}[2]::as_raw_fd[0]",
"mio_uds::datagram[0]::{{impl}}[3]::into_raw_fd[0]",
"mio_uds::listener[0]::{{impl}}[2]::as_raw_fd[0]",
"mio_uds::listener[0]::{{impl}}[3]::into_raw_fd[0]",
"mio_uds::socket[0]::{{impl}}[0]::fd[0]",
"mio_uds::socket[0]::{{impl}}[0]::into_fd[0]",
"mio_uds::stream[0]::{{impl}}[6]::as_raw_fd[0]",
"mio_uds::stream[0]::{{impl}}[7]::into_raw_fd[0]"
]
