CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"json::codegen[0]::Generator[0]::dedent[0]",
"json::codegen[0]::Generator[0]::indent[0]",
"json::number[0]::{{impl}}[0]::is_empty[0]",
"json::number[0]::{{impl}}[0]::is_zero[0]",
"json::number[0]::{{impl}}[13]::clone[0]",
"json::number[0]::{{impl}}[21]::eq[0]",
"json::number[0]::{{impl}}[22]::eq[0]",
"json::number[0]::{{impl}}[24]::eq[0]",
"json::number[0]::{{impl}}[25]::eq[0]",
"json::number[0]::{{impl}}[27]::eq[0]",
"json::number[0]::{{impl}}[28]::eq[0]",
"json::number[0]::{{impl}}[30]::eq[0]",
"json::number[0]::{{impl}}[31]::eq[0]",
"json::number[0]::{{impl}}[33]::eq[0]",
"json::number[0]::{{impl}}[34]::eq[0]",
"json::number[0]::{{impl}}[41]::eq[0]",
"json::number[0]::{{impl}}[42]::eq[0]",
"json::number[0]::{{impl}}[44]::eq[0]",
"json::number[0]::{{impl}}[45]::eq[0]",
"json::number[0]::{{impl}}[47]::eq[0]",
"json::number[0]::{{impl}}[48]::eq[0]",
"json::number[0]::{{impl}}[50]::eq[0]",
"json::number[0]::{{impl}}[51]::eq[0]",
"json::number[0]::{{impl}}[53]::eq[0]",
"json::number[0]::{{impl}}[54]::eq[0]",
"json::util[0]::diyfp[0]::{{impl}}[0]::new[0]",
"json::util[0]::diyfp[0]::{{impl}}[1]::sub[0]",
"json::util[0]::diyfp[0]::{{impl}}[4]::clone[0]",
"json::util[0]::grisu2[0]::count_decimal_digit32[0]"
]
