CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"deflate::chained_hash_table[0]::{{impl}}[2]::slide_value[0]",
"deflate::checksum[0]::{{impl}}[0]::new[0]",
"deflate::checksum[0]::{{impl}}[1]::current_hash[0]",
"deflate::checksum[0]::{{impl}}[3]::new[0]",
"deflate::checksum[0]::{{impl}}[4]::current_hash[0]",
"deflate::checksum[0]::{{impl}}[4]::update[0]",
"deflate::compress[0]::{{impl}}[0]::clone[0]",
"deflate::compress[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"deflate::compression_options[0]::{{impl}}[0]::default[0]",
"deflate::compression_options[0]::{{impl}}[12]::clone[0]",
"deflate::compression_options[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"deflate::compression_options[0]::{{impl}}[18]::clone[0]",
"deflate::compression_options[0]::{{impl}}[19]::hash[0]",
"deflate::compression_options[0]::{{impl}}[1]::default[0]",
"deflate::compression_options[0]::{{impl}}[20]::eq[0]",
"deflate::compression_options[0]::{{impl}}[20]::ne[0]",
"deflate::compression_options[0]::{{impl}}[21]::assert_receiver_is_total_eq[0]",
"deflate::compression_options[0]::{{impl}}[23]::clone[0]",
"deflate::compression_options[0]::{{impl}}[2]::fast[0]",
"deflate::compression_options[0]::{{impl}}[2]::huffman_only[0]",
"deflate::compression_options[0]::{{impl}}[2]::rle[0]",
"deflate::compression_options[0]::{{impl}}[4]::from[0]",
"deflate::compression_options[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"deflate::deflate_state[0]::{{impl}}[0]::add[0]",
"deflate::deflate_state[0]::{{impl}}[0]::get[0]",
"deflate::deflate_state[0]::{{impl}}[0]::reset[0]",
"deflate::deflate_state[0]::{{impl}}[3]::default[0]",
"deflate::huffman_lengths[0]::extra_bits_for_huffman_length_code[0]",
"deflate::huffman_table[0]::{{impl}}[1]::new[0]",
"deflate::huffman_table[0]::{{impl}}[3]::clone[0]",
"deflate::huffman_table[0]::{{impl}}[5]::default[0]",
"deflate::huffman_table[0]::{{impl}}[6]::clone[0]",
"deflate::length_encode[0]::in_place[0]::{{impl}}[1]::eq[0]",
"deflate::length_encode[0]::in_place[0]::{{impl}}[1]::ne[0]",
"deflate::length_encode[0]::in_place[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"deflate::length_encode[0]::not_max_repetitions[0]",
"deflate::length_encode[0]::{{impl}}[0]::from_prev_and_repeat[0]",
"deflate::length_encode[0]::{{impl}}[1]::assert_receiver_is_total_eq[0]",
"deflate::lz77[0]::buffer_full[0]",
"deflate::lz77[0]::{{impl}}[10]::clone[0]",
"deflate::lz77[0]::{{impl}}[15]::clone[0]",
"deflate::lz77[0]::{{impl}}[17]::assert_receiver_is_total_eq[0]",
"deflate::lz77[0]::{{impl}}[2]::new[0]",
"deflate::lz77[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"deflate::lzvalue[0]::{{impl}}[0]::new[0]",
"deflate::lzvalue[0]::{{impl}}[0]::stored_length[0]",
"deflate::lzvalue[0]::{{impl}}[10]::clone[0]",
"deflate::lzvalue[0]::{{impl}}[13]::eq[0]",
"deflate::lzvalue[0]::{{impl}}[13]::ne[0]",
"deflate::lzvalue[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"deflate::lzvalue[0]::{{impl}}[15]::clone[0]",
"deflate::lzvalue[0]::{{impl}}[1]::literal[0]",
"deflate::lzvalue[0]::{{impl}}[1]::value[0]",
"deflate::lzvalue[0]::{{impl}}[3]::eq[0]",
"deflate::lzvalue[0]::{{impl}}[3]::ne[0]",
"deflate::lzvalue[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"deflate::lzvalue[0]::{{impl}}[5]::clone[0]",
"deflate::lzvalue[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]"
]
