CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"x11_dl::error[0]::{{impl}}[11]::clone[0]",
"x11_dl::error[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"x11_dl::xcursor[0]::{{impl}}[25]::clone[0]",
"x11_dl::xcursor[0]::{{impl}}[8]::clone[0]",
"x11_dl::xft[0]::{{impl}}[11]::eq[0]",
"x11_dl::xft[0]::{{impl}}[11]::ne[0]",
"x11_dl::xft[0]::{{impl}}[13]::clone[0]",
"x11_dl::xft[0]::{{impl}}[23]::eq[0]",
"x11_dl::xft[0]::{{impl}}[23]::ne[0]",
"x11_dl::xft[0]::{{impl}}[25]::clone[0]",
"x11_dl::xft[0]::{{impl}}[7]::eq[0]",
"x11_dl::xft[0]::{{impl}}[7]::ne[0]",
"x11_dl::xft[0]::{{impl}}[9]::clone[0]",
"x11_dl::xinerama[0]::{{impl}}[3]::eq[0]",
"x11_dl::xinerama[0]::{{impl}}[3]::ne[0]",
"x11_dl::xinerama[0]::{{impl}}[5]::clone[0]",
"x11_dl::xinerama[0]::{{impl}}[7]::eq[0]",
"x11_dl::xinerama[0]::{{impl}}[7]::ne[0]",
"x11_dl::xinerama[0]::{{impl}}[9]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[11]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[19]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[29]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[2]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[33]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[35]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[39]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[4]::clone[0]",
"x11_dl::xinput2[0]::{{impl}}[6]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[23]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[23]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[25]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[27]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[27]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[29]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[31]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[31]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[33]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[35]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[35]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[37]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[39]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[39]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[41]::clone[0]",
"x11_dl::xinput[0]::{{impl}}[7]::eq[0]",
"x11_dl::xinput[0]::{{impl}}[7]::ne[0]",
"x11_dl::xinput[0]::{{impl}}[9]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[410]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[410]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[412]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[414]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[414]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[416]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[418]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[418]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[420]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[426]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[426]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[428]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[434]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[434]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[436]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[438]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[438]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[440]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[442]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[442]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[444]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[450]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[450]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[452]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[462]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[462]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[464]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[470]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[470]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[472]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[490]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[490]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[492]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[494]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[494]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[496]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[498]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[498]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[500]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[510]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[510]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[512]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[514]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[514]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[516]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[518]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[518]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[520]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[522]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[522]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[524]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[538]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[538]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[540]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[554]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[554]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[556]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[558]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[558]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[560]::clone[0]",
"x11_dl::xlib[0]::{{impl}}[562]::eq[0]",
"x11_dl::xlib[0]::{{impl}}[562]::ne[0]",
"x11_dl::xlib[0]::{{impl}}[564]::clone[0]",
"x11_dl::xrandr[0]::{{impl}}[35]::eq[0]",
"x11_dl::xrandr[0]::{{impl}}[35]::ne[0]",
"x11_dl::xrandr[0]::{{impl}}[37]::clone[0]",
"x11_dl::xrandr[0]::{{impl}}[3]::eq[0]",
"x11_dl::xrandr[0]::{{impl}}[3]::ne[0]",
"x11_dl::xrandr[0]::{{impl}}[5]::clone[0]",
"x11_dl::xrecord[0]::{{impl}}[15]::eq[0]",
"x11_dl::xrecord[0]::{{impl}}[15]::ne[0]",
"x11_dl::xrecord[0]::{{impl}}[17]::clone[0]",
"x11_dl::xrecord[0]::{{impl}}[19]::eq[0]",
"x11_dl::xrecord[0]::{{impl}}[19]::ne[0]",
"x11_dl::xrecord[0]::{{impl}}[21]::clone[0]",
"x11_dl::xrecord[0]::{{impl}}[23]::eq[0]",
"x11_dl::xrecord[0]::{{impl}}[23]::ne[0]",
"x11_dl::xrecord[0]::{{impl}}[25]::clone[0]",
"x11_dl::xrecord[0]::{{impl}}[7]::eq[0]",
"x11_dl::xrecord[0]::{{impl}}[7]::ne[0]",
"x11_dl::xrecord[0]::{{impl}}[9]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[11]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[11]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[13]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[31]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[31]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[33]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[35]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[35]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[37]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[39]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[39]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[3]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[3]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[41]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[43]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[43]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[45]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[51]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[51]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[53]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[55]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[55]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[57]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[59]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[59]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[5]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[61]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[63]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[63]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[65]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[67]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[67]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[69]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[71]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[71]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[73]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[75]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[75]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[77]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[79]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[79]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[7]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[7]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[81]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[83]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[83]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[85]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[87]::eq[0]",
"x11_dl::xrender[0]::{{impl}}[87]::ne[0]",
"x11_dl::xrender[0]::{{impl}}[89]::clone[0]",
"x11_dl::xrender[0]::{{impl}}[9]::clone[0]",
"x11_dl::xss[0]::{{impl}}[3]::eq[0]",
"x11_dl::xss[0]::{{impl}}[3]::ne[0]",
"x11_dl::xss[0]::{{impl}}[5]::clone[0]"
]
