CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"heapsize::{{impl}}[10]::heap_size_of_children[0]",
"heapsize::{{impl}}[11]::heap_size_of_children[0]",
"heapsize::{{impl}}[12]::heap_size_of_children[0]",
"heapsize::{{impl}}[13]::heap_size_of_children[0]",
"heapsize::{{impl}}[16]::heap_size_of_children[0]",
"heapsize::{{impl}}[22]::heap_size_of_children[0]",
"heapsize::{{impl}}[25]::heap_size_of_children[0]",
"heapsize::{{impl}}[26]::heap_size_of_children[0]",
"heapsize::{{impl}}[27]::heap_size_of_children[0]",
"heapsize::{{impl}}[28]::heap_size_of_children[0]",
"heapsize::{{impl}}[30]::heap_size_of_children[0]",
"heapsize::{{impl}}[31]::heap_size_of_children[0]",
"heapsize::{{impl}}[32]::heap_size_of_children[0]",
"heapsize::{{impl}}[33]::heap_size_of_children[0]",
"heapsize::{{impl}}[34]::heap_size_of_children[0]",
"heapsize::{{impl}}[35]::heap_size_of_children[0]",
"heapsize::{{impl}}[36]::heap_size_of_children[0]",
"heapsize::{{impl}}[37]::heap_size_of_children[0]",
"heapsize::{{impl}}[38]::heap_size_of_children[0]",
"heapsize::{{impl}}[39]::heap_size_of_children[0]",
"heapsize::{{impl}}[40]::heap_size_of_children[0]",
"heapsize::{{impl}}[43]::heap_size_of_children[0]",
"heapsize::{{impl}}[44]::heap_size_of_children[0]",
"heapsize::{{impl}}[45]::heap_size_of_children[0]",
"heapsize::{{impl}}[46]::heap_size_of_children[0]",
"heapsize::{{impl}}[48]::heap_size_of_children[0]",
"heapsize::{{impl}}[6]::heap_size_of_children[0]",
"heapsize::{{impl}}[7]::heap_size_of_children[0]",
"heapsize::{{impl}}[9]::heap_size_of_children[0]"
]
