CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"lock_api::mutex[0]::RawMutexFair[0]::bump[0]",
"lock_api::mutex[0]::{{impl}}[6]::default[0]",
"lock_api::mutex[0]::{{impl}}[7]::from[0]",
"lock_api::remutex[0]::{{impl}}[0]::unlock[0]",
"lock_api::remutex[0]::{{impl}}[10]::from[0]",
"lock_api::remutex[0]::{{impl}}[1]::bump[0]",
"lock_api::remutex[0]::{{impl}}[1]::unlock_fair[0]",
"lock_api::remutex[0]::{{impl}}[9]::default[0]",
"lock_api::rwlock[0]::RawRwLockFair[0]::bump_exclusive[0]",
"lock_api::rwlock[0]::RawRwLockFair[0]::bump_shared[0]",
"lock_api::rwlock[0]::RawRwLockUpgradeFair[0]::bump_upgradable[0]",
"lock_api::rwlock[0]::{{impl}}[10]::default[0]",
"lock_api::rwlock[0]::{{impl}}[11]::from[0]"
]
