CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"gleam::ffi[0]::missing_fn_panic[0]",
"gleam::ffi_gl[0]::missing_fn_panic[0]",
"gleam::ffi_gles[0]::missing_fn_panic[0]",
"gleam::gl[0]::{{impl}}[0]::default[0]",
"gleam::gl[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]"
]
