CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ascii::ascii_char[0]::{{impl}}[0]::as_char[0]",
"ascii::ascii_char[0]::{{impl}}[0]::eq_ignore_ascii_case[0]",
"ascii::ascii_char[0]::{{impl}}[0]::from[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_alphanumeric[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_graph[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_lowercase[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_print[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_punctuation[0]",
"ascii::ascii_char[0]::{{impl}}[0]::is_uppercase[0]",
"ascii::ascii_char[0]::{{impl}}[0]::make_ascii_lowercase[0]",
"ascii::ascii_char[0]::{{impl}}[0]::make_ascii_uppercase[0]",
"ascii::ascii_char[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"ascii::ascii_char[0]::{{impl}}[16]::clone[0]",
"ascii::ascii_char[0]::{{impl}}[17]::from[0]",
"ascii::ascii_char[0]::{{impl}}[18]::eq[0]",
"ascii::ascii_char[0]::{{impl}}[19]::eq[0]",
"ascii::ascii_char[0]::{{impl}}[20]::partial_cmp[0]",
"ascii::ascii_char[0]::{{impl}}[21]::partial_cmp[0]",
"ascii::ascii_char[0]::{{impl}}[22]::from[0]",
"ascii::ascii_char[0]::{{impl}}[23]::eq[0]",
"ascii::ascii_char[0]::{{impl}}[24]::eq[0]",
"ascii::ascii_char[0]::{{impl}}[25]::partial_cmp[0]",
"ascii::ascii_char[0]::{{impl}}[26]::partial_cmp[0]",
"ascii::ascii_char[0]::{{impl}}[27]::eq[0]",
"ascii::ascii_char[0]::{{impl}}[27]::ne[0]",
"ascii::ascii_char[0]::{{impl}}[3]::eq_ignore_ascii_case[0]",
"ascii::ascii_char[0]::{{impl}}[3]::is_ascii[0]",
"ascii::ascii_char[0]::{{impl}}[3]::make_ascii_lowercase[0]",
"ascii::ascii_char[0]::{{impl}}[3]::make_ascii_uppercase[0]",
"ascii::ascii_char[0]::{{impl}}[7]::to_ascii_char[0]",
"ascii::ascii_str[0]::{{impl}}[20]::valid_up_to[0]",
"ascii::ascii_str[0]::{{impl}}[59]::assert_receiver_is_total_eq[0]",
"ascii::ascii_str[0]::{{impl}}[60]::eq[0]",
"ascii::ascii_str[0]::{{impl}}[60]::ne[0]",
"ascii::ascii_str[0]::{{impl}}[62]::clone[0]",
"ascii::ascii_string[0]::{{impl}}[24]::ascii_error[0]",
"ascii::ascii_string[0]::{{impl}}[24]::into_source[0]",
"ascii::ascii_string[0]::{{impl}}[49]::assert_receiver_is_total_eq[0]",
"ascii::ascii_string[0]::{{impl}}[50]::eq[0]",
"ascii::ascii_string[0]::{{impl}}[50]::ne[0]",
"ascii::ascii_string[0]::{{impl}}[52]::clone[0]"
]
