CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"zip::compression[0]::{{impl}}[0]::from_u16[0]",
"zip::compression[0]::{{impl}}[0]::to_u16[0]",
"zip::compression[0]::{{impl}}[4]::clone[0]",
"zip::cp437[0]::to_char[0]",
"zip::crc32[0]::{{impl}}[0]::check_matches[0]",
"zip::crc32[0]::{{impl}}[0]::into_inner[0]",
"zip::crc32[0]::{{impl}}[0]::new[0]",
"zip::types[0]::{{impl}}[0]::from_u8[0]",
"zip::types[0]::{{impl}}[5]::clone[0]",
"zip::write[0]::{{impl}}[0]::default[0]",
"zip::write[0]::{{impl}}[6]::default[0]",
"zip::write[0]::{{impl}}[7]::clone[0]"
]
