CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"serialize::hex[0]::{{impl}}[5]::clone[0]",
"serialize::json[0]::{{impl}}[47]::clone[0]",
"serialize::json[0]::{{impl}}[55]::clone[0]",
"serialize::json[0]::{{impl}}[6]::from[0]"
]
