CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"wayland_client::generated[0]::rust_api[0]::wl_buffer[0]::{{impl}}[0]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_buffer[0]::{{impl}}[0]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_buffer[0]::{{impl}}[1]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_buffer[0]::{{impl}}[1]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_callback[0]::{{impl}}[0]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_callback[0]::{{impl}}[0]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_callback[0]::{{impl}}[1]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_callback[0]::{{impl}}[1]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_compositor[0]::{{impl}}[1]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_compositor[0]::{{impl}}[1]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[0]::to_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[10]::eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[10]::ne[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Ask[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Copy[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Move[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::None[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Ask[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Copy[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Move[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::all[0]::__BitFlags[0]::None[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::bits[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::contains[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::from_bits_truncate[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::intersects[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::is_all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::is_empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[17]::set[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[28]::from_iter[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[2]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[2]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[5]::hash[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[6]::cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[7]::partial_cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[8]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_device_manager[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_offer[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_offer[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_source[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_data_source[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_display[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_display[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[12]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[1]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[2]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[2]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_keyboard[0]::{{impl}}[8]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[13]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[15]::hash[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[16]::cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[17]::partial_cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[18]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[1]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[20]::eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[20]::ne[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[22]::fmt[0]::__BitFlags[0]::Current[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[22]::fmt[0]::__BitFlags[0]::Preferred[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::all[0]::__BitFlags[0]::Current[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::all[0]::__BitFlags[0]::Preferred[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::bits[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::contains[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::from_bits_truncate[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::intersects[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::is_all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::is_empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[27]::set[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[2]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[2]::to_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[38]::from_iter[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[3]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[3]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_output[0]::{{impl}}[9]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[10]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[14]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[18]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[1]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[22]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[2]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_pointer[0]::{{impl}}[3]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_region[0]::{{impl}}[0]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_region[0]::{{impl}}[0]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_region[0]::{{impl}}[1]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_region[0]::{{impl}}[1]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[0]::to_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[10]::eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[10]::ne[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Keyboard[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Pointer[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Touch[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Keyboard[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Pointer[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Touch[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::bits[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::contains[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::from_bits_truncate[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::intersects[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::is_all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::is_empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[17]::set[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[28]::from_iter[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[5]::hash[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[6]::cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[7]::partial_cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[8]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_seat[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell[0]::{{impl}}[2]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell[0]::{{impl}}[2]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[0]::to_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[10]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[12]::eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[12]::ne[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::BottomLeft[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::BottomRight[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::Bottom[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::Left[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::None[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::Right[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::TopLeft[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::TopRight[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[14]::fmt[0]::__BitFlags[0]::Top[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::BottomLeft[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::BottomRight[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::Bottom[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::Left[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::None[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::Right[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::TopLeft[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::TopRight[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::all[0]::__BitFlags[0]::Top[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::bits[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::contains[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::from_bits_truncate[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::intersects[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::is_all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::is_empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[19]::set[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[1]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[1]::to_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[2]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[30]::from_iter[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[31]::hash[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[32]::cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[33]::partial_cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[34]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[35]::assert_receiver_is_total_eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[36]::eq[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[36]::ne[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[38]::fmt[0]::__BitFlags[0]::Inactive[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::all[0]::__BitFlags[0]::Inactive[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::bits[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::contains[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::from_bits_truncate[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::intersects[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::is_all[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::is_empty[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[43]::set[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[4]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[4]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[54]::from_iter[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[57]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[7]::hash[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[8]::cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shell_surface[0]::{{impl}}[9]::partial_cmp[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[12]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[1]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[3]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[3]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm[0]::{{impl}}[8]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm_pool[0]::{{impl}}[1]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_shm_pool[0]::{{impl}}[1]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subcompositor[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subcompositor[0]::{{impl}}[2]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subcompositor[0]::{{impl}}[2]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subcompositor[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subsurface[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subsurface[0]::{{impl}}[2]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subsurface[0]::{{impl}}[2]::opcode[0]",
"wayland_client::generated[0]::rust_api[0]::wl_subsurface[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_surface[0]::{{impl}}[0]::from_raw[0]",
"wayland_client::generated[0]::rust_api[0]::wl_surface[0]::{{impl}}[7]::clone[0]",
"wayland_client::generated[0]::rust_api[0]::wl_touch[0]::{{impl}}[0]::is_destructor[0]",
"wayland_client::generated[0]::rust_api[0]::wl_touch[0]::{{impl}}[0]::opcode[0]",
"wayland_client::globals[0]::GlobalImplementor[0]::error[0]"
]
