CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"encoding_rs::ascii[0]::count_zeros[0]",
"encoding_rs::big5[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::big5[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::big5[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::big5[0]::{{impl}}[0]::plus_one_if_lead[0]",
"encoding_rs::big5[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::big5[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::checked_add[0]",
"encoding_rs::checked_add_opt[0]",
"encoding_rs::checked_div[0]",
"encoding_rs::checked_min[0]",
"encoding_rs::checked_mul[0]",
"encoding_rs::euc_jp[0]::{{impl}}[0]::count[0]",
"encoding_rs::euc_jp[0]::{{impl}}[0]::is_none[0]",
"encoding_rs::euc_jp[0]::{{impl}}[1]::max_utf16_buffer_length[0]",
"encoding_rs::euc_jp[0]::{{impl}}[1]::max_utf8_buffer_length[0]",
"encoding_rs::euc_jp[0]::{{impl}}[1]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::euc_jp[0]::{{impl}}[1]::plus_one_if_lead[0]",
"encoding_rs::euc_jp[0]::{{impl}}[2]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::euc_jp[0]::{{impl}}[2]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::euc_kr[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::euc_kr[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::euc_kr[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::euc_kr[0]::{{impl}}[0]::plus_one_if_lead[0]",
"encoding_rs::euc_kr[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::euc_kr[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::gb18030[0]::{{impl}}[0]::count[0]",
"encoding_rs::gb18030[0]::{{impl}}[0]::is_none[0]",
"encoding_rs::gb18030[0]::{{impl}}[1]::extra_from_state[0]",
"encoding_rs::gb18030[0]::{{impl}}[1]::max_utf16_buffer_length[0]",
"encoding_rs::gb18030[0]::{{impl}}[1]::max_utf8_buffer_length[0]",
"encoding_rs::gb18030[0]::{{impl}}[1]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::gb18030[0]::{{impl}}[2]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::gb18030[0]::{{impl}}[2]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::in_inclusive_range16[0]",
"encoding_rs::in_inclusive_range32[0]",
"encoding_rs::in_inclusive_range8[0]",
"encoding_rs::in_inclusive_range[0]",
"encoding_rs::in_range16[0]",
"encoding_rs::in_range32[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[0]::extra_to_input_from_state[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[1]::has_pending_state[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::iso_2022_jp[0]::{{impl}}[2]::clone[0]",
"encoding_rs::mem[0]::is_char_bidi[0]",
"encoding_rs::mem[0]::is_utf16_code_unit_bidi[0]",
"encoding_rs::mem[0]::{{impl}}[0]::assert_receiver_is_total_eq[0]",
"encoding_rs::replacement[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::replacement[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::replacement[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::shift_jis[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::shift_jis[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::shift_jis[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::shift_jis[0]::{{impl}}[0]::plus_one_if_lead[0]",
"encoding_rs::shift_jis[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::shift_jis[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::utf_16[0]::{{impl}}[0]::additional_from_state[0]",
"encoding_rs::utf_16[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::utf_16[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::utf_16[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::utf_8[0]::{{impl}}[0]::extra_from_state[0]",
"encoding_rs::utf_8[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::utf_8[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::utf_8[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::utf_8[0]::{{impl}}[0]::new_inner[0]",
"encoding_rs::utf_8[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::utf_8[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::x_user_defined[0]::{{impl}}[0]::max_utf16_buffer_length[0]",
"encoding_rs::x_user_defined[0]::{{impl}}[0]::max_utf8_buffer_length[0]",
"encoding_rs::x_user_defined[0]::{{impl}}[0]::max_utf8_buffer_length_without_replacement[0]",
"encoding_rs::x_user_defined[0]::{{impl}}[1]::max_buffer_length_from_utf16_without_replacement[0]",
"encoding_rs::x_user_defined[0]::{{impl}}[1]::max_buffer_length_from_utf8_without_replacement[0]",
"encoding_rs::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"encoding_rs::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"encoding_rs::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"encoding_rs::{{impl}}[6]::unmappable_from_bmp[0]"
]
