CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_codec::bytes_codec[0]::{{impl}}[0]::new[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[3]::hash[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[4]::partial_cmp[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[5]::cmp[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[6]::eq[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[6]::ne[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_codec::bytes_codec[0]::{{impl}}[9]::clone[0]",
"tokio_codec::lines_codec[0]::{{impl}}[0]::max_length[0]",
"tokio_codec::lines_codec[0]::{{impl}}[0]::new_with_max_length[0]",
"tokio_codec::lines_codec[0]::{{impl}}[3]::hash[0]",
"tokio_codec::lines_codec[0]::{{impl}}[4]::partial_cmp[0]",
"tokio_codec::lines_codec[0]::{{impl}}[5]::cmp[0]",
"tokio_codec::lines_codec[0]::{{impl}}[6]::eq[0]",
"tokio_codec::lines_codec[0]::{{impl}}[6]::ne[0]",
"tokio_codec::lines_codec[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"tokio_codec::lines_codec[0]::{{impl}}[9]::clone[0]"
]
