CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"podio::{{impl}}[0]::int_from_target[0]",
"podio::{{impl}}[0]::int_to_target[0]",
"podio::{{impl}}[1]::int_from_target[0]",
"podio::{{impl}}[1]::int_to_target[0]",
"podio::{{impl}}[4]::from_be[0]",
"podio::{{impl}}[4]::from_le[0]",
"podio::{{impl}}[4]::to_be[0]",
"podio::{{impl}}[4]::to_le[0]",
"podio::{{impl}}[5]::from_be[0]",
"podio::{{impl}}[5]::from_le[0]",
"podio::{{impl}}[5]::to_be[0]",
"podio::{{impl}}[5]::to_le[0]",
"podio::{{impl}}[6]::from_be[0]",
"podio::{{impl}}[6]::from_le[0]",
"podio::{{impl}}[6]::to_be[0]",
"podio::{{impl}}[6]::to_le[0]",
"podio::{{impl}}[7]::from_be[0]",
"podio::{{impl}}[7]::from_le[0]",
"podio::{{impl}}[7]::to_be[0]",
"podio::{{impl}}[7]::to_le[0]"
]
