CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"msdos_time::{{impl}}[0]::new[0]",
"msdos_time::{{impl}}[3]::clone[0]"
]
