CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"unix_socket::{{impl}}[11]::as_raw_fd[0]",
"unix_socket::{{impl}}[13]::into_raw_fd[0]",
"unix_socket::{{impl}}[16]::as_raw_fd[0]",
"unix_socket::{{impl}}[18]::into_raw_fd[0]",
"unix_socket::{{impl}}[23]::as_raw_fd[0]",
"unix_socket::{{impl}}[25]::into_raw_fd[0]"
]
