CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"winit::events[0]::{{impl}}[10]::clone[0]",
"winit::events[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"winit::events[0]::{{impl}}[19]::clone[0]",
"winit::events[0]::{{impl}}[20]::assert_receiver_is_total_eq[0]",
"winit::events[0]::{{impl}}[25]::clone[0]",
"winit::events[0]::{{impl}}[26]::assert_receiver_is_total_eq[0]",
"winit::events[0]::{{impl}}[35]::clone[0]",
"winit::events[0]::{{impl}}[36]::assert_receiver_is_total_eq[0]",
"winit::events[0]::{{impl}}[41]::clone[0]",
"winit::events[0]::{{impl}}[42]::assert_receiver_is_total_eq[0]",
"winit::events[0]::{{impl}}[43]::eq[0]",
"winit::events[0]::{{impl}}[43]::ne[0]",
"winit::events[0]::{{impl}}[44]::hash[0]",
"winit::events[0]::{{impl}}[46]::default[0]",
"winit::events[0]::{{impl}}[7]::clone[0]",
"winit::icon[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"winit::icon[0]::{{impl}}[7]::clone[0]",
"winit::platform[0]::platform[0]::wayland[0]::keyboard[0]::key_to_vkey[0]",
"winit::platform[0]::platform[0]::wayland[0]::keyboard[0]::{{impl}}[0]::from[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[0]::hash[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[10]::partial_cmp[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[12]::eq[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[12]::ne[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[13]::clone[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[1]::cmp[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[2]::partial_cmp[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[4]::eq[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[5]::clone[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[8]::hash[0]",
"winit::platform[0]::platform[0]::wayland[0]::{{impl}}[9]::cmp[0]",
"winit::platform[0]::platform[0]::x11[0]::dnd[0]::{{impl}}[6]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::events[0]::keysym_to_element[0]",
"winit::platform[0]::platform[0]::x11[0]::ime[0]::input_method[0]::{{impl}}[6]::deref[0]",
"winit::platform[0]::platform[0]::x11[0]::ime[0]::input_method[0]::{{impl}}[6]::deref[0]::__static_ref_initialize[0]",
"winit::platform[0]::platform[0]::x11[0]::ime[0]::input_method[0]::{{impl}}[7]::initialize[0]",
"winit::platform[0]::platform[0]::x11[0]::mkdid[0]",
"winit::platform[0]::platform[0]::x11[0]::mkwid[0]",
"winit::platform[0]::platform[0]::x11[0]::monitor[0]::{{impl}}[2]::deref[0]",
"winit::platform[0]::platform[0]::x11[0]::monitor[0]::{{impl}}[2]::deref[0]::__static_ref_initialize[0]",
"winit::platform[0]::platform[0]::x11[0]::monitor[0]::{{impl}}[3]::initialize[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::format[0]::{{impl}}[0]::from_format[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::format[0]::{{impl}}[0]::is_same_size_as[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::format[0]::{{impl}}[11]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::format[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[0]::contains_point[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[0]::get_overlapping_area[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[10]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[17]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[1]::from_border[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[1]::new[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[5]::eq[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[5]::ne[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::geometry[0]::{{impl}}[6]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::hint[0]::{{impl}}[0]::from[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::hint[0]::{{impl}}[1]::default[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::hint[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::hint[0]::{{impl}}[9]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::util[0]::maybe_change[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[12]::hash[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[13]::cmp[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[14]::partial_cmp[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[16]::eq[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[16]::ne[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[17]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[20]::hash[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[21]::cmp[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[22]::partial_cmp[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[24]::eq[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[24]::ne[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[25]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[28]::clone[0]",
"winit::platform[0]::platform[0]::x11[0]::{{impl}}[35]::clone[0]",
"winit::platform[0]::platform[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::{{impl}}[13]::clone[0]",
"winit::platform[0]::platform[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"winit::platform[0]::platform[0]::{{impl}}[21]::clone[0]",
"winit::{{impl}}[10]::cmp[0]",
"winit::{{impl}}[11]::partial_cmp[0]",
"winit::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"winit::{{impl}}[13]::eq[0]",
"winit::{{impl}}[13]::ne[0]",
"winit::{{impl}}[14]::clone[0]",
"winit::{{impl}}[17]::hash[0]",
"winit::{{impl}}[18]::cmp[0]",
"winit::{{impl}}[19]::partial_cmp[0]",
"winit::{{impl}}[20]::assert_receiver_is_total_eq[0]",
"winit::{{impl}}[21]::eq[0]",
"winit::{{impl}}[21]::ne[0]",
"winit::{{impl}}[22]::clone[0]",
"winit::{{impl}}[25]::assert_receiver_is_total_eq[0]",
"winit::{{impl}}[28]::clone[0]",
"winit::{{impl}}[31]::hash[0]",
"winit::{{impl}}[32]::assert_receiver_is_total_eq[0]",
"winit::{{impl}}[33]::eq[0]",
"winit::{{impl}}[34]::clone[0]",
"winit::{{impl}}[41]::clone[0]",
"winit::{{impl}}[7]::default[0]",
"winit::{{impl}}[9]::hash[0]"
]
