CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"colored::color[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"colored::color[0]::{{impl}}[8]::clone[0]",
"colored::control[0]::{{impl}}[0]::default[0]",
"colored::control[0]::{{impl}}[1]::set_override[0]",
"colored::control[0]::{{impl}}[1]::should_colorize[0]",
"colored::control[0]::{{impl}}[1]::unset_override[0]",
"colored::control[0]::{{impl}}[2]::deref[0]",
"colored::control[0]::{{impl}}[2]::deref[0]::__static_ref_initialize[0]",
"colored::control[0]::{{impl}}[3]::initialize[0]",
"colored::style[0]::{{impl}}[11]::clone[0]",
"colored::style[0]::{{impl}}[1]::new[0]",
"colored::style[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"colored::style[0]::{{impl}}[4]::eq[0]",
"colored::style[0]::{{impl}}[4]::ne[0]",
"colored::style[0]::{{impl}}[6]::clone[0]",
"colored::style[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]"
]
