CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"try_lock::{{impl}}[0]::new[0]",
"try_lock::{{impl}}[8]::default[0]"
]
