CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"wayland_sys::common[0]::wl_fixed_from_int[0]",
"wayland_sys::common[0]::wl_fixed_to_int[0]"
]
