CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"wayland_scanner::protocol[0]::{{impl}}[13]::clone[0]",
"wayland_scanner::protocol[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"wayland_scanner::protocol[0]::{{impl}}[6]::nullable[0]",
"wayland_scanner::side[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"wayland_scanner::side[0]::{{impl}}[4]::clone[0]"
]
