CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_uds::ucred[0]::{{impl}}[1]::hash[0]",
"tokio_uds::ucred[0]::{{impl}}[2]::eq[0]",
"tokio_uds::ucred[0]::{{impl}}[2]::ne[0]",
"tokio_uds::ucred[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"tokio_uds::ucred[0]::{{impl}}[4]::clone[0]"
]
