CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"approx::abs_diff_eq[0]::{{impl}}[10]::abs_diff_eq[0]",
"approx::abs_diff_eq[0]::{{impl}}[10]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[11]::abs_diff_eq[0]",
"approx::abs_diff_eq[0]::{{impl}}[11]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[12]::abs_diff_eq[0]",
"approx::abs_diff_eq[0]::{{impl}}[12]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[13]::abs_diff_eq[0]",
"approx::abs_diff_eq[0]::{{impl}}[13]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[14]::abs_diff_eq[0]",
"approx::abs_diff_eq[0]::{{impl}}[14]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[5]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[6]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[7]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[8]::default_epsilon[0]",
"approx::abs_diff_eq[0]::{{impl}}[9]::default_epsilon[0]",
"approx::ulps_eq[0]::{{impl}}[0]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[1]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[2]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[3]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[4]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[5]::default_max_ulps[0]",
"approx::ulps_eq[0]::{{impl}}[6]::default_max_ulps[0]"
]
