CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ena::unify[0]::backing_vec[0]::{{impl}}[7]::clone[0]",
"ena::unify[0]::{{impl}}[10]::default[0]",
"ena::unify[0]::{{impl}}[12]::clone[0]",
"ena::unify[0]::{{impl}}[2]::len[0]",
"ena::unify[0]::{{impl}}[2]::new[0]",
"ena::unify[0]::{{impl}}[2]::reserve[0]",
"ena::unify[0]::{{impl}}[3]::find[0]",
"ena::unify[0]::{{impl}}[3]::union[0]",
"ena::unify[0]::{{impl}}[3]::union_value[0]",
"ena::unify[0]::{{impl}}[3]::unioned[0]"
]
