CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ar::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"ar::{{impl}}[14]::clone[0]",
"ar::{{impl}}[9]::new[0]"
]
