CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"wayland_kbd::ffi[0]::{{impl}}[10]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[14]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[18]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[22]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[26]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[2]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[30]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[34]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[38]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[42]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[44]::hash[0]",
"wayland_kbd::ffi[0]::{{impl}}[45]::cmp[0]",
"wayland_kbd::ffi[0]::{{impl}}[46]::partial_cmp[0]",
"wayland_kbd::ffi[0]::{{impl}}[47]::clone[0]",
"wayland_kbd::ffi[0]::{{impl}}[48]::assert_receiver_is_total_eq[0]",
"wayland_kbd::ffi[0]::{{impl}}[49]::eq[0]",
"wayland_kbd::ffi[0]::{{impl}}[49]::ne[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_LAYOUT_DEPRESSED[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_LAYOUT_EFFECTIVE[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_LAYOUT_LATCHED[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_LAYOUT_LOCKED[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_LEDS[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_MODS_DEPRESSED[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_MODS_EFFECTIVE[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_MODS_LATCHED[0]",
"wayland_kbd::ffi[0]::{{impl}}[51]::fmt[0]::__BitFlags[0]::XKB_STATE_MODS_LOCKED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_LAYOUT_DEPRESSED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_LAYOUT_EFFECTIVE[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_LAYOUT_LATCHED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_LAYOUT_LOCKED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_LEDS[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_MODS_DEPRESSED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_MODS_EFFECTIVE[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_MODS_LATCHED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::all[0]::__BitFlags[0]::XKB_STATE_MODS_LOCKED[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::bits[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::contains[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::empty[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::from_bits_truncate[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::intersects[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::is_all[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::is_empty[0]",
"wayland_kbd::ffi[0]::{{impl}}[56]::set[0]",
"wayland_kbd::ffi[0]::{{impl}}[67]::from_iter[0]",
"wayland_kbd::ffi[0]::{{impl}}[6]::clone[0]",
"wayland_kbd::mapped_keyboard[0]::{{impl}}[0]::new[0]",
"wayland_kbd::mapped_keyboard[0]::{{impl}}[5]::clone[0]"
]
