CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tiny_http::common[0]::{{impl}}[10]::partial_cmp[0]",
"tiny_http::common[0]::{{impl}}[11]::partial_cmp[0]",
"tiny_http::common[0]::{{impl}}[28]::eq[0]",
"tiny_http::common[0]::{{impl}}[2]::from[0]",
"tiny_http::common[0]::{{impl}}[30]::partial_cmp[0]",
"tiny_http::common[0]::{{impl}}[34]::partial_cmp[0]",
"tiny_http::common[0]::{{impl}}[35]::cmp[0]",
"tiny_http::common[0]::{{impl}}[37]::clone[0]",
"tiny_http::common[0]::{{impl}}[38]::eq[0]",
"tiny_http::common[0]::{{impl}}[38]::ne[0]",
"tiny_http::common[0]::{{impl}}[39]::assert_receiver_is_total_eq[0]",
"tiny_http::common[0]::{{impl}}[46]::cmp[0]",
"tiny_http::common[0]::{{impl}}[47]::assert_receiver_is_total_eq[0]",
"tiny_http::common[0]::{{impl}}[48]::eq[0]",
"tiny_http::common[0]::{{impl}}[48]::ne[0]",
"tiny_http::common[0]::{{impl}}[49]::clone[0]",
"tiny_http::common[0]::{{impl}}[4]::from[0]",
"tiny_http::common[0]::{{impl}}[7]::as_ref[0]",
"tiny_http::response[0]::{{impl}}[7]::clone[0]",
"tiny_http::util[0]::custom_stream[0]::{{impl}}[0]::new[0]",
"tiny_http::util[0]::refined_tcp_stream[0]::{{impl}}[0]::from[0]",
"tiny_http::util[0]::refined_tcp_stream[0]::{{impl}}[1]::secure[0]"
]
