CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"http::_assert_types[0]::assert_send[0]",
"http::_assert_types[0]::assert_sync[0]",
"http::convert[0]::{{impl}}[4]::try_from[0]",
"http::error[0]::{{impl}}[10]::from[0]",
"http::error[0]::{{impl}}[11]::from[0]",
"http::error[0]::{{impl}}[2]::from[0]",
"http::error[0]::{{impl}}[3]::from[0]",
"http::error[0]::{{impl}}[4]::from[0]",
"http::error[0]::{{impl}}[5]::from[0]",
"http::error[0]::{{impl}}[6]::from[0]",
"http::error[0]::{{impl}}[7]::from[0]",
"http::error[0]::{{impl}}[8]::from[0]",
"http::error[0]::{{impl}}[9]::from[0]",
"http::extensions[0]::{{impl}}[0]::finish[0]",
"http::extensions[0]::{{impl}}[0]::write_u64[0]",
"http::extensions[0]::{{impl}}[3]::default[0]",
"http::header[0]::map[0]::to_raw_capacity[0]",
"http::header[0]::map[0]::usable_capacity[0]",
"http::header[0]::map[0]::{{impl}}[50]::is_some[0]",
"http::header[0]::map[0]::{{impl}}[50]::new[0]",
"http::header[0]::map[0]::{{impl}}[50]::resolve[0]",
"http::header[0]::map[0]::{{impl}}[51]::is_red[0]",
"http::header[0]::map[0]::{{impl}}[51]::is_yellow[0]",
"http::header[0]::map[0]::{{impl}}[51]::to_green[0]",
"http::header[0]::map[0]::{{impl}}[51]::to_red[0]",
"http::header[0]::map[0]::{{impl}}[51]::to_yellow[0]",
"http::header[0]::map[0]::{{impl}}[68]::assert_receiver_is_total_eq[0]",
"http::header[0]::map[0]::{{impl}}[69]::clone[0]",
"http::header[0]::map[0]::{{impl}}[72]::clone[0]",
"http::header[0]::map[0]::{{impl}}[74]::eq[0]",
"http::header[0]::map[0]::{{impl}}[74]::ne[0]",
"http::header[0]::map[0]::{{impl}}[75]::assert_receiver_is_total_eq[0]",
"http::header[0]::map[0]::{{impl}}[76]::clone[0]",
"http::header[0]::map[0]::{{impl}}[81]::clone[0]",
"http::header[0]::map[0]::{{impl}}[84]::clone[0]",
"http::header[0]::map[0]::{{impl}}[87]::assert_receiver_is_total_eq[0]",
"http::header[0]::map[0]::{{impl}}[88]::clone[0]",
"http::header[0]::name[0]::{{impl}}[42]::assert_receiver_is_total_eq[0]",
"http::header[0]::name[0]::{{impl}}[56]::assert_receiver_is_total_eq[0]",
"http::header[0]::name[0]::{{impl}}[58]::clone[0]",
"http::header[0]::name[0]::{{impl}}[8]::new[0]",
"http::header[0]::value[0]::is_valid[0]",
"http::header[0]::value[0]::is_visible_ascii[0]",
"http::method[0]::{{impl}}[16]::new[0]",
"http::status[0]::{{impl}}[0]::as_u16[0]",
"http::status[0]::{{impl}}[0]::from_u16[0]",
"http::status[0]::{{impl}}[0]::is_client_error[0]",
"http::status[0]::{{impl}}[0]::is_informational[0]",
"http::status[0]::{{impl}}[0]::is_redirection[0]",
"http::status[0]::{{impl}}[0]::is_server_error[0]",
"http::status[0]::{{impl}}[0]::is_success[0]",
"http::status[0]::{{impl}}[12]::try_from[0]",
"http::status[0]::{{impl}}[13]::new[0]",
"http::status[0]::{{impl}}[16]::hash[0]",
"http::status[0]::{{impl}}[17]::cmp[0]",
"http::status[0]::{{impl}}[18]::partial_cmp[0]",
"http::status[0]::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"http::status[0]::{{impl}}[20]::eq[0]",
"http::status[0]::{{impl}}[20]::ne[0]",
"http::status[0]::{{impl}}[22]::clone[0]",
"http::status[0]::{{impl}}[4]::eq[0]",
"http::status[0]::{{impl}}[5]::eq[0]",
"http::status[0]::{{impl}}[6]::from[0]",
"http::status[0]::{{impl}}[8]::from[0]",
"http::status[0]::{{impl}}[9]::try_from[0]",
"http::uri[0]::scheme[0]::{{impl}}[11]::is_none[0]",
"http::uri[0]::scheme[0]::{{impl}}[13]::len[0]",
"http::uri[0]::scheme[0]::{{impl}}[14]::from[0]",
"http::uri[0]::scheme[0]::{{impl}}[20]::clone[0]",
"http::uri[0]::{{impl}}[18]::from[0]",
"http::uri[0]::{{impl}}[19]::from[0]",
"http::uri[0]::{{impl}}[20]::from[0]",
"http::uri[0]::{{impl}}[35]::assert_receiver_is_total_eq[0]",
"http::version[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"http::version[0]::{{impl}}[13]::clone[0]",
"http::version[0]::{{impl}}[3]::hash[0]",
"http::version[0]::{{impl}}[4]::cmp[0]",
"http::version[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"http::version[0]::{{impl}}[6]::clone[0]",
"http::version[0]::{{impl}}[8]::partial_cmp[0]",
"http::version[0]::{{impl}}[9]::eq[0]",
"http::version[0]::{{impl}}[9]::ne[0]"
]
