CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"slog::Drain[0]::filter[0]",
"slog::Drain[0]::filter_level[0]",
"slog::Drain[0]::ignore_res[0]",
"slog::Drain[0]::is_critical_enabled[0]",
"slog::Drain[0]::is_debug_enabled[0]",
"slog::Drain[0]::is_enabled[0]",
"slog::Drain[0]::is_error_enabled[0]",
"slog::Drain[0]::is_info_enabled[0]",
"slog::Drain[0]::is_trace_enabled[0]",
"slog::Drain[0]::is_warning_enabled[0]",
"slog::Drain[0]::map[0]",
"slog::__slog_static_max_level[0]",
"slog::{{impl}}[100]::assert_receiver_is_total_eq[0]",
"slog::{{impl}}[102]::clone[0]",
"slog::{{impl}}[11]::is_enabled[0]",
"slog::{{impl}}[13]::is_enabled[0]",
"slog::{{impl}}[14]::new[0]",
"slog::{{impl}}[15]::is_enabled[0]",
"slog::{{impl}}[16]::new[0]",
"slog::{{impl}}[17]::is_enabled[0]",
"slog::{{impl}}[20]::new[0]",
"slog::{{impl}}[21]::is_enabled[0]",
"slog::{{impl}}[22]::new[0]",
"slog::{{impl}}[23]::is_enabled[0]",
"slog::{{impl}}[24]::new[0]",
"slog::{{impl}}[25]::is_enabled[0]",
"slog::{{impl}}[31]::as_usize[0]",
"slog::{{impl}}[31]::from_usize[0]",
"slog::{{impl}}[32]::as_usize[0]",
"slog::{{impl}}[32]::from_usize[0]",
"slog::{{impl}}[32]::max[0]",
"slog::{{impl}}[32]::min[0]",
"slog::{{impl}}[36]::is_at_least[0]",
"slog::{{impl}}[77]::clone[0]",
"slog::{{impl}}[80]::clone[0]",
"slog::{{impl}}[82]::clone[0]",
"slog::{{impl}}[84]::clone[0]",
"slog::{{impl}}[86]::clone[0]",
"slog::{{impl}}[88]::clone[0]",
"slog::{{impl}}[93]::assert_receiver_is_total_eq[0]",
"slog::{{impl}}[95]::clone[0]"
]
