CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"chunked_transfer::decoder[0]::{{impl}}[0]::new[0]",
"chunked_transfer::decoder[0]::{{impl}}[4]::clone[0]"
]
