CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"wayland_window::frame[0]::{{impl}}[0]::clamp_to_limits[0]",
"wayland_window::frame[0]::{{impl}}[3]::clone[0]",
"wayland_window::{{impl}}[10]::clone[0]",
"wayland_window::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"wayland_window::{{impl}}[5]::clone[0]",
"wayland_window::{{impl}}[8]::assert_receiver_is_total_eq[0]"
]
