CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crossbeam_channel::flavors[0]::zero[0]::{{impl}}[0]::empty_on_heap[0]",
"crossbeam_channel::flavors[0]::zero[0]::{{impl}}[0]::empty_on_stack[0]",
"crossbeam_channel::flavors[0]::zero[0]::{{impl}}[0]::message_on_stack[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[17]::eq[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[17]::ne[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[19]::clone[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[1]::from[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[20]::assert_receiver_is_total_eq[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[23]::clone[0]",
"crossbeam_channel::internal[0]::select[0]::{{impl}}[2]::into[0]",
"crossbeam_channel::internal[0]::utils[0]::sleep_forever[0]",
"crossbeam_channel::internal[0]::utils[0]::{{impl}}[0]::new[0]"
]
