CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"notify::op[0]::{{impl}}[0]::hash[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::CHMOD[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::CREATE[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::REMOVE[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::RENAME[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::RESCAN[0]",
"notify::op[0]::{{impl}}[12]::all[0]::__BitFlags[0]::WRITE[0]",
"notify::op[0]::{{impl}}[12]::bits[0]",
"notify::op[0]::{{impl}}[12]::contains[0]",
"notify::op[0]::{{impl}}[12]::empty[0]",
"notify::op[0]::{{impl}}[12]::from_bits_truncate[0]",
"notify::op[0]::{{impl}}[12]::intersects[0]",
"notify::op[0]::{{impl}}[12]::is_all[0]",
"notify::op[0]::{{impl}}[12]::is_empty[0]",
"notify::op[0]::{{impl}}[12]::set[0]",
"notify::op[0]::{{impl}}[1]::cmp[0]",
"notify::op[0]::{{impl}}[23]::from_iter[0]",
"notify::op[0]::{{impl}}[2]::partial_cmp[0]",
"notify::op[0]::{{impl}}[3]::clone[0]",
"notify::op[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"notify::op[0]::{{impl}}[5]::eq[0]",
"notify::op[0]::{{impl}}[5]::ne[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::CHMOD[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::CREATE[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::REMOVE[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::RENAME[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::RESCAN[0]",
"notify::op[0]::{{impl}}[7]::fmt[0]::__BitFlags[0]::WRITE[0]",
"notify::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"notify::{{impl}}[14]::clone[0]",
"notify::{{impl}}[5]::is_recursive[0]"
]
