CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"bytecount::{{impl}}[0]::from_splat[0]",
"bytecount::{{impl}}[0]::increment[0]"
]
