CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"bzip2::mem[0]::{{impl}}[10]::clone[0]",
"bzip2::mem[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"bzip2::mem[0]::{{impl}}[15]::clone[0]",
"bzip2::mem[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"bzip2::mem[0]::{{impl}}[20]::clone[0]",
"bzip2::mem[0]::{{impl}}[23]::assert_receiver_is_total_eq[0]",
"bzip2::{{impl}}[1]::clone[0]"
]
