CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crypto_mac::errors[0]::{{impl}}[10]::clone[0]",
"crypto_mac::errors[0]::{{impl}}[13]::default[0]",
"crypto_mac::errors[0]::{{impl}}[2]::eq[0]",
"crypto_mac::errors[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"crypto_mac::errors[0]::{{impl}}[4]::clone[0]",
"crypto_mac::errors[0]::{{impl}}[7]::default[0]",
"crypto_mac::errors[0]::{{impl}}[8]::eq[0]",
"crypto_mac::errors[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]"
]
