CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"syslog::facility[0]::{{impl}}[2]::clone[0]",
"syslog::format[0]::{{impl}}[3]::clone[0]"
]
