CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"errno::errno[0]",
"errno::set_errno[0]",
"errno::{{impl}}[2]::into[0]",
"errno::{{impl}}[4]::hash[0]",
"errno::{{impl}}[5]::partial_cmp[0]",
"errno::{{impl}}[6]::eq[0]",
"errno::{{impl}}[6]::ne[0]",
"errno::{{impl}}[7]::cmp[0]",
"errno::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"errno::{{impl}}[9]::clone[0]"
]
