CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"fern::builders[0]::{{impl}}[11]::call[0]::{{impl}}[0]::flush[0]",
"fern::log_impl[0]::{{impl}}[3]::flush[0]",
"fern::log_impl[0]::{{impl}}[8]::flush[0]"
]
