CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"strum::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"strum::{{impl}}[6]::clone[0]"
]
