CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"inotify::events[0]::{{impl}}[10]::eq[0]",
"inotify::events[0]::{{impl}}[10]::ne[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::ACCESS[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::ATTRIB[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::CLOSE_NOWRITE[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::CREATE[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::DELETE[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::DELETE_SELF[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::IGNORED[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::ISDIR[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::MODIFY[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::MOVED_FROM[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::MOVED_TO[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::MOVE_SELF[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::OPEN[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::Q_OVERFLOW[0]",
"inotify::events[0]::{{impl}}[12]::fmt[0]::__BitFlags[0]::UNMOUNT[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::ACCESS[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::ATTRIB[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::CLOSE_NOWRITE[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::CREATE[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::DELETE[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::DELETE_SELF[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::IGNORED[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::ISDIR[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::MODIFY[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::MOVED_FROM[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::MOVED_TO[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::MOVE_SELF[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::OPEN[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::Q_OVERFLOW[0]",
"inotify::events[0]::{{impl}}[17]::all[0]::__BitFlags[0]::UNMOUNT[0]",
"inotify::events[0]::{{impl}}[17]::bits[0]",
"inotify::events[0]::{{impl}}[17]::contains[0]",
"inotify::events[0]::{{impl}}[17]::empty[0]",
"inotify::events[0]::{{impl}}[17]::from_bits_truncate[0]",
"inotify::events[0]::{{impl}}[17]::intersects[0]",
"inotify::events[0]::{{impl}}[17]::is_all[0]",
"inotify::events[0]::{{impl}}[17]::is_empty[0]",
"inotify::events[0]::{{impl}}[17]::set[0]",
"inotify::events[0]::{{impl}}[28]::from_iter[0]",
"inotify::events[0]::{{impl}}[5]::hash[0]",
"inotify::events[0]::{{impl}}[6]::cmp[0]",
"inotify::events[0]::{{impl}}[7]::partial_cmp[0]",
"inotify::events[0]::{{impl}}[8]::clone[0]",
"inotify::events[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"inotify::fd_guard[0]::{{impl}}[0]::should_not_close[0]",
"inotify::fd_guard[0]::{{impl}}[1]::deref[0]",
"inotify::fd_guard[0]::{{impl}}[4]::into_raw_fd[0]",
"inotify::fd_guard[0]::{{impl}}[5]::as_raw_fd[0]",
"inotify::fd_guard[0]::{{impl}}[6]::eq[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ACCESS[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ALL_EVENTS[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ATTRIB[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::CLOSE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::CLOSE_NOWRITE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::CREATE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::DELETE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::DELETE_SELF[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::DONT_FOLLOW[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::EXCL_UNLINK[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MASK_ADD[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MODIFY[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MOVED_FROM[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MOVED_TO[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MOVE[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::MOVE_SELF[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ONESHOT[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::ONLYDIR[0]",
"inotify::watches[0]::{{impl}}[10]::fmt[0]::__BitFlags[0]::OPEN[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ACCESS[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ALL_EVENTS[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ATTRIB[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::CLOSE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::CLOSE_NOWRITE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::CLOSE_WRITE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::CREATE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::DELETE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::DELETE_SELF[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::DONT_FOLLOW[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::EXCL_UNLINK[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MASK_ADD[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MODIFY[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MOVED_FROM[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MOVED_TO[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MOVE[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::MOVE_SELF[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ONESHOT[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::ONLYDIR[0]",
"inotify::watches[0]::{{impl}}[15]::all[0]::__BitFlags[0]::OPEN[0]",
"inotify::watches[0]::{{impl}}[15]::bits[0]",
"inotify::watches[0]::{{impl}}[15]::contains[0]",
"inotify::watches[0]::{{impl}}[15]::empty[0]",
"inotify::watches[0]::{{impl}}[15]::from_bits_truncate[0]",
"inotify::watches[0]::{{impl}}[15]::intersects[0]",
"inotify::watches[0]::{{impl}}[15]::is_all[0]",
"inotify::watches[0]::{{impl}}[15]::is_empty[0]",
"inotify::watches[0]::{{impl}}[15]::set[0]",
"inotify::watches[0]::{{impl}}[26]::from_iter[0]",
"inotify::watches[0]::{{impl}}[3]::hash[0]",
"inotify::watches[0]::{{impl}}[4]::cmp[0]",
"inotify::watches[0]::{{impl}}[5]::partial_cmp[0]",
"inotify::watches[0]::{{impl}}[6]::clone[0]",
"inotify::watches[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"inotify::watches[0]::{{impl}}[8]::eq[0]",
"inotify::watches[0]::{{impl}}[8]::ne[0]"
]
