CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"crc16::{{impl}}[0]::get[0]",
"crc16::{{impl}}[0]::new[0]",
"crc16::{{impl}}[100]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[102]::clone[0]",
"crc16::{{impl}}[106]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[108]::clone[0]",
"crc16::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[112]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[114]::clone[0]",
"crc16::{{impl}}[118]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[120]::clone[0]",
"crc16::{{impl}}[124]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[126]::clone[0]",
"crc16::{{impl}}[12]::clone[0]",
"crc16::{{impl}}[130]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[132]::clone[0]",
"crc16::{{impl}}[136]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[138]::clone[0]",
"crc16::{{impl}}[142]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[144]::clone[0]",
"crc16::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[18]::clone[0]",
"crc16::{{impl}}[1]::finish[0]",
"crc16::{{impl}}[22]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[24]::clone[0]",
"crc16::{{impl}}[28]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[2]::default[0]",
"crc16::{{impl}}[30]::clone[0]",
"crc16::{{impl}}[34]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[36]::clone[0]",
"crc16::{{impl}}[40]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[42]::clone[0]",
"crc16::{{impl}}[46]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[48]::clone[0]",
"crc16::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[52]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[54]::clone[0]",
"crc16::{{impl}}[58]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[5]::eq[0]",
"crc16::{{impl}}[5]::ne[0]",
"crc16::{{impl}}[60]::clone[0]",
"crc16::{{impl}}[64]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[66]::clone[0]",
"crc16::{{impl}}[6]::clone[0]",
"crc16::{{impl}}[70]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[72]::clone[0]",
"crc16::{{impl}}[76]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[78]::clone[0]",
"crc16::{{impl}}[82]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[84]::clone[0]",
"crc16::{{impl}}[88]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[90]::clone[0]",
"crc16::{{impl}}[94]::assert_receiver_is_total_eq[0]",
"crc16::{{impl}}[96]::clone[0]"
]
