CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"h2::client[0]::{{impl}}[18]::dyn[0]",
"h2::client[0]::{{impl}}[18]::is_server[0]",
"h2::client[0]::{{impl}}[25]::clone[0]",
"h2::client[0]::{{impl}}[5]::enable_push[0]",
"h2::client[0]::{{impl}}[5]::initial_connection_window_size[0]",
"h2::client[0]::{{impl}}[5]::initial_max_send_streams[0]",
"h2::client[0]::{{impl}}[5]::initial_window_size[0]",
"h2::client[0]::{{impl}}[5]::max_concurrent_reset_streams[0]",
"h2::client[0]::{{impl}}[5]::max_concurrent_streams[0]",
"h2::client[0]::{{impl}}[5]::max_frame_size[0]",
"h2::client[0]::{{impl}}[5]::max_header_list_size[0]",
"h2::client[0]::{{impl}}[5]::reset_stream_duration[0]",
"h2::client[0]::{{impl}}[6]::default[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::head[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::into_payload[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::is_end_stream[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::map[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::new[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::payload[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::payload_mut[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::set_end_stream[0]",
"h2::frame[0]::data[0]::{{impl}}[0]::stream_id[0]",
"h2::frame[0]::data[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::data[0]::{{impl}}[11]::eq[0]",
"h2::frame[0]::data[0]::{{impl}}[11]::ne[0]",
"h2::frame[0]::data[0]::{{impl}}[12]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::data[0]::{{impl}}[13]::clone[0]",
"h2::frame[0]::data[0]::{{impl}}[6]::default[0]",
"h2::frame[0]::data[0]::{{impl}}[7]::from[0]",
"h2::frame[0]::data[0]::{{impl}}[9]::eq[0]",
"h2::frame[0]::data[0]::{{impl}}[9]::ne[0]",
"h2::frame[0]::go_away[0]::{{impl}}[0]::last_stream_id[0]",
"h2::frame[0]::go_away[0]::{{impl}}[0]::new[0]",
"h2::frame[0]::go_away[0]::{{impl}}[0]::reason[0]",
"h2::frame[0]::go_away[0]::{{impl}}[2]::eq[0]",
"h2::frame[0]::go_away[0]::{{impl}}[2]::ne[0]",
"h2::frame[0]::go_away[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::go_away[0]::{{impl}}[5]::clone[0]",
"h2::frame[0]::head[0]::{{impl}}[0]::flag[0]",
"h2::frame[0]::head[0]::{{impl}}[0]::kind[0]",
"h2::frame[0]::head[0]::{{impl}}[0]::new[0]",
"h2::frame[0]::head[0]::{{impl}}[0]::stream_id[0]",
"h2::frame[0]::head[0]::{{impl}}[1]::new[0]",
"h2::frame[0]::head[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::head[0]::{{impl}}[3]::eq[0]",
"h2::frame[0]::head[0]::{{impl}}[3]::ne[0]",
"h2::frame[0]::head[0]::{{impl}}[4]::clone[0]",
"h2::frame[0]::head[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::head[0]::{{impl}}[9]::clone[0]",
"h2::frame[0]::headers[0]::decoded_header_size[0]",
"h2::frame[0]::headers[0]::{{impl}}[11]::empty[0]",
"h2::frame[0]::headers[0]::{{impl}}[13]::from[0]",
"h2::frame[0]::headers[0]::{{impl}}[15]::empty[0]",
"h2::frame[0]::headers[0]::{{impl}}[17]::from[0]",
"h2::frame[0]::headers[0]::{{impl}}[23]::eq[0]",
"h2::frame[0]::headers[0]::{{impl}}[23]::ne[0]",
"h2::frame[0]::headers[0]::{{impl}}[24]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::headers[0]::{{impl}}[25]::clone[0]",
"h2::frame[0]::headers[0]::{{impl}}[29]::eq[0]",
"h2::frame[0]::headers[0]::{{impl}}[29]::ne[0]",
"h2::frame[0]::headers[0]::{{impl}}[30]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::headers[0]::{{impl}}[31]::clone[0]",
"h2::frame[0]::priority[0]::{{impl}}[2]::dependency_id[0]",
"h2::frame[0]::priority[0]::{{impl}}[2]::new[0]",
"h2::frame[0]::priority[0]::{{impl}}[3]::eq[0]",
"h2::frame[0]::priority[0]::{{impl}}[3]::ne[0]",
"h2::frame[0]::priority[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::priority[0]::{{impl}}[6]::eq[0]",
"h2::frame[0]::priority[0]::{{impl}}[6]::ne[0]",
"h2::frame[0]::priority[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::reason[0]::{{impl}}[1]::from[0]",
"h2::frame[0]::reason[0]::{{impl}}[2]::from[0]",
"h2::frame[0]::reason[0]::{{impl}}[7]::clone[0]",
"h2::frame[0]::reason[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::reason[0]::{{impl}}[9]::eq[0]",
"h2::frame[0]::reason[0]::{{impl}}[9]::ne[0]",
"h2::frame[0]::reset[0]::{{impl}}[0]::new[0]",
"h2::frame[0]::reset[0]::{{impl}}[0]::reason[0]",
"h2::frame[0]::reset[0]::{{impl}}[0]::stream_id[0]",
"h2::frame[0]::reset[0]::{{impl}}[2]::eq[0]",
"h2::frame[0]::reset[0]::{{impl}}[2]::ne[0]",
"h2::frame[0]::reset[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::ack[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::initial_window_size[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::is_ack[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::is_push_enabled[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::max_concurrent_streams[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::max_frame_size[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::max_header_list_size[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::set_initial_window_size[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::set_max_concurrent_streams[0]",
"h2::frame[0]::settings[0]::{{impl}}[0]::set_max_header_list_size[0]",
"h2::frame[0]::settings[0]::{{impl}}[11]::default[0]",
"h2::frame[0]::settings[0]::{{impl}}[12]::eq[0]",
"h2::frame[0]::settings[0]::{{impl}}[12]::ne[0]",
"h2::frame[0]::settings[0]::{{impl}}[13]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::settings[0]::{{impl}}[14]::clone[0]",
"h2::frame[0]::settings[0]::{{impl}}[2]::from_id[0]",
"h2::frame[0]::settings[0]::{{impl}}[3]::empty[0]",
"h2::frame[0]::settings[0]::{{impl}}[4]::from[0]",
"h2::frame[0]::settings[0]::{{impl}}[5]::eq[0]",
"h2::frame[0]::settings[0]::{{impl}}[5]::ne[0]",
"h2::frame[0]::settings[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::settings[0]::{{impl}}[7]::default[0]",
"h2::frame[0]::settings[0]::{{impl}}[8]::clone[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[0]::is_client_initiated[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[0]::is_server_initiated[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[0]::is_zero[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[12]::clone[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[2]::from[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[3]::eq[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[4]::hash[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[5]::partial_cmp[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[6]::cmp[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[7]::eq[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[7]::ne[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::stream_id[0]::{{impl}}[9]::clone[0]",
"h2::frame[0]::window_update[0]::{{impl}}[0]::new[0]",
"h2::frame[0]::window_update[0]::{{impl}}[0]::size_increment[0]",
"h2::frame[0]::window_update[0]::{{impl}}[0]::stream_id[0]",
"h2::frame[0]::window_update[0]::{{impl}}[2]::eq[0]",
"h2::frame[0]::window_update[0]::{{impl}}[2]::ne[0]",
"h2::frame[0]::window_update[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"h2::frame[0]::window_update[0]::{{impl}}[4]::clone[0]",
"h2::frame[0]::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::decoder[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::decoder[0]::{{impl}}[13]::clone[0]",
"h2::hpack[0]::decoder[0]::{{impl}}[16]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::decoder[0]::{{impl}}[18]::clone[0]",
"h2::hpack[0]::decoder[0]::{{impl}}[9]::from[0]",
"h2::hpack[0]::encoder[0]::encode_size_update[0]",
"h2::hpack[0]::encoder[0]::{{impl}}[10]::clone[0]",
"h2::hpack[0]::encoder[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::encoder[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::huffman[0]::{{impl}}[0]::is_final[0]",
"h2::hpack[0]::huffman[0]::{{impl}}[0]::new[0]",
"h2::hpack[0]::table[0]::to_raw_capacity[0]",
"h2::hpack[0]::table[0]::usable_capacity[0]",
"h2::hpack[0]::table[0]::{{impl}}[10]::eq[0]",
"h2::hpack[0]::table[0]::{{impl}}[10]::ne[0]",
"h2::hpack[0]::table[0]::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::table[0]::{{impl}}[12]::clone[0]",
"h2::hpack[0]::table[0]::{{impl}}[5]::eq[0]",
"h2::hpack[0]::table[0]::{{impl}}[5]::ne[0]",
"h2::hpack[0]::table[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"h2::hpack[0]::table[0]::{{impl}}[8]::clone[0]",
"h2::proto[0]::connection[0]::{{impl}}[5]::clone[0]",
"h2::proto[0]::go_away[0]::{{impl}}[0]::go_away_now[0]",
"h2::proto[0]::go_away[0]::{{impl}}[0]::is_going_away[0]",
"h2::proto[0]::go_away[0]::{{impl}}[0]::new[0]",
"h2::proto[0]::go_away[0]::{{impl}}[0]::should_close_now[0]",
"h2::proto[0]::peer[0]::Peer[0]::is_local_init[0]",
"h2::proto[0]::peer[0]::{{impl}}[0]::is_local_init[0]",
"h2::proto[0]::peer[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"h2::proto[0]::peer[0]::{{impl}}[3]::clone[0]",
"h2::proto[0]::ping_pong[0]::{{impl}}[1]::is_shutdown[0]",
"h2::proto[0]::settings[0]::{{impl}}[0]::new[0]",
"h2::proto[0]::streams[0]::buffer[0]::{{impl}}[1]::is_empty[0]",
"h2::proto[0]::streams[0]::buffer[0]::{{impl}}[1]::new[0]",
"h2::proto[0]::streams[0]::buffer[0]::{{impl}}[4]::clone[0]",
"h2::proto[0]::streams[0]::buffer[0]::{{impl}}[6]::default[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::can_inc_num_recv_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::can_inc_num_reset_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::can_inc_num_send_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::dec_num_reset_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::has_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::inc_num_reset_streams[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[0]::peer[0]",
"h2::proto[0]::streams[0]::counts[0]::{{impl}}[1]::drop[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[0]::assign_capacity[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[0]::available[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[0]::claim_capacity[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[0]::new[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[0]::window_size[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[11]::clone[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[13]::partial_cmp[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[14]::eq[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[14]::ne[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[17]::clone[0]",
"h2::proto[0]::streams[0]::flow_control[0]::{{impl}}[3]::eq[0]",
"h2::proto[0]::streams[0]::prioritize[0]::{{impl}}[1]::advance[0]",
"h2::proto[0]::streams[0]::prioritize[0]::{{impl}}[1]::remaining[0]",
"h2::proto[0]::streams[0]::prioritize[0]::{{impl}}[5]::assert_receiver_is_total_eq[0]",
"h2::proto[0]::streams[0]::recv[0]::{{impl}}[2]::is_push_promise[0]",
"h2::proto[0]::streams[0]::recv[0]::{{impl}}[9]::clone[0]",
"h2::proto[0]::streams[0]::send[0]::{{impl}}[0]::init_window_sz[0]",
"h2::proto[0]::streams[0]::send[0]::{{impl}}[0]::new[0]",
"h2::proto[0]::streams[0]::send[0]::{{impl}}[0]::open[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::get_scheduled_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_closed[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_idle[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_local_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_recv_closed[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_recv_headers[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_recv_streaming[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_scheduled_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_send_closed[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::is_send_streaming[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::send_open[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::set_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[0]::set_scheduled_reset[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[11]::clone[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[1]::default[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[2]::default[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[3]::clone[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[6]::clone[0]",
"h2::proto[0]::streams[0]::state[0]::{{impl}}[8]::clone[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[15]::assert_receiver_is_total_eq[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[16]::eq[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[16]::ne[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[18]::clone[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[22]::clone[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[6]::new[0]",
"h2::proto[0]::streams[0]::store[0]::{{impl}}[6]::take[0]",
"h2::proto[0]::streams[0]::stream[0]::{{impl}}[7]::is_head[0]",
"h2::server[0]::{{impl}}[13]::dyn[0]",
"h2::server[0]::{{impl}}[13]::is_server[0]",
"h2::server[0]::{{impl}}[19]::clone[0]",
"h2::server[0]::{{impl}}[3]::initial_connection_window_size[0]",
"h2::server[0]::{{impl}}[3]::initial_window_size[0]",
"h2::server[0]::{{impl}}[3]::max_concurrent_reset_streams[0]",
"h2::server[0]::{{impl}}[3]::max_concurrent_streams[0]",
"h2::server[0]::{{impl}}[3]::max_frame_size[0]",
"h2::server[0]::{{impl}}[3]::max_header_list_size[0]",
"h2::server[0]::{{impl}}[3]::reset_stream_duration[0]",
"h2::server[0]::{{impl}}[4]::default[0]",
"h2::share[0]::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"h2::share[0]::{{impl}}[11]::clone[0]",
"h2::share[0]::{{impl}}[1]::from_internal[0]",
"h2::share[0]::{{impl}}[8]::hash[0]",
"h2::share[0]::{{impl}}[9]::eq[0]",
"h2::share[0]::{{impl}}[9]::ne[0]"
]
