CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"conv::ConvUtil[0]::into_as[0]",
"conv::errors[0]::{{impl}}[0]::from[0]",
"conv::errors[0]::{{impl}}[102]::into_inner[0]",
"conv::errors[0]::{{impl}}[107]::from[0]",
"conv::errors[0]::{{impl}}[108]::from[0]",
"conv::errors[0]::{{impl}}[113]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[114]::clone[0]",
"conv::errors[0]::{{impl}}[121]::from[0]",
"conv::errors[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[17]::into_inner[0]",
"conv::errors[0]::{{impl}}[1]::from[0]",
"conv::errors[0]::{{impl}}[22]::from[0]",
"conv::errors[0]::{{impl}}[23]::from[0]",
"conv::errors[0]::{{impl}}[24]::from[0]",
"conv::errors[0]::{{impl}}[25]::from[0]",
"conv::errors[0]::{{impl}}[30]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[31]::clone[0]",
"conv::errors[0]::{{impl}}[39]::from[0]",
"conv::errors[0]::{{impl}}[40]::from[0]",
"conv::errors[0]::{{impl}}[41]::from[0]",
"conv::errors[0]::{{impl}}[46]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[47]::clone[0]",
"conv::errors[0]::{{impl}}[49]::partial_cmp[0]",
"conv::errors[0]::{{impl}}[4]::saturate[0]",
"conv::errors[0]::{{impl}}[50]::cmp[0]",
"conv::errors[0]::{{impl}}[51]::eq[0]",
"conv::errors[0]::{{impl}}[51]::ne[0]",
"conv::errors[0]::{{impl}}[52]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[53]::clone[0]",
"conv::errors[0]::{{impl}}[55]::into_inner[0]",
"conv::errors[0]::{{impl}}[5]::saturate[0]",
"conv::errors[0]::{{impl}}[60]::partial_cmp[0]",
"conv::errors[0]::{{impl}}[61]::cmp[0]",
"conv::errors[0]::{{impl}}[62]::eq[0]",
"conv::errors[0]::{{impl}}[62]::ne[0]",
"conv::errors[0]::{{impl}}[63]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[64]::clone[0]",
"conv::errors[0]::{{impl}}[66]::into_inner[0]",
"conv::errors[0]::{{impl}}[6]::saturate[0]",
"conv::errors[0]::{{impl}}[71]::partial_cmp[0]",
"conv::errors[0]::{{impl}}[72]::cmp[0]",
"conv::errors[0]::{{impl}}[73]::eq[0]",
"conv::errors[0]::{{impl}}[73]::ne[0]",
"conv::errors[0]::{{impl}}[74]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[75]::clone[0]",
"conv::errors[0]::{{impl}}[77]::into_inner[0]",
"conv::errors[0]::{{impl}}[7]::unwrap_ok[0]",
"conv::errors[0]::{{impl}}[85]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[88]::into_inner[0]",
"conv::errors[0]::{{impl}}[93]::from[0]",
"conv::errors[0]::{{impl}}[94]::from[0]",
"conv::errors[0]::{{impl}}[95]::from[0]",
"conv::errors[0]::{{impl}}[99]::assert_receiver_is_total_eq[0]",
"conv::errors[0]::{{impl}}[9]::unwrap_or_invalid[0]",
"conv::impls[0]::lang_char_to_int[0]::{{impl}}[0]::try_from[0]",
"conv::impls[0]::lang_char_to_int[0]::{{impl}}[8]::try_from[0]",
"conv::impls[0]::lang_char_to_int[0]::{{impl}}[9]::try_from[0]",
"conv::impls[0]::lang_int_to_char[0]::{{impl}}[0]::try_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[0]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[120]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[121]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[122]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[123]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[124]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[125]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[126]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[127]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[128]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[150]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[151]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[152]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[153]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[154]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[155]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[180]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[181]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[182]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[1]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[2]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[30]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[31]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[32]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[33]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[34]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[35]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[3]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[4]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[5]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[60]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[61]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[62]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[6]::value_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[7]::approx_from[0]",
"conv::impls[0]::lang_ints[0]::{{impl}}[8]::approx_from[0]",
"conv::{{impl}}[0]::approx_from[0]",
"conv::{{impl}}[10]::value_from[0]",
"conv::{{impl}}[8]::try_from[0]"
]
