CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"endian_type::{{impl}}[14]::into[0]",
"endian_type::{{impl}}[15]::from[0]",
"endian_type::{{impl}}[16]::from[0]",
"endian_type::{{impl}}[17]::into[0]",
"endian_type::{{impl}}[18]::from[0]",
"endian_type::{{impl}}[19]::from[0]",
"endian_type::{{impl}}[20]::into[0]",
"endian_type::{{impl}}[21]::from[0]",
"endian_type::{{impl}}[22]::from[0]",
"endian_type::{{impl}}[23]::into[0]",
"endian_type::{{impl}}[24]::from[0]",
"endian_type::{{impl}}[25]::from[0]",
"endian_type::{{impl}}[26]::into[0]",
"endian_type::{{impl}}[27]::from[0]",
"endian_type::{{impl}}[28]::from[0]",
"endian_type::{{impl}}[29]::into[0]",
"endian_type::{{impl}}[2]::partial_cmp[0]",
"endian_type::{{impl}}[30]::from[0]",
"endian_type::{{impl}}[31]::from[0]",
"endian_type::{{impl}}[32]::into[0]",
"endian_type::{{impl}}[33]::from[0]",
"endian_type::{{impl}}[34]::from[0]",
"endian_type::{{impl}}[35]::into[0]",
"endian_type::{{impl}}[36]::from[0]",
"endian_type::{{impl}}[37]::from[0]",
"endian_type::{{impl}}[38]::partial_cmp[0]",
"endian_type::{{impl}}[39]::cmp[0]",
"endian_type::{{impl}}[3]::cmp[0]",
"endian_type::{{impl}}[40]::hash[0]",
"endian_type::{{impl}}[41]::eq[0]",
"endian_type::{{impl}}[41]::ne[0]",
"endian_type::{{impl}}[42]::assert_receiver_is_total_eq[0]",
"endian_type::{{impl}}[44]::clone[0]",
"endian_type::{{impl}}[4]::hash[0]",
"endian_type::{{impl}}[50]::into[0]",
"endian_type::{{impl}}[51]::from[0]",
"endian_type::{{impl}}[52]::from[0]",
"endian_type::{{impl}}[53]::into[0]",
"endian_type::{{impl}}[54]::from[0]",
"endian_type::{{impl}}[55]::from[0]",
"endian_type::{{impl}}[56]::into[0]",
"endian_type::{{impl}}[57]::from[0]",
"endian_type::{{impl}}[58]::from[0]",
"endian_type::{{impl}}[59]::into[0]",
"endian_type::{{impl}}[5]::eq[0]",
"endian_type::{{impl}}[5]::ne[0]",
"endian_type::{{impl}}[60]::from[0]",
"endian_type::{{impl}}[61]::from[0]",
"endian_type::{{impl}}[62]::into[0]",
"endian_type::{{impl}}[63]::from[0]",
"endian_type::{{impl}}[64]::from[0]",
"endian_type::{{impl}}[65]::into[0]",
"endian_type::{{impl}}[66]::from[0]",
"endian_type::{{impl}}[67]::from[0]",
"endian_type::{{impl}}[68]::into[0]",
"endian_type::{{impl}}[69]::from[0]",
"endian_type::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"endian_type::{{impl}}[70]::from[0]",
"endian_type::{{impl}}[71]::into[0]",
"endian_type::{{impl}}[72]::from[0]",
"endian_type::{{impl}}[73]::from[0]",
"endian_type::{{impl}}[8]::clone[0]"
]
