CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"libsqlite3_sys::error[0]::{{impl}}[12]::clone[0]",
"libsqlite3_sys::error[0]::{{impl}}[3]::assert_receiver_is_total_eq[0]",
"libsqlite3_sys::error[0]::{{impl}}[7]::clone[0]",
"libsqlite3_sys::error[0]::{{impl}}[8]::assert_receiver_is_total_eq[0]",
"libsqlite3_sys::error[0]::{{impl}}[9]::eq[0]",
"libsqlite3_sys::error[0]::{{impl}}[9]::ne[0]",
"libsqlite3_sys::{{impl}}[7]::clone[0]",
"libsqlite3_sys::{{impl}}[8]::clone[0]",
"libsqlite3_sys::{{impl}}[9]::clone[0]"
]
