CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"slog_term::{{impl}}[16]::new[0]",
"slog_term::{{impl}}[27]::new[0]",
"slog_term::{{impl}}[28]::level_to_color[0]",
"slog_term::{{impl}}[28]::new[0]"
]
