CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"ws::factory[0]::test[0]::{{impl}}[1]::eq[0]",
"ws::factory[0]::test[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"ws::handler[0]::test[0]::{{impl}}[1]::eq[0]",
"ws::handler[0]::test[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"ws::io[0]::{{impl}}[0]::is_active[0]",
"ws::io[0]::{{impl}}[3]::clone[0]",
"ws::protocol[0]::{{impl}}[0]::is_control[0]",
"ws::protocol[0]::{{impl}}[12]::clone[0]",
"ws::protocol[0]::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"ws::protocol[0]::{{impl}}[2]::into[0]",
"ws::protocol[0]::{{impl}}[3]::from[0]",
"ws::protocol[0]::{{impl}}[4]::into[0]",
"ws::protocol[0]::{{impl}}[5]::from[0]",
"ws::protocol[0]::{{impl}}[7]::clone[0]",
"ws::protocol[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"ws::stream[0]::{{impl}}[2]::evented[0]",
"ws::stream[0]::{{impl}}[2]::is_negotiating[0]",
"ws::stream[0]::{{impl}}[2]::tcp[0]",
"ws::{{impl}}[2]::new[0]",
"ws::{{impl}}[2]::with_settings[0]",
"ws::{{impl}}[4]::clone[0]",
"ws::{{impl}}[7]::clone[0]",
"ws::{{impl}}[8]::default[0]"
]
