CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"string::{{impl}}[0]::get_ref[0]",
"string::{{impl}}[0]::into_inner[0]",
"string::{{impl}}[10]::hash[0]",
"string::{{impl}}[11]::partial_cmp[0]",
"string::{{impl}}[12]::cmp[0]",
"string::{{impl}}[13]::eq[0]",
"string::{{impl}}[13]::ne[0]",
"string::{{impl}}[14]::assert_receiver_is_total_eq[0]",
"string::{{impl}}[15]::clone[0]",
"string::{{impl}}[9]::default[0]"
]
