CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"tokio_current_thread::EXECUTOR_ID[0]::__init[0]",
"tokio_current_thread::scheduler[0]::abort[0]::{{impl}}[0]::drop[0]",
"tokio_current_thread::{{impl}}[0]::has_polled[0]",
"tokio_current_thread::{{impl}}[24]::is_timeout[0]",
"tokio_current_thread::{{impl}}[24]::new[0]",
"tokio_current_thread::{{impl}}[26]::into_inner[0]"
]
