CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"r2d2::CustomizeConnection[0]::on_acquire[0]",
"r2d2::CustomizeConnection[0]::on_release[0]",
"r2d2::{{impl}}[14]::clone[0]",
"r2d2::{{impl}}[17]::clone[0]",
"r2d2::{{impl}}[20]::clone[0]"
]
