CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"stb_truetype::mac_eid[0]",
"stb_truetype::mac_lang[0]",
"stb_truetype::microsoft_eid[0]",
"stb_truetype::microsoft_lang[0]",
"stb_truetype::platform_id[0]",
"stb_truetype::unicode_eid[0]",
"stb_truetype::{{impl}}[11]::clone[0]",
"stb_truetype::{{impl}}[14]::clone[0]",
"stb_truetype::{{impl}}[17]::clone[0]",
"stb_truetype::{{impl}}[1]::get_codepoint_box[0]",
"stb_truetype::{{impl}}[1]::get_codepoint_h_metrics[0]",
"stb_truetype::{{impl}}[1]::get_codepoint_kern_advance[0]",
"stb_truetype::{{impl}}[1]::get_num_glyphs[0]",
"stb_truetype::{{impl}}[20]::clone[0]",
"stb_truetype::{{impl}}[25]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[28]::clone[0]",
"stb_truetype::{{impl}}[33]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[37]::clone[0]",
"stb_truetype::{{impl}}[41]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[45]::clone[0]",
"stb_truetype::{{impl}}[49]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[4]::clone[0]",
"stb_truetype::{{impl}}[53]::clone[0]",
"stb_truetype::{{impl}}[57]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[61]::clone[0]",
"stb_truetype::{{impl}}[65]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[69]::clone[0]",
"stb_truetype::{{impl}}[6]::clone[0]",
"stb_truetype::{{impl}}[73]::assert_receiver_is_total_eq[0]",
"stb_truetype::{{impl}}[77]::clone[0]",
"stb_truetype::{{impl}}[8]::assert_receiver_is_total_eq[0]"
]
