CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"cexpr::expr[0]::{{impl}}[13]::concat_str[0]::_unify[0]",
"cexpr::literal[0]::c_char[0]::{{closure}}[0]::_unify[0]",
"cexpr::literal[0]::c_int[0]::_unify[0]",
"cexpr::literal[0]::c_string[0]::{{closure}}[0]::_unify[0]",
"cexpr::literal[0]::c_string[0]::{{closure}}[0]::_unify[1]",
"cexpr::literal[0]::escaped_char[0]::{{closure}}[0]::_unify[0]",
"cexpr::literal[0]::escaped_char[0]::{{closure}}[0]::_unify[1]",
"cexpr::literal[0]::one_literal[0]::_unify[0]",
"cexpr::literal[0]::one_literal[0]::_unify[1]",
"cexpr::literal[0]::one_literal[0]::_unify[2]",
"cexpr::literal[0]::one_literal[0]::_unify[3]",
"cexpr::literal[0]::{{impl}}[0]::from[0]",
"cexpr::literal[0]::{{impl}}[2]::assert_receiver_is_total_eq[0]",
"cexpr::literal[0]::{{impl}}[4]::clone[0]",
"cexpr::token[0]::{{impl}}[1]::assert_receiver_is_total_eq[0]",
"cexpr::token[0]::{{impl}}[3]::clone[0]"
]
