CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rustc_hash::{{impl}}[0]::default[0]",
"rustc_hash::{{impl}}[2]::write_usize[0]"
]
