CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rustc_rayon_core::current_num_threads[0]",
"rustc_rayon_core::job[0]::{{impl}}[5]::new[0]",
"rustc_rayon_core::latch[0]::{{impl}}[0]::new[0]",
"rustc_rayon_core::latch[0]::{{impl}}[1]::probe[0]",
"rustc_rayon_core::latch[0]::{{impl}}[2]::set[0]",
"rustc_rayon_core::latch[0]::{{impl}}[6]::increment[0]",
"rustc_rayon_core::latch[0]::{{impl}}[6]::new[0]",
"rustc_rayon_core::latch[0]::{{impl}}[7]::probe[0]",
"rustc_rayon_core::latch[0]::{{impl}}[8]::set[0]",
"rustc_rayon_core::log[0]::{{impl}}[1]::deref[0]",
"rustc_rayon_core::log[0]::{{impl}}[2]::initialize[0]",
"rustc_rayon_core::registry[0]::{{impl}}[10]::clone[0]",
"rustc_rayon_core::registry[0]::{{impl}}[5]::cmp[0]",
"rustc_rayon_core::registry[0]::{{impl}}[6]::partial_cmp[0]",
"rustc_rayon_core::registry[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"rustc_rayon_core::registry[0]::{{impl}}[8]::eq[0]",
"rustc_rayon_core::registry[0]::{{impl}}[8]::ne[0]",
"rustc_rayon_core::tlv[0]::TLV[0]::__init[0]"
]
