CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"rmp::decode[0]::ext[0]::{{impl}}[0]::eq[0]",
"rmp::decode[0]::ext[0]::{{impl}}[0]::ne[0]",
"rmp::marker[0]::{{impl}}[1]::from[0]",
"rmp::marker[0]::{{impl}}[2]::into[0]",
"rmp::marker[0]::{{impl}}[6]::clone[0]"
]
