CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"parity_wasm::builder[0]::code[0]::{{impl}}[5]::with_callback[0]",
"parity_wasm::builder[0]::export[0]::{{impl}}[4]::with_callback[0]",
"parity_wasm::builder[0]::import[0]::{{impl}}[4]::with_callback[0]",
"parity_wasm::builder[0]::invoke[0]::{{impl}}[0]::invoke[0]",
"parity_wasm::builder[0]::misc[0]::{{impl}}[0]::with_callback[0]",
"parity_wasm::builder[0]::misc[0]::{{impl}}[1]::with_callback[0]",
"parity_wasm::elements[0]::export_entry[0]::{{impl}}[7]::clone[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[0]::new[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[0]::type_ref[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[0]::type_ref_mut[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[10]::clone[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[13]::eq[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[13]::ne[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[14]::clone[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[3]::count[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[3]::new[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[3]::value_type[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[9]::eq[0]",
"parity_wasm::elements[0]::func[0]::{{impl}}[9]::ne[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[0]::content_type[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[0]::is_mutable[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[0]::new[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[17]::eq[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[17]::ne[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[18]::clone[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[21]::eq[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[21]::ne[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[22]::clone[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[25]::eq[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[25]::ne[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[26]::clone[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[29]::eq[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[29]::ne[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[30]::clone[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[34]::clone[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[3]::elem_type[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[3]::limits[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[3]::new[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[6]::initial[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[6]::maximum[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[6]::new[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[6]::shared[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[9]::limits[0]",
"parity_wasm::elements[0]::import_entry[0]::{{impl}}[9]::new[0]",
"parity_wasm::elements[0]::module[0]::{{impl}}[10]::clone[0]",
"parity_wasm::elements[0]::ops[0]::{{impl}}[21]::eq[0]",
"parity_wasm::elements[0]::ops[0]::{{impl}}[21]::ne[0]",
"parity_wasm::elements[0]::ops[0]::{{impl}}[23]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[10]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[11]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[14]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[15]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[18]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[19]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[1]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[22]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[23]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[26]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[27]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[2]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[31]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[33]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[36]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[37]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[38]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[39]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[49]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[49]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[50]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[53]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[53]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[54]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[57]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[57]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[58]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[61]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[61]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[62]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[65]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[65]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[66]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[69]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[69]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[6]::from[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[70]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[73]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[73]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[74]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[77]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[77]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[78]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[81]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[81]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[82]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[85]::eq[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[85]::ne[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[86]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[92]::clone[0]",
"parity_wasm::elements[0]::primitives[0]::{{impl}}[9]::from[0]",
"parity_wasm::elements[0]::reloc_section[0]::{{impl}}[11]::clone[0]",
"parity_wasm::elements[0]::types[0]::{{impl}}[19]::clone[0]",
"parity_wasm::elements[0]::types[0]::{{impl}}[23]::clone[0]",
"parity_wasm::elements[0]::types[0]::{{impl}}[30]::clone[0]",
"parity_wasm::io[0]::{{impl}}[0]::new[0]",
"parity_wasm::io[0]::{{impl}}[0]::position[0]"
]
