CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"number_prefix::{{impl}}[11]::assert_receiver_is_total_eq[0]",
"number_prefix::{{impl}}[6]::clone[0]",
"number_prefix::{{impl}}[7]::assert_receiver_is_total_eq[0]"
]
