CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"postgres::_ensure_send[0]::_is_send[0]",
"postgres::priv_io[0]::{{impl}}[3]::get_mut[0]",
"postgres::priv_io[0]::{{impl}}[3]::get_ref[0]",
"postgres::priv_io[0]::{{impl}}[4]::as_raw_fd[0]",
"postgres::stmt[0]::{{impl}}[6]::from_u16[0]",
"postgres::stmt[0]::{{impl}}[7]::assert_receiver_is_total_eq[0]",
"postgres::stmt[0]::{{impl}}[9]::clone[0]",
"postgres::transaction[0]::{{impl}}[1]::default[0]",
"postgres::transaction[0]::{{impl}}[2]::deferrable[0]",
"postgres::transaction[0]::{{impl}}[2]::isolation_level[0]",
"postgres::transaction[0]::{{impl}}[2]::new[0]",
"postgres::transaction[0]::{{impl}}[2]::read_only[0]",
"postgres::transaction[0]::{{impl}}[6]::assert_receiver_is_total_eq[0]",
"postgres::transaction[0]::{{impl}}[9]::clone[0]",
"postgres::{{impl}}[9]::clone[0]"
]
