CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"csv_core::reader[0]::{{impl}}[18]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[22]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[26]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[30]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[34]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[38]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[40]::clone[0]",
"csv_core::reader[0]::{{impl}}[42]::partial_cmp[0]",
"csv_core::reader[0]::{{impl}}[43]::eq[0]",
"csv_core::reader[0]::{{impl}}[43]::ne[0]",
"csv_core::reader[0]::{{impl}}[44]::cmp[0]",
"csv_core::reader[0]::{{impl}}[45]::assert_receiver_is_total_eq[0]",
"csv_core::reader[0]::{{impl}}[48]::clone[0]",
"csv_core::reader[0]::{{impl}}[4]::is_field_final[0]",
"csv_core::reader[0]::{{impl}}[4]::is_record_final[0]",
"csv_core::reader[0]::{{impl}}[8]::is_start[0]",
"csv_core::reader[0]::{{impl}}[8]::start[0]",
"csv_core::writer[0]::moving[0]",
"csv_core::writer[0]::{{impl}}[13]::clone[0]",
"csv_core::writer[0]::{{impl}}[6]::default[0]",
"csv_core::writer[0]::{{impl}}[9]::assert_receiver_is_total_eq[0]",
"csv_core::{{impl}}[1]::default[0]",
"csv_core::{{impl}}[2]::default[0]",
"csv_core::{{impl}}[5]::clone[0]",
"csv_core::{{impl}}[8]::clone[0]"
]
