CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"sdl2_sys::{{impl}}[100]::clone[0]",
"sdl2_sys::{{impl}}[10]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[119]::clone[0]",
"sdl2_sys::{{impl}}[124]::clone[0]",
"sdl2_sys::{{impl}}[12]::clone[0]",
"sdl2_sys::{{impl}}[152]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[154]::clone[0]",
"sdl2_sys::{{impl}}[158]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[160]::clone[0]",
"sdl2_sys::{{impl}}[164]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[166]::clone[0]",
"sdl2_sys::{{impl}}[170]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[172]::clone[0]",
"sdl2_sys::{{impl}}[176]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[178]::clone[0]",
"sdl2_sys::{{impl}}[182]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[184]::clone[0]",
"sdl2_sys::{{impl}}[187]::clone[0]",
"sdl2_sys::{{impl}}[196]::clone[0]",
"sdl2_sys::{{impl}}[199]::clone[0]",
"sdl2_sys::{{impl}}[19]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[203]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[205]::clone[0]",
"sdl2_sys::{{impl}}[209]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[211]::clone[0]",
"sdl2_sys::{{impl}}[215]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[217]::clone[0]",
"sdl2_sys::{{impl}}[21]::clone[0]",
"sdl2_sys::{{impl}}[224]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[226]::clone[0]",
"sdl2_sys::{{impl}}[236]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[238]::clone[0]",
"sdl2_sys::{{impl}}[242]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[244]::clone[0]",
"sdl2_sys::{{impl}}[248]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[250]::clone[0]",
"sdl2_sys::{{impl}}[254]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[256]::clone[0]",
"sdl2_sys::{{impl}}[260]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[262]::clone[0]",
"sdl2_sys::{{impl}}[266]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[268]::clone[0]",
"sdl2_sys::{{impl}}[272]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[274]::clone[0]",
"sdl2_sys::{{impl}}[278]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[27]::clone[0]",
"sdl2_sys::{{impl}}[280]::clone[0]",
"sdl2_sys::{{impl}}[284]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[286]::clone[0]",
"sdl2_sys::{{impl}}[290]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[292]::clone[0]",
"sdl2_sys::{{impl}}[296]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[298]::clone[0]",
"sdl2_sys::{{impl}}[301]::clone[0]",
"sdl2_sys::{{impl}}[308]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[310]::clone[0]",
"sdl2_sys::{{impl}}[314]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[316]::clone[0]",
"sdl2_sys::{{impl}}[31]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[326]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[328]::clone[0]",
"sdl2_sys::{{impl}}[332]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[334]::clone[0]",
"sdl2_sys::{{impl}}[33]::clone[0]",
"sdl2_sys::{{impl}}[341]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[343]::clone[0]",
"sdl2_sys::{{impl}}[350]::clone[0]",
"sdl2_sys::{{impl}}[354]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[356]::clone[0]",
"sdl2_sys::{{impl}}[360]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[362]::clone[0]",
"sdl2_sys::{{impl}}[369]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[371]::clone[0]",
"sdl2_sys::{{impl}}[374]::clone[0]",
"sdl2_sys::{{impl}}[377]::clone[0]",
"sdl2_sys::{{impl}}[380]::clone[0]",
"sdl2_sys::{{impl}}[389]::clone[0]",
"sdl2_sys::{{impl}}[392]::clone[0]",
"sdl2_sys::{{impl}}[395]::clone[0]",
"sdl2_sys::{{impl}}[398]::clone[0]",
"sdl2_sys::{{impl}}[401]::clone[0]",
"sdl2_sys::{{impl}}[404]::clone[0]",
"sdl2_sys::{{impl}}[407]::clone[0]",
"sdl2_sys::{{impl}}[410]::clone[0]",
"sdl2_sys::{{impl}}[413]::clone[0]",
"sdl2_sys::{{impl}}[416]::clone[0]",
"sdl2_sys::{{impl}}[419]::clone[0]",
"sdl2_sys::{{impl}}[422]::clone[0]",
"sdl2_sys::{{impl}}[437]::clone[0]",
"sdl2_sys::{{impl}}[440]::clone[0]",
"sdl2_sys::{{impl}}[452]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[454]::clone[0]",
"sdl2_sys::{{impl}}[475]::clone[0]",
"sdl2_sys::{{impl}}[484]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[486]::clone[0]",
"sdl2_sys::{{impl}}[490]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[492]::clone[0]",
"sdl2_sys::{{impl}}[496]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[498]::clone[0]",
"sdl2_sys::{{impl}}[49]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[4]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[502]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[504]::clone[0]",
"sdl2_sys::{{impl}}[508]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[510]::clone[0]",
"sdl2_sys::{{impl}}[516]::clone[0]",
"sdl2_sys::{{impl}}[51]::clone[0]",
"sdl2_sys::{{impl}}[520]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[522]::clone[0]",
"sdl2_sys::{{impl}}[532]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[534]::clone[0]",
"sdl2_sys::{{impl}}[538]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[540]::clone[0]",
"sdl2_sys::{{impl}}[547]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[549]::clone[0]",
"sdl2_sys::{{impl}}[553]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[555]::clone[0]",
"sdl2_sys::{{impl}}[559]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[561]::clone[0]",
"sdl2_sys::{{impl}}[571]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[573]::clone[0]",
"sdl2_sys::{{impl}}[580]::clone[0]",
"sdl2_sys::{{impl}}[586]::clone[0]",
"sdl2_sys::{{impl}}[589]::clone[0]",
"sdl2_sys::{{impl}}[592]::clone[0]",
"sdl2_sys::{{impl}}[613]::clone[0]",
"sdl2_sys::{{impl}}[631]::clone[0]",
"sdl2_sys::{{impl}}[634]::clone[0]",
"sdl2_sys::{{impl}}[637]::clone[0]",
"sdl2_sys::{{impl}}[640]::clone[0]",
"sdl2_sys::{{impl}}[643]::clone[0]",
"sdl2_sys::{{impl}}[646]::clone[0]",
"sdl2_sys::{{impl}}[649]::clone[0]",
"sdl2_sys::{{impl}}[655]::clone[0]",
"sdl2_sys::{{impl}}[6]::clone[0]",
"sdl2_sys::{{impl}}[71]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[73]::clone[0]",
"sdl2_sys::{{impl}}[772]::clone[0]",
"sdl2_sys::{{impl}}[775]::clone[0]",
"sdl2_sys::{{impl}}[784]::clone[0]",
"sdl2_sys::{{impl}}[792]::clone[0]",
"sdl2_sys::{{impl}}[80]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[811]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[813]::clone[0]",
"sdl2_sys::{{impl}}[82]::clone[0]",
"sdl2_sys::{{impl}}[841]::clone[0]",
"sdl2_sys::{{impl}}[849]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[851]::clone[0]",
"sdl2_sys::{{impl}}[85]::clone[0]",
"sdl2_sys::{{impl}}[861]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[863]::clone[0]",
"sdl2_sys::{{impl}}[866]::clone[0]",
"sdl2_sys::{{impl}}[870]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[872]::clone[0]",
"sdl2_sys::{{impl}}[879]::clone[0]",
"sdl2_sys::{{impl}}[889]::assert_receiver_is_total_eq[0]",
"sdl2_sys::{{impl}}[88]::clone[0]",
"sdl2_sys::{{impl}}[891]::clone[0]",
"sdl2_sys::{{impl}}[919]::clone[0]",
"sdl2_sys::{{impl}}[91]::clone[0]",
"sdl2_sys::{{impl}}[922]::clone[0]",
"sdl2_sys::{{impl}}[925]::clone[0]",
"sdl2_sys::{{impl}}[928]::clone[0]",
"sdl2_sys::{{impl}}[97]::clone[0]"
]
