CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"matrixmultiply::dgemm_kernel[0]::{{impl}}[0]::align_to[0]",
"matrixmultiply::dgemm_kernel[0]::{{impl}}[0]::always_masked[0]",
"matrixmultiply::sgemm_kernel[0]::{{impl}}[0]::align_to[0]",
"matrixmultiply::sgemm_kernel[0]::{{impl}}[0]::always_masked[0]",
"matrixmultiply::util[0]::range_chunk[0]",
"matrixmultiply::util[0]::round_up_to[0]",
"matrixmultiply::util[0]::{{impl}}[0]::next[0]"
]
