CHECK_PANICS = false
CHECK_BINARY_OPERATIONS = false
ENCODE_UNSIGNED_NUM_CONSTRAINT = false
ENABLE_WHITELIST = true
WHITELIST = [
"chalk_macros::{{impl}}[3]::initialize[0]",
"chalk_macros::{{impl}}[5]::initialize[0]"
]
